// Auto-generated file - do not edit manually
// Generated from: Ruu's OC List 2025 - [INFO] (1).csv and Ruu's OC List 2025 - Copy of [OC List].csv
// Run: npx tsx scripts/utilities/generate-csv-options.ts

export const csvOptions: Record<string, string[]> = {
  "pronouns": [
    "He/Him",
    "He/They",
    "She/He",
    "She/He/They",
    "She/Her",
    "She/They",
    "They/He",
    "They/She",
    "They/Them"
  ],
  "gender_identity": [
    "Agender",
    "Androgynous",
    "Bigender",
    "Cisgender",
    "Demiboy",
    "Demigirl",
    "Genderfluid",
    "Genderqueer",
    "Intersex",
    "Neutrois",
    "Non-binary",
    "Pangender",
    "Third Gender",
    "Transgender",
    "Two-spirit"
  ],
  "romantic": [
    "Biromantic",
    "Demiromantic",
    "Greyromantic",
    "Heteroromantic",
    "Homoromantic",
    "Lithromantic",
    "Monogamy",
    "Panromantic"
  ],
  "sexual": [
    "Androsexual",
    "Asexual",
    "Autosexual",
    "Bisexual",
    "Demisexual",
    "Greysexual",
    "Gynosexual",
    "Heterosexual",
    "Homosexual",
    "Lithsexual",
    "Pansexual",
    "Polysexual",
    "Queer",
    "Sapiosexual",
    "Skoliosexual"
  ],
  "relationship_type": [
    "Aromantic",
    "Asexual",
    "Casual Relationship",
    "Co-parenting",
    "Dom/sub (d/s)",
    "Friends With Benefits",
    "Group Marriage",
    "Long-distance Relationship (ldr)",
    "Monogamy",
    "Open Relationship",
    "Platonic Relationship",
    "Polyamory",
    "Polyandry",
    "Polygamy",
    "Polygyny",
    "Primary/secondary",
    "Quad",
    "Queerplatonic Relationship (qpr)",
    "Relationship Anarchy",
    "Swinging",
    "Triad"
  ],
  "sex": [
    "Androgyne",
    "Female",
    "Intersex",
    "Male"
  ],
  "accent": [
    "Boston",
    "Brazilian Portuguese",
    "Californian",
    "Canadian",
    "Caribbean",
    "Chicago",
    "Chicano English (Mexican-American)",
    "Chinese",
    "Dutch",
    "German",
    "Greek",
    "Hawaiian Pidgin",
    "Indian",
    "Jamaican",
    "Japanese",
    "Korean",
    "Midwestern",
    "Minnesotan",
    "New Orleans (cajun)",
    "New York",
    "New Zealand",
    "Pacific Northwest",
    "Philadelphia",
    "Polish",
    "Russian",
    "South African",
    "Southern Appalachian",
    "Southern Californian (SoCal)",
    "Texan",
    "Turkish",
    "Valley (California)",
    "Welsh"
  ],
  "nationality": [
    "Afghan",
    "American",
    "Argentine",
    "Australian",
    "Austrian",
    "Bangladeshi",
    "Belgian",
    "Bosnian",
    "Brazilian",
    "British",
    "Bulgarian",
    "Canadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Czech",
    "Danish",
    "Dominican",
    "Dutch",
    "Egyptian",
    "Emirati",
    "Ethiopian",
    "Filipino",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Haitian",
    "Hungarian",
    "Icelandic",
    "Inariko",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kenyan",
    "Konohagakure",
    "Korean",
    "Lebanese",
    "Malaysian",
    "Mexican",
    "Mongolian",
    "Moroccan",
    "New Zealander (Kiwi)",
    "Nigerian",
    "Norwegian",
    "Pakistani",
    "Palestinian",
    "Panamanian",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Rudania",
    "Russian",
    "Saudi Arabian",
    "Scottish",
    "Serbian",
    "Singaporean",
    "South African",
    "Spanish",
    "Sri Lankan",
    "Sun Empire",
    "Sunagakure",
    "Swedish",
    "Swiss",
    "Syrian",
    "Thai",
    "Trinidadian",
    "Turkish",
    "Ukrainian",
    "Venezuelan",
    "Vhintl",
    "Vietnamese",
    "Welsh"
  ],
  "ethnicity_race": [
    "African",
    "African Descent",
    "Afro-Caribbean",
    "Afro-Latinx",
    "Arab",
    "Armenian",
    "Ashkenazi Jewish",
    "Asian",
    "Asian Descent",
    "Australian Aboriginal",
    "Basque",
    "Bengali",
    "Berber",
    "Bhutanese",
    "Brazilian",
    "Burmese",
    "Cambodian",
    "Caribbean",
    "Caucasian",
    "Caucasian / Pacific Islander",
    "Chicano",
    "Chinese",
    "Creole",
    "Cuban",
    "Dominican",
    "Druze",
    "Eastern European",
    "Egyptian",
    "Ethiopian",
    "Finnish",
    "First Nations",
    "French",
    "German",
    "German Descent",
    "Gerudo / Sheikah",
    "Ghanaian",
    "Greek Descent",
    "Guatemalan",
    "Haitian",
    "Hmong",
    "Hylian",
    "Icelandic",
    "Igbo",
    "Indigenous Australian",
    "Indigenous Canadian",
    "Inuit",
    "Iranian",
    "Iraqi",
    "Israeli",
    "Italian",
    "Italian/Chinese",
    "Japanese",
    "Japanese/British",
    "Jewish",
    "Kazakh",
    "Korean",
    "Kurdish",
    "Latinx",
    "Lebanese",
    "Lithuanian",
    "Lithuanian / Romanian",
    "Lithuanian/Mediterranean/French/Arabian",
    "Lithuanian/Romanian/French/Arabian",
    "Maori",
    "Mayan",
    "Mediterranean",
    "Mediterranean Caucasian Mix",
    "Mediterranean Descent",
    "Meowth",
    "Mestizo",
    "Mexican",
    "Mexican-American",
    "Middle Eastern",
    "Mongolian",
    "Moravian",
    "Nigerian",
    "Pacific Islander",
    "Palestinian",
    "Pashtun",
    "Persian",
    "Polynesian Descent",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Roma",
    "Romanian",
    "Russian",
    "Samoan",
    "Sardinian",
    "Scandinavian",
    "Scanner",
    "Sephardic Jewish",
    "Sicilian",
    "Somali",
    "South Asian",
    "Southeast Asian",
    "Swahili",
    "Syrian",
    "Tibetan",
    "Tlingit",
    "Tongan",
    "Turkish",
    "Uyghur",
    "Venezuelan",
    "Vietnamese",
    "West African",
    "White",
    "Yoruba"
  ],
  "species": [
    "Android",
    "Chimera",
    "Demon",
    "Dragon",
    "Elf",
    "Gijinka",
    "God",
    "Golem",
    "Human",
    "Humanoid Machine",
    "Mosaic",
    "Numen",
    "Saiyan",
    "Shadow",
    "Tabaxi",
    "Werewolf",
    "Yokai",
    "Zora"
  ],
  "eye_color": [
    "Ash",
    "Azure",
    "Black",
    "Black/Silver",
    "Blood",
    "Blue",
    "Brown",
    "Bubblegum",
    "Burnt",
    "Cardinal",
    "Carmine",
    "Coral",
    "Crimson",
    "Deep",
    "Espresso",
    "Gold",
    "Gray",
    "Green",
    "Green/Pink",
    "Ice",
    "Indigo",
    "Lemon",
    "Light",
    "Lilac",
    "Lime",
    "Multi",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "Yellow"
  ],
  "hair_color": [
    "Ash",
    "Baby",
    "Beige",
    "Black",
    "Black/Silver",
    "Blonde",
    "Blue",
    "Brown",
    "Cobalt",
    "Cool",
    "Dark",
    "Dusty",
    "Dusty Rose",
    "Fern",
    "Gray",
    "Green",
    "Jade",
    "Medium",
    "Neutral",
    "Olive",
    "Orange",
    "Pink",
    "Pumpkin",
    "Purple",
    "Silver",
    "Soft",
    "Tawny",
    "White"
  ],
  "skin_tone": [
    "Albino",
    "Amber",
    "Ashen",
    "Black",
    "Bronze",
    "Brown",
    "Caramel",
    "Chestnut",
    "Copper",
    "Dark Brown",
    "Deep Brown",
    "Ebony",
    "Fair",
    "Golden",
    "Honey",
    "Ivory",
    "Light",
    "Light Beige",
    "Mahogany",
    "Medium",
    "Olive",
    "Pale",
    "Porcelain",
    "Rosy",
    "Ruddy",
    "Sable",
    "Sienna",
    "Tan"
  ],
  "occupation": [
    "Abbot/abbess",
    "Abecedarian",
    "Abjurer",
    "Acater",
    "Accoucheur/obstetrician/midwife",
    "Accountant",
    "Accoutrements/coinsmith",
    "Acolyte",
    "Acrobat",
    "Actor",
    "Actuary",
    "Acupuncturist",
    "Administrator",
    "Admiral",
    "Adventurer",
    "Advertising Executive",
    "Aerialist/trapezist",
    "Affeeror",
    "Agister",
    "Air Traffic Controller",
    "Aircraft Engineer",
    "Alchemist",
    "Alderman",
    "Alienist",
    "Almoner",
    "Anaesthetist",
    "Animal Breeder",
    "Animal Collector/monster Collector",
    "Animal/monster Handler",
    "Anthropologist",
    "Antique Dealer",
    "Apothecary",
    "Appraiser",
    "Apprentice",
    "Arborist",
    "Archaeologist",
    "Archbishop",
    "Architect",
    "Archivist",
    "Archmage",
    "Armorer",
    "Aromatherapist",
    "Arranger",
    "Art Critic",
    "Art Dealer",
    "Art Historian",
    "Art Therapist",
    "Artificer",
    "Artist",
    "Arts / Artists / Artistic",
    "Assassin",
    "Assay Master",
    "Assayer",
    "Assembly Line Worker",
    "Assistant",
    "Astrologer",
    "Astronomer",
    "Athlete",
    "Au Pair",
    "Auctioneer",
    "Auditor",
    "Author",
    "Baggage Handler",
    "Bagnio Keeper",
    "Bailiff",
    "Baker",
    "Baler",
    "Bandit",
    "Bank Clerk",
    "Bank Manager",
    "Banker",
    "Bar Staff",
    "Barber",
    "Bard",
    "Barkeep",
    "Barmaid/barboy",
    "Baron/baroness",
    "Barrister",
    "Beekeeper",
    "Beggar/pauper",
    "Billboard Poster",
    "Biochemist",
    "Biologist",
    "Bishop",
    "Blacksmith",
    "Bladesmith",
    "Blood Hunter/monster Hunter",
    "Bloodletter",
    "Boat Builder",
    "Boatman",
    "Bodyguard",
    "Bone Oracle",
    "Bookbinder",
    "Bookkeeper",
    "Bookmaker",
    "Bosun",
    "Botanist",
    "Bottler",
    "Bouncer",
    "Bounty Hunter",
    "Bowyer",
    "Breeder",
    "Brewer",
    "Brewery Worker",
    "Brick Mason / Bricklayer / Mason",
    "Bricklayer",
    "Brickmaker",
    "Broadcaster",
    "Broom Maker",
    "Brothel Keeper",
    "Bug Catcher",
    "Builder",
    "Building Labourer",
    "Burglar",
    "Bus Driver",
    "Business Consultant",
    "Business Owner",
    "Busker/street Musician",
    "Butcher",
    "Butler",
    "Cabbie/wagoner",
    "Cabin Boy/cabin Girl",
    "Cabin Crew",
    "Cabinet Maker",
    "Calligraphist",
    "Camera Operator",
    "Candlemaker",
    "Cantor",
    "Captain",
    "Car Dealer",
    "Car Wash Attendant",
    "Caravaneer",
    "Cardinal",
    "Care Assistant",
    "Career Criminal",
    "Careers Advisor",
    "Caregiver",
    "Caretaker",
    "Carpenter",
    "Carpet Fitter",
    "Carter",
    "Cartographer",
    "Cartoonist",
    "Cartwright",
    "Cashier",
    "Castellan",
    "Casual Worker",
    "Catering Staff",
    "Cavalryman/cavalier",
    "Celebrity",
    "Cemetery Worker",
    "Ceo",
    "Chancellor",
    "Chandler",
    "Chaplain",
    "Charcoal Maker",
    "Charioteer",
    "Charlatan/conman",
    "Chatelaine/majordomo",
    "Chauffeur",
    "Chef",
    "Chef Or Cook",
    "Chemist",
    "Chief",
    "Childcare Worker",
    "Childminder",
    "Childrens Entertainer",
    "Chimney Sweep",
    "Chimney Sweeper",
    "Chiropodist",
    "Chiropractor",
    "Choirmaster",
    "Choreographer",
    "Circus Worker",
    "City Watch",
    "Civil Servant",
    "Clairvoyant",
    "Cleaner",
    "Clergyman",
    "Cleric",
    "Clerical Assistant",
    "Clerk",
    "Clockmaker",
    "Clown",
    "Coastguard",
    "Cobbler",
    "Cockfighter/game Fighter",
    "Collector",
    "Comedian",
    "Commissar",
    "Community Worker",
    "Company Director",
    "Composer",
    "Composer Or Songwriter",
    "Computer Analyst",
    "Computer Engineer",
    "Computer Programmer",
    "Con Artist",
    "Conductor",
    "Confessor",
    "Conjuror",
    "Conservationist",
    "Constable",
    "Construction Worker",
    "Contortionist",
    "Cook",
    "Cooper/hooper",
    "Copyist",
    "Coroner",
    "Costume Designer",
    "Costumer",
    "Councillor",
    "Counsellor",
    "Count/earl/countess",
    "Courier",
    "Courtier",
    "Cowherd",
    "Craftsperson",
    "Crane Driver",
    "Crematorium Worker",
    "Crime",
    "Crime Boss",
    "Crossing Sweeper",
    "Croupier",
    "Crown Prosecutor",
    "Cult Leader",
    "Cultist",
    "Curator",
    "Customs Officer",
    "Cutler",
    "Cutpurse",
    "Dairy Boy/dairymaid",
    "Dancer",
    "Data Processor",
    "Deacon",
    "Dean",
    "Debt Collector",
    "Decorator",
    "Deity",
    "Delivery Driver",
    "Dental Hygienist",
    "Dental Nurse",
    "Dentist",
    "Deserter",
    "Designer",
    "Detective/investigator",
    "Dietician",
    "Diplomat",
    "Director",
    "Disc Jockey",
    "Disgraced Noble",
    "Diver",
    "Diviner",
    "Doctor",
    "Doctor/physician",
    "Domestic Staff",
    "Doorman",
    "Drakologist",
    "Draper",
    "Dressmaker",
    "Driving Instructor",
    "Drug Dealer",
    "Drug Lord",
    "Druid",
    "Drummer/fifer",
    "Drunkard",
    "Duelist",
    "Duke/duchess",
    "Dungeon Delver",
    "Dyer",
    "Economist",
    "Editor",
    "Elder",
    "Electrician",
    "Elementalist",
    "Embalmer",
    "Embroiderer",
    "Emperor/empress",
    "Enchanter/enchantress",
    "Engineer",
    "Engraver",
    "Entomologist",
    "Entrepreneur",
    "Equilibrist",
    "Estate Agent",
    "Events Organiser",
    "Evoker",
    "Executioner",
    "Exile",
    "Exorcist",
    "Explorer",
    "Exterminator",
    "Extortioner",
    "Factory Worker",
    "Fairground Worker",
    "Falconer",
    "Farm Worker",
    "Farmer",
    "Farrier",
    "Fashion Designer",
    "Fbi Agent",
    "Fence",
    "Ferryman",
    "Film Director",
    "Financial Advisor",
    "Firefighter",
    "First Mate",
    "Fisher",
    "Fisherman/woman",
    "Fitness Instructor",
    "Fletcher",
    "Florist",
    "Flower Arranger",
    "Flying Instructor",
    "Folk Hero",
    "Food & Drink Taster",
    "Footballer",
    "Forager",
    "Forester",
    "Forger",
    "Forklift Driver",
    "Foster Parent",
    "Fowler",
    "Fugitive",
    "Fundraiser",
    "Funeral Director",
    "Furniture Artisan",
    "Furrier",
    "Gambler",
    "Gamekeeper",
    "Gang Leader",
    "Gangster",
    "Garden Designer",
    "Gardener",
    "Gardener/landscaper",
    "Gas Fitter",
    "Genealogist",
    "General",
    "General Contractor",
    "Geneticist",
    "Geologist",
    "Gladiator",
    "Glasspainter",
    "Glassworker",
    "Glazier",
    "Glove Maker",
    "God",
    "Goldsmith/silversmith",
    "Gong Farmer",
    "Graphic Designer",
    "Grave Digger",
    "Grave Keeper",
    "Grave Robber/tomb Raider",
    "Gravedigger",
    "Gremlin",
    "Grim Reaper",
    "Grocer",
    "Groom",
    "Groundskeeper",
    "Groundsperson",
    "Guard",
    "Guard/sentinel",
    "Guild Master",
    "Hacker",
    "Hair Stylist",
    "Hairdresser",
    "Handyman",
    "Hatter/milliner",
    "Head Hunter",
    "Healer",
    "Health Visitor",
    "Healthcare Assistant",
    "Hearth Witch/hearth Wizard",
    "Heating Engineer",
    "Helmsman",
    "Herald",
    "Herbalist",
    "Herder",
    "Heretic",
    "Hermit",
    "High Priest/pope",
    "Highwayman",
    "Historian",
    "Home-worker",
    "Homemaker",
    "Homeopath",
    "Horologist",
    "Horse Trainer",
    "Horticulturist",
    "Housekeeper",
    "Housewife/househusband",
    "Hunter",
    "Hypnotherapist",
    "Illuminator",
    "Illusionist",
    "Illustrator",
    "Immigration Officer",
    "Independent Means",
    "Innkeeper",
    "Inquisitor",
    "Inspection Officer",
    "Instrument Maker",
    "Insurance Consultant",
    "Intelligence Officer",
    "Interior Designer",
    "Interpreter",
    "Inventor",
    "It Consultant",
    "Jack Of All Trades",
    "Jack The Ripper",
    "Jailer",
    "Jester",
    "Jeweler",
    "Jeweller",
    "Jewellery Maker",
    "Jockey",
    "Journalist",
    "Judge",
    "Juggler",
    "Kennel Worker",
    "Kidnapper",
    "King/queen",
    "Kitchen Drudge",
    "Knacker",
    "Knight",
    "Laboratory Technician",
    "Labourer",
    "Lady",
    "Lamplighter",
    "Land Surveyor",
    "Landowner",
    "Lap Dancer",
    "Lapidary",
    "Laundry Worker",
    "Lawyer",
    "Lawyer/advocate",
    "Leaflet Distributor",
    "Leatherworker",
    "Lector",
    "Lecturer",
    "Legal Secretary",
    "Librarian",
    "Lieutenant",
    "Lifeguard",
    "Lift Engineer",
    "Lighthouse Keeper",
    "Limner",
    "Linguist",
    "Literary Agent",
    "Loan Shark",
    "Local Govt Worker",
    "Lock Keeper",
    "Locksmith",
    "Longshoreman",
    "Lord",
    "Lorry Driver",
    "Lumberjack",
    "Luthier",
    "Machinist",
    "Mafia Princess",
    "Mage",
    "Magician",
    "Magistrate",
    "Maid",
    "Makeup Artist",
    "Management Consultant",
    "Managing Director",
    "Manicurist",
    "Market Trader",
    "Marketing Director",
    "Marksman/archer",
    "Marquess/marchioness",
    "Marshall",
    "Martial Artist",
    "Mason",
    "Massage Therapist",
    "Master",
    "Mathematician",
    "Mayor",
    "Mechanic",
    "Medic",
    "Medical Student",
    "Medium",
    "Mercenary",
    "Mercer",
    "Merchant",
    "Merchant Navy Personnel",
    "Messenger",
    "Meteorologist",
    "Meter Reader",
    "Midwife",
    "Miller",
    "Miner",
    "Minister",
    "Minstrel",
    "Missionary",
    "Model",
    "Model Maker",
    "Moneychanger",
    "Moneylender",
    "Monk",
    "Mortician",
    "Musician",
    "Nanny",
    "Nanny/nursemaid",
    "Navigator",
    "Necromancer",
    "Ninja",
    "Noble",
    "Noble/aristocrat",
    "Notary",
    "Nun",
    "Nurse",
    "Occupational Therapist",
    "Oceanographer",
    "Oil Rig Crew",
    "Operator",
    "Optician",
    "Optometrist",
    "Oracle",
    "Orator/spokesman",
    "Osteopath",
    "Page",
    "Painter",
    "Paladin",
    "Paramedic",
    "Pardoner",
    "Park Ranger",
    "Park-keeper",
    "Party Planner",
    "Pastry Chef",
    "Pathfinder",
    "Pathologist",
    "Pawnbroker",
    "Peddler",
    "Pest Controller",
    "Pharmacist",
    "Philosopher",
    "Photographer",
    "Physicist",
    "Physiotherapist",
    "Pickpocket",
    "Picture Framer",
    "Pilgrim",
    "Pilot",
    "Pimp/madame",
    "Pirate",
    "Plantation Owner",
    "Plasterer",
    "Playwright",
    "Plumber",
    "Plumer",
    "Poacher",
    "Poet",
    "Poisoner",
    "Police Officer",
    "Politician",
    "Pop Star",
    "Porter",
    "Postal Delivery Worker",
    "Postman Or Postwoman",
    "Potion Master",
    "Potter",
    "Preacher",
    "Priest",
    "Priestess",
    "Prince",
    "Prince/princess",
    "Princess",
    "Print Manager",
    "Printer",
    "Prison Officer",
    "Prisoner",
    "Private Investigator",
    "Private Tutor",
    "Privateer",
    "Probation Officer",
    "Producer",
    "Professor",
    "Prop Maker",
    "Property Developer",
    "Prophet",
    "Prospector",
    "Prostitute",
    "Psychiatrist",
    "Psychologist",
    "Publican",
    "Publisher",
    "Purser",
    "Quarryman/quarrywoman",
    "Quartermaster",
    "Racing Driver",
    "Radio Presenter",
    "Raider/marauder",
    "Ranger",
    "Rebel/political Dissident",
    "Receptionist",
    "Refugee",
    "Refuse Collector",
    "Renderer",
    "Reporter",
    "Researcher",
    "Restorer",
    "Retired",
    "Ringmaster/ringmistress",
    "Ritualist",
    "Road Sweeper",
    "Roadlayer/streetlayer",
    "Roofer",
    "Roofer/thatcher",
    "Room Attendant",
    "Ropemaker",
    "Ropewalker",
    "Roustabout",
    "Royal Guard",
    "Rugmaker",
    "Runaway Slave",
    "Runecaster",
    "Runner",
    "Saddler",
    "Sage",
    "Sailor",
    "Salesperson",
    "Sapper",
    "Scaffolder",
    "Scanner Unit",
    "Scavenger/mudlark/tosher",
    "Scholar/researcher",
    "School Crossing Warden",
    "School Meals Supervisor",
    "Scientist",
    "Scout",
    "Scribe",
    "Sculptor",
    "Sea Captain",
    "Seamstress",
    "Seamstress/tailor",
    "Secretary",
    "Security Guard",
    "Seer/oracle",
    "Senator",
    "Sergeant",
    "Servant",
    "Sexton",
    "Shaman",
    "Shapeshifter",
    "Shepard",
    "Shepherd",
    "Sheriff",
    "Ship Builder",
    "Shipwright",
    "Shoe Repairer",
    "Shoemaker",
    "Shop Assistant",
    "Shop Owner",
    "Shopfitter",
    "Shrine Priestess",
    "Siege Artillerist",
    "Singer",
    "Singer/soprano",
    "Skald",
    "Slave",
    "Slave Driver",
    "Slayer",
    "Smuggler",
    "Soaper",
    "Social Worker",
    "Software Developer",
    "Soldier",
    "Soldier/man",
    "Solicitor",
    "Song Writer",
    "Sorcerer/sorceress",
    "Soul Piper",
    "Soul Reaper",
    "Special Constable",
    "Special Force Soldier",
    "Speculator",
    "Speech Therapist",
    "Spirit Medium",
    "Sports Coach",
    "Sportsperson",
    "Spy",
    "Spymaster",
    "Squatter",
    "Squire",
    "Stablehand",
    "Stage Magician",
    "Stagehand",
    "Stay At Home Mom",
    "Steeplejack",
    "Steward",
    "Stockbroker",
    "Stonemason",
    "Street Entertainer",
    "Student",
    "Stuntman/stuntwoman",
    "Summoner",
    "Surgeon",
    "Surgeon/chirurgeon",
    "Surveyor",
    "Tactician",
    "Tailor",
    "Tailor Or Dressmaker",
    "Talent Scout",
    "Tanner",
    "Tarot Reader",
    "Tattooist",
    "Tax Collector",
    "Tax Inspector",
    "Taxi Driver",
    "Taxidermist",
    "Taxonomist",
    "Teacher",
    "Teaching Assistant",
    "Telephonist",
    "Telesales Person",
    "Television Presenter",
    "Templar",
    "Theater Director",
    "Theologian",
    "Thief",
    "Thresher",
    "Thrift Dealer",
    "Thug",
    "Tinker",
    "Toilet Attendant",
    "Tollkeeper",
    "Toolmaker",
    "Torturer",
    "Tour Guide",
    "Town Crier",
    "Toymaker",
    "Tradesman",
    "Traffic Warden",
    "Train Conductor",
    "Train Driver",
    "Trainer",
    "Translator",
    "Transmuter",
    "Trapper",
    "Travel Agent",
    "Traveler/wanderer/vagabond",
    "Tunner",
    "Tutor",
    "Typist",
    "Undertaker",
    "Unemployed",
    "Urchin",
    "Vendor",
    "Veterinarian",
    "Vintner",
    "Viscount/viscountess",
    "Waiting Staff",
    "Ward",
    "Warden",
    "Warlock",
    "Warmage",
    "Warrior",
    "Watchmaker",
    "Water Bearer",
    "Water Witch",
    "Weaponsmith",
    "Weaver",
    "Welder",
    "Wet Nurse",
    "Wheelwright",
    "Whittler/woodcarver",
    "Window Cleaner",
    "Witch",
    "Witchdoctor",
    "Wizard",
    "Wordsmith",
    "Wrestler",
    "Writer",
    "Zookeeper",
    "Zoologist"
  ],
  "mbti": [
    "ENFJ",
    "ENFP",
    "ENTJ",
    "ENTP",
    "ESFJ",
    "ESFP",
    "ESTJ",
    "ESTP",
    "INFJ",
    "INFP",
    "INTJ",
    "INTP",
    "ISFJ",
    "ISFP",
    "ISTJ",
    "ISTP"
  ],
  "moral": [
    "Chaotic Evil",
    "Chaotic Good",
    "Chaotic Neutral",
    "Lawful Evil",
    "Lawful Good",
    "Lawful Neutral",
    "Neutral Evil",
    "Neutral Good",
    "True Neutral"
  ],
  "positive_traits": [
    "ACCESSIBLE",
    "ACTIVE",
    "ADAPTABLE",
    "ADMIRABLE",
    "ADVENTUROUS",
    "AGREEABLE",
    "ALERT",
    "ALLOCENTRIC",
    "ATTRACTIVE",
    "BALANCED",
    "BENEVOLENT",
    "BRILLIANT",
    "CALM",
    "CAPABLE",
    "CAPTIVATING",
    "CARING",
    "CHALLENGING",
    "CHARISMATIC",
    "CHARMING",
    "CHEERFUL",
    "CLEAN",
    "CLEAR-HEADED",
    "CLEVER",
    "COLORFUL",
    "COMPANIONLY",
    "COMPASSIONATE",
    "CONCILIATORY",
    "CONFIDENT",
    "CONSCIENTIOUS",
    "CONSIDERATE",
    "CONSTANT",
    "CONTEMPLATIVE",
    "COOPERATIVE",
    "COURAGEOUS",
    "COURTEOUS",
    "CREATIVE",
    "CULTURED",
    "CURIOUS",
    "DARING",
    "DEBONAIR",
    "DECENT",
    "DECISIVE",
    "DEDICATED",
    "DEEP",
    "DIGNIFIED",
    "DIRECTED",
    "DISCIPLINED",
    "DISCREET",
    "DRAMATIC",
    "DUTIFUL",
    "DYNAMIC",
    "EARNEST",
    "EBULLIENT",
    "EDUCATED",
    "EFFICIENT",
    "ELEGANT",
    "ELOQUENT",
    "EMPATHETIC",
    "ENERGETIC",
    "ENTHUSIASTIC",
    "ESTHETIC",
    "EXCITING",
    "EXTRAORDINARY",
    "FAIR",
    "FAITHFUL",
    "FARSIGHTED",
    "FEARLESS",
    "FELICIFIC",
    "FIRM",
    "FLEXIBLE",
    "FOCUSED",
    "FORCEFUL",
    "FORGIVING",
    "FORTHRIGHT",
    "FREETHINKING",
    "FRIENDLY",
    "FUN-LOVING",
    "GALLANT",
    "GENEROUS",
    "GENTLE",
    "GENUINE",
    "GOOD-NATURED",
    "GRACIOUS",
    "HARDWORKING",
    "HEALTHY",
    "HEARTY",
    "HELPFUL",
    "HEROIC",
    "HIGH-MINDED",
    "HONEST",
    "HONORABLE",
    "HUMBLE",
    "HUMOROUS",
    "IDEALISTIC",
    "IMAGINATIVE",
    "IMPRESSIVE",
    "INCISIVE",
    "INCORRUPTIBLE",
    "INDEPENDENT",
    "INDIVIDUALISTIC",
    "INNOVATIVE",
    "INOFFENSIVE",
    "INSIGHTFUL",
    "INSOUCIANT",
    "INTELLIGENT",
    "INTUITIVE",
    "INVULNERABLE",
    "KIND",
    "KNOWLEDGE",
    "LEADERLY",
    "LEISURELY",
    "LIBERAL",
    "LOGICAL",
    "LOVABLE",
    "LOYAL",
    "LYRICAL",
    "MAGNANIMOUS",
    "MANY-SIDED",
    "MASCULINE (MANLY)",
    "MATURE",
    "METHODICAL",
    "METICULOUS",
    "MODERATE",
    "MODEST",
    "MULTI-LEVELED",
    "NEAT",
    "NON AUTHORITARIAN",
    "OBJECTIVE",
    "OBSERVANT",
    "OPEN",
    "OPTIMISTIC",
    "ORDERLY",
    "ORGANIZED",
    "ORIGINAL",
    "PAINSTAKING",
    "PASSIONATE",
    "PATIENT",
    "PATRIOTIC",
    "PEACEFUL",
    "PERCEPTIVE",
    "PERFECTIONIST",
    "PERSONABLE",
    "PERSUASIVE",
    "PLANFUL",
    "PLAYFUL",
    "POLISHED",
    "POPULAR",
    "PRACTICAL",
    "PRECISE",
    "PRINCIPLED",
    "PROFOUND",
    "PROTEAN",
    "PROTECTIVE",
    "PROVIDENTIAL",
    "PRUDENT",
    "PUNCTUAL",
    "PURPOSEFUL",
    "RATIONAL",
    "REALISTIC",
    "REFLECTIVE",
    "RELAXED",
    "RELIABLE",
    "RESILIENT",
    "RESOURCEFUL",
    "RESPECTFUL",
    "RESPONSIBLE",
    "RESPONSIVE",
    "REVERENTIAL",
    "ROMANTIC",
    "RUSTIC",
    "SAGE",
    "SANE",
    "SCHOLARLY",
    "SCRUPULOUS",
    "SECURE",
    "SELF-CRITICAL",
    "SELF-DEFACING",
    "SELF-DENYING",
    "SELF-RELIANT",
    "SELF-SUFFICIENT",
    "SELFLESS",
    "SENSITIVE",
    "SENTIMENTAL",
    "SERAPHIC",
    "SERIOUS",
    "SEXY",
    "SHARING",
    "SHREWD",
    "SIMPLE",
    "SKILLFUL",
    "SOBER",
    "SOCIABLE",
    "SOLID",
    "SOPHISTICATED",
    "SPONTANEOUS",
    "SPORTING",
    "STABLE",
    "STEADFAST",
    "STEADY",
    "STOIC",
    "STRONG",
    "STUDIOUS",
    "SUAVE",
    "SUBTLE",
    "SWEET",
    "SYMPATHETIC",
    "SYSTEMATIC",
    "TASTEFUL",
    "TEACHERLY",
    "THOROUGH",
    "TIDY",
    "TOLERANT",
    "TRACTABLE",
    "TRUSTING",
    "UNCOMPLAINING",
    "UNDERSTANDING",
    "UNDOGMATIC",
    "UNFOOLABLE",
    "UPRIGHT",
    "URBANE",
    "VENTURESOME",
    "VIVACIOUS",
    "WARM",
    "WELL-BRED",
    "WELL-READ",
    "WELL-ROUNDED",
    "WINNING",
    "WISE",
    "WITTY",
    "YOUTHFUL"
  ],
  "neutral_traits": [
    "ABSENTMINDED",
    "AGGRESSIVE",
    "AMBITIOUS",
    "AMUSING",
    "ARTFUL",
    "ASCETIC",
    "AUTHORITARIAN",
    "BIG-THINKING",
    "CHUMMY",
    "CIRCUMSPECT",
    "COMPETITIVE",
    "COMPLEX",
    "CONFIDENTIAL",
    "CONSERVATIVE",
    "CONTRADICTORY",
    "CRISP",
    "CUTE",
    "DECEPTIVE",
    "DETERMINED",
    "DOMINATING",
    "DREAMY",
    "DRIVING",
    "DROLL",
    "DRY",
    "EARTHY",
    "EFFEMINATE",
    "EMOTIONAL",
    "ENIGMATIC",
    "EXPERIMENTAL",
    "FAMILIAL",
    "FOLKSY",
    "FORMAL",
    "FREEWHEELING",
    "FRUGAL",
    "GLAMOROUS",
    "GUILELESS",
    "HIGH-SPIRITED",
    "HURIED",
    "HYPNOTIC",
    "ICONOCLASTIC",
    "IDIOSYNCRATIC",
    "IMPASSIVE",
    "IMPERSONAL",
    "IMPRESSIONABLE",
    "INTENSE",
    "INVISIBLE",
    "IRRELIGIOUS",
    "IRREVERENT",
    "MATERNAL",
    "MELLOW",
    "MODERN",
    "MORALISTIC",
    "MYSTICAL",
    "NEUTRAL",
    "NONCOMMITTAL",
    "NONCOMPETITIVE",
    "OBEDIENT",
    "OLD-FASHIONED",
    "ORDINARY",
    "OUTSPOKEN",
    "PATERNALISTIC",
    "PHYSICAL",
    "PLACID",
    "POLITICAL",
    "PREDICTABLE",
    "PREOCCUPIED",
    "PRIVATE",
    "PROGRESSIVE",
    "PROUD",
    "PURE",
    "QUESTIONING",
    "QUIET",
    "RELIGIOUS",
    "RESERVED",
    "RESTRAINED",
    "RETIRING",
    "SARCASTIC",
    "SELF-CONSCIOUS",
    "SENSUAL",
    "SKEPTICAL",
    "SMOOTH",
    "SOFT",
    "SOLEMN",
    "SOLITARY",
    "STERN",
    "STOLID",
    "STRICT",
    "STUBBORN",
    "STYLISH",
    "SUBJECTIVE",
    "SURPRISING",
    "TOUGH",
    "UNAGGRESSIVE",
    "UNAMBITIOUS",
    "UNCEREMONIOUS",
    "UNCHANGING",
    "UNDEMANDING",
    "UNFATHOMABLE",
    "UNHURRIED",
    "UNINHIBITED",
    "UNPATRIOTIC",
    "UNPREDICTABLE",
    "UNRELIGIOUS",
    "UNSENTIMENTAL",
    "WHIMSICAL"
  ],
  "negative_traits": [
    "ABRASIVE",
    "ABRUPT",
    "AGONIZING",
    "AIMLESS",
    "AIRY",
    "ALOOF",
    "AMORAL",
    "ANGRY",
    "ASOCIAL",
    "ASSERTIVE",
    "ASTIGMATIC",
    "BARBARIC",
    "BEWILDERED",
    "BIZARRE",
    "BLAND",
    "BLUNT",
    "BOISTEROUS",
    "BRITTLE",
    "BRUTAL",
    "CALCULATING",
    "CALLOUS",
    "CANTANKEROUS",
    "CARELESS",
    "CAUTIOUS",
    "CHARMLESS",
    "CHILDISH",
    "CLUMSY",
    "COARSE",
    "COLD",
    "COLORLESS",
    "COMPLACENT",
    "COMPLAINTIVE",
    "COMPULSIVE",
    "CONCEITED",
    "CONDEMNATORY",
    "CONFORMIST",
    "CONFUSED",
    "CONTEMPTIBLE",
    "CONVENTIONAL",
    "COWARDLY",
    "CRAFTY",
    "CRASS",
    "CRAZY",
    "CRIMINAL",
    "CRITICAL",
    "CRUDE",
    "CRUEL",
    "CYNICAL",
    "DECADENT",
    "DECEITFUL",
    "DELICATE",
    "DEMANDING",
    "DEPENDENT",
    "DESPERATE",
    "DESTRUCTIVE",
    "DEVIOUS",
    "DIFFICULT",
    "DIRTY",
    "DISCONCERTING",
    "DISCONTENTED",
    "DISCOURAGING",
    "DISCOURTEOUS",
    "DISHONEST",
    "DISLOYAL",
    "DISOBEDIENT",
    "DISORDERLY",
    "DISORGANIZED",
    "DISPUTATIOUS",
    "DISRESPECTFUL",
    "DISRUPTIVE",
    "DISSOLUTE",
    "DISSONANT",
    "DISTRACTIBLE",
    "DISTURBING",
    "DOGMATIC",
    "DOMINEERING",
    "DULL",
    "EASILY DISCOURAGED",
    "EGOCENTRIC",
    "ENERVATED",
    "ENVIOUS",
    "ERRATIC",
    "ESCAPIST",
    "EXCITABLE",
    "EXPEDIENT",
    "EXTRAVAGANT",
    "EXTREME",
    "FAITHLESS",
    "FANATICAL",
    "FANCIFUL",
    "FATALISTIC",
    "FAWNING",
    "FEARFUL",
    "FICKLE",
    "FIERY",
    "FIXED",
    "FLAMBOYANT",
    "FOOLISH",
    "FORGETFUL",
    "FRAUDULENT",
    "FRIGHTENING",
    "FRIVOLOUS",
    "GLOOMY",
    "GRACELESS",
    "GRAND",
    "GREEDY",
    "GRIM",
    "GULLIBLE",
    "HATEFUL",
    "HAUGHTY",
    "HEDONISTIC",
    "HESITANT",
    "HIDEBOUND",
    "HIGH-HANDED",
    "HOSTILE",
    "IGNORANT",
    "IMITATIVE",
    "IMPATIENT",
    "IMPRACTICAL",
    "IMPRUDENT",
    "IMPULSIVE",
    "INCONSIDERATE",
    "INCURIOUS",
    "INDECISIVE",
    "INDULGENT",
    "INERT",
    "INHIBITED",
    "INSECURE",
    "INSENSITIVE",
    "INSINCERE",
    "INSULTING",
    "INTOLERANT",
    "IRASCIBLE",
    "IRRATIONAL",
    "IRRESPONSIBLE",
    "IRRITABLE",
    "LAZY",
    "LIBIDINOUS",
    "LOQUACIOUS",
    "MALICIOUS",
    "MANIPULATIVE",
    "MANNERED",
    "MANNERLESS",
    "MAWKISH",
    "MEALY MOUTHED",
    "MECHANICAL",
    "MEDDLESOME",
    "MELANCHOLIC",
    "MERETRICIOUS",
    "MESSY",
    "MISERABLE",
    "MISERLY",
    "MISGUIDED",
    "MISTAKEN",
    "MONEY-MINDED",
    "MONSTROUS",
    "MOODY",
    "MORBID",
    "MUDDLE-HEADED",
    "NAIVE",
    "NARCISSISTIC",
    "NARROW",
    "NARROW-MINDED",
    "NATTY",
    "NEGATIVISTIC",
    "NEGLECTFUL",
    "NEUROTIC",
    "NIHILISTIC",
    "OBNOXIOUS",
    "OBSESSIVE",
    "OBVIOUS",
    "ODD",
    "OFFHAND",
    "ONE-DIMENSIONAL",
    "ONE-SIDED",
    "OPINIONATED",
    "OPPORTUNISTIC",
    "OPPRESSED",
    "OUTRAGEOUS",
    "OVER IMAGINATIVE",
    "PARANOID",
    "PASSIVE",
    "PEDANTIC",
    "PERVERSE",
    "PETTY",
    "PHARISAICAL",
    "PHLEGMATIC",
    "PLODDING",
    "POMPOUS",
    "POSSESSIVE",
    "POWER-HUNGRY",
    "PREDATORY",
    "PREJUDICED",
    "PRESUMPTUOUS",
    "PRETENTIOUS",
    "PRIM",
    "PROCRASTINATING",
    "PROFLIGATE",
    "PROVOCATIVE",
    "PUGNACIOUS",
    "PURITANICAL",
    "QUIRKY",
    "REACTIONARY",
    "REACTIVE",
    "REGIMENTAL",
    "REGRETFUL",
    "REPENTANT",
    "REPRESSED",
    "RESENTFUL",
    "RIDICULOUS",
    "RIGID",
    "RITUALISTIC",
    "ROWDY",
    "RUINED",
    "SADISTIC",
    "SANCTIMONIOUS",
    "SCHEMING",
    "SCORNFUL",
    "SECRETIVE",
    "SEDENTARY",
    "SELF-INDULGENT",
    "SELFISH",
    "SHALLOW",
    "SHORTSIGHTED",
    "SHY",
    "SILLY",
    "SINGLE-MINDED",
    "SLOPPY",
    "SLOW",
    "SLY",
    "SMALL-THINKING",
    "SOFT HEADED",
    "SORDID",
    "STEELY",
    "STIFF",
    "STRONG-WILLED",
    "STUPID",
    "SUBMISSIVE",
    "SUPERFICIAL",
    "SUPERSTITIOUS",
    "SUSPICIOUS",
    "TACTLESS",
    "TASTELESS",
    "TENSE",
    "THIEVISH",
    "THOUGHTLESS",
    "TIMID",
    "TRANSPARENT",
    "TREACHEROUS",
    "TRENDY",
    "TROUBLESOME",
    "UNAPPRECIATIVE",
    "UNCARING",
    "UNCHARITABLE",
    "UNCONVINCING",
    "UNCOOPERATIVE",
    "UNCREATIVE",
    "UNCRITICAL",
    "UNCTUOUS",
    "UNDISCIPLINED",
    "UNFRIENDLY",
    "UNGRATEFUL",
    "UNHEALTHY",
    "UNIMAGINATIVE",
    "UNIMPRESSIVE",
    "UNLOVABLE",
    "UNPOLISHED",
    "UNPREDICTABLE",
    "UNPRINCIPLED",
    "UNREALISTIC",
    "UNREFLECTIVE",
    "UNRELIABLE",
    "UNRESTRAINED",
    "UNSELF-CRITICAL",
    "UNSTABLE",
    "VACUOUS",
    "VAGUE",
    "VENAL",
    "VENOMOUS",
    "VINDICTIVE",
    "VULNERABLE",
    "WEAK",
    "WEAK-WILLED",
    "WELL-MEANING",
    "WILLFUL",
    "WISHFUL",
    "ZANY"
  ],
  "gender": [
    "Agender",
    "Androgynous",
    "Bigender",
    "Cisgender",
    "Demiboy",
    "Demigirl",
    "Genderfluid",
    "Genderqueer",
    "Intersex",
    "Neutrois",
    "Non-binary",
    "Pangender",
    "Third Gender",
    "Transgender",
    "Two-spirit"
  ]
};

// Individual exports for convenience
export const pronounsOptions: string[] = ["He/Him","He/They","She/He","She/He/They","She/Her","She/They","They/He","They/She","They/Them"];
export const gender_identityOptions: string[] = ["Agender","Androgynous","Bigender","Cisgender","Demiboy","Demigirl","Genderfluid","Genderqueer","Intersex","Neutrois","Non-binary","Pangender","Third Gender","Transgender","Two-spirit"];
export const romanticOptions: string[] = ["Biromantic","Demiromantic","Greyromantic","Heteroromantic","Homoromantic","Lithromantic","Monogamy","Panromantic"];
export const sexualOptions: string[] = ["Androsexual","Asexual","Autosexual","Bisexual","Demisexual","Greysexual","Gynosexual","Heterosexual","Homosexual","Lithsexual","Pansexual","Polysexual","Queer","Sapiosexual","Skoliosexual"];
export const relationship_typeOptions: string[] = ["Aromantic","Asexual","Casual Relationship","Co-parenting","Dom/sub (d/s)","Friends With Benefits","Group Marriage","Long-distance Relationship (ldr)","Monogamy","Open Relationship","Platonic Relationship","Polyamory","Polyandry","Polygamy","Polygyny","Primary/secondary","Quad","Queerplatonic Relationship (qpr)","Relationship Anarchy","Swinging","Triad"];
export const sexOptions: string[] = ["Androgyne","Female","Intersex","Male"];
export const accentOptions: string[] = ["Boston","Brazilian Portuguese","Californian","Canadian","Caribbean","Chicago","Chicano English (Mexican-American)","Chinese","Dutch","German","Greek","Hawaiian Pidgin","Indian","Jamaican","Japanese","Korean","Midwestern","Minnesotan","New Orleans (cajun)","New York","New Zealand","Pacific Northwest","Philadelphia","Polish","Russian","South African","Southern Appalachian","Southern Californian (SoCal)","Texan","Turkish","Valley (California)","Welsh"];
export const nationalityOptions: string[] = ["Afghan","American","Argentine","Australian","Austrian","Bangladeshi","Belgian","Bosnian","Brazilian","British","Bulgarian","Canadian","Chilean","Chinese","Colombian","Costa Rican","Croatian","Cuban","Czech","Danish","Dominican","Dutch","Egyptian","Emirati","Ethiopian","Filipino","Finnish","French","German","Greek","Haitian","Hungarian","Icelandic","Inariko","Indian","Indonesian","Iranian","Iraqi","Irish","Israeli","Italian","Jamaican","Japanese","Jordanian","Kenyan","Konohagakure","Korean","Lebanese","Malaysian","Mexican","Mongolian","Moroccan","New Zealander (Kiwi)","Nigerian","Norwegian","Pakistani","Palestinian","Panamanian","Peruvian","Polish","Portuguese","Romanian","Rudania","Russian","Saudi Arabian","Scottish","Serbian","Singaporean","South African","Spanish","Sri Lankan","Sun Empire","Sunagakure","Swedish","Swiss","Syrian","Thai","Trinidadian","Turkish","Ukrainian","Venezuelan","Vhintl","Vietnamese","Welsh"];
export const ethnicity_raceOptions: string[] = ["African","African Descent","Afro-Caribbean","Afro-Latinx","Arab","Armenian","Ashkenazi Jewish","Asian","Asian Descent","Australian Aboriginal","Basque","Bengali","Berber","Bhutanese","Brazilian","Burmese","Cambodian","Caribbean","Caucasian","Caucasian / Pacific Islander","Chicano","Chinese","Creole","Cuban","Dominican","Druze","Eastern European","Egyptian","Ethiopian","Finnish","First Nations","French","German","German Descent","Gerudo / Sheikah","Ghanaian","Greek Descent","Guatemalan","Haitian","Hmong","Hylian","Icelandic","Igbo","Indigenous Australian","Indigenous Canadian","Inuit","Iranian","Iraqi","Israeli","Italian","Italian/Chinese","Japanese","Japanese/British","Jewish","Kazakh","Korean","Kurdish","Latinx","Lebanese","Lithuanian","Lithuanian / Romanian","Lithuanian/Mediterranean/French/Arabian","Lithuanian/Romanian/French/Arabian","Maori","Mayan","Mediterranean","Mediterranean Caucasian Mix","Mediterranean Descent","Meowth","Mestizo","Mexican","Mexican-American","Middle Eastern","Mongolian","Moravian","Nigerian","Pacific Islander","Palestinian","Pashtun","Persian","Polynesian Descent","Portuguese","Punjabi","Quechua","Roma","Romanian","Russian","Samoan","Sardinian","Scandinavian","Scanner","Sephardic Jewish","Sicilian","Somali","South Asian","Southeast Asian","Swahili","Syrian","Tibetan","Tlingit","Tongan","Turkish","Uyghur","Venezuelan","Vietnamese","West African","White","Yoruba"];
export const speciesOptions: string[] = ["Android","Chimera","Demon","Dragon","Elf","Gijinka","God","Golem","Human","Humanoid Machine","Mosaic","Numen","Saiyan","Shadow","Tabaxi","Werewolf","Yokai","Zora"];
export const eye_colorOptions: string[] = ["Ash","Azure","Black","Black/Silver","Blood","Blue","Brown","Bubblegum","Burnt","Cardinal","Carmine","Coral","Crimson","Deep","Espresso","Gold","Gray","Green","Green/Pink","Ice","Indigo","Lemon","Light","Lilac","Lime","Multi","Orange","Pink","Purple","Red","Yellow"];
export const hair_colorOptions: string[] = ["Ash","Baby","Beige","Black","Black/Silver","Blonde","Blue","Brown","Cobalt","Cool","Dark","Dusty","Dusty Rose","Fern","Gray","Green","Jade","Medium","Neutral","Olive","Orange","Pink","Pumpkin","Purple","Silver","Soft","Tawny","White"];
export const skin_toneOptions: string[] = ["Albino","Amber","Ashen","Black","Bronze","Brown","Caramel","Chestnut","Copper","Dark Brown","Deep Brown","Ebony","Fair","Golden","Honey","Ivory","Light","Light Beige","Mahogany","Medium","Olive","Pale","Porcelain","Rosy","Ruddy","Sable","Sienna","Tan"];
export const occupationOptions: string[] = ["Abbot/abbess","Abecedarian","Abjurer","Acater","Accoucheur/obstetrician/midwife","Accountant","Accoutrements/coinsmith","Acolyte","Acrobat","Actor","Actuary","Acupuncturist","Administrator","Admiral","Adventurer","Advertising Executive","Aerialist/trapezist","Affeeror","Agister","Air Traffic Controller","Aircraft Engineer","Alchemist","Alderman","Alienist","Almoner","Anaesthetist","Animal Breeder","Animal Collector/monster Collector","Animal/monster Handler","Anthropologist","Antique Dealer","Apothecary","Appraiser","Apprentice","Arborist","Archaeologist","Archbishop","Architect","Archivist","Archmage","Armorer","Aromatherapist","Arranger","Art Critic","Art Dealer","Art Historian","Art Therapist","Artificer","Artist","Arts / Artists / Artistic","Assassin","Assay Master","Assayer","Assembly Line Worker","Assistant","Astrologer","Astronomer","Athlete","Au Pair","Auctioneer","Auditor","Author","Baggage Handler","Bagnio Keeper","Bailiff","Baker","Baler","Bandit","Bank Clerk","Bank Manager","Banker","Bar Staff","Barber","Bard","Barkeep","Barmaid/barboy","Baron/baroness","Barrister","Beekeeper","Beggar/pauper","Billboard Poster","Biochemist","Biologist","Bishop","Blacksmith","Bladesmith","Blood Hunter/monster Hunter","Bloodletter","Boat Builder","Boatman","Bodyguard","Bone Oracle","Bookbinder","Bookkeeper","Bookmaker","Bosun","Botanist","Bottler","Bouncer","Bounty Hunter","Bowyer","Breeder","Brewer","Brewery Worker","Brick Mason / Bricklayer / Mason","Bricklayer","Brickmaker","Broadcaster","Broom Maker","Brothel Keeper","Bug Catcher","Builder","Building Labourer","Burglar","Bus Driver","Business Consultant","Business Owner","Busker/street Musician","Butcher","Butler","Cabbie/wagoner","Cabin Boy/cabin Girl","Cabin Crew","Cabinet Maker","Calligraphist","Camera Operator","Candlemaker","Cantor","Captain","Car Dealer","Car Wash Attendant","Caravaneer","Cardinal","Care Assistant","Career Criminal","Careers Advisor","Caregiver","Caretaker","Carpenter","Carpet Fitter","Carter","Cartographer","Cartoonist","Cartwright","Cashier","Castellan","Casual Worker","Catering Staff","Cavalryman/cavalier","Celebrity","Cemetery Worker","Ceo","Chancellor","Chandler","Chaplain","Charcoal Maker","Charioteer","Charlatan/conman","Chatelaine/majordomo","Chauffeur","Chef","Chef Or Cook","Chemist","Chief","Childcare Worker","Childminder","Childrens Entertainer","Chimney Sweep","Chimney Sweeper","Chiropodist","Chiropractor","Choirmaster","Choreographer","Circus Worker","City Watch","Civil Servant","Clairvoyant","Cleaner","Clergyman","Cleric","Clerical Assistant","Clerk","Clockmaker","Clown","Coastguard","Cobbler","Cockfighter/game Fighter","Collector","Comedian","Commissar","Community Worker","Company Director","Composer","Composer Or Songwriter","Computer Analyst","Computer Engineer","Computer Programmer","Con Artist","Conductor","Confessor","Conjuror","Conservationist","Constable","Construction Worker","Contortionist","Cook","Cooper/hooper","Copyist","Coroner","Costume Designer","Costumer","Councillor","Counsellor","Count/earl/countess","Courier","Courtier","Cowherd","Craftsperson","Crane Driver","Crematorium Worker","Crime","Crime Boss","Crossing Sweeper","Croupier","Crown Prosecutor","Cult Leader","Cultist","Curator","Customs Officer","Cutler","Cutpurse","Dairy Boy/dairymaid","Dancer","Data Processor","Deacon","Dean","Debt Collector","Decorator","Deity","Delivery Driver","Dental Hygienist","Dental Nurse","Dentist","Deserter","Designer","Detective/investigator","Dietician","Diplomat","Director","Disc Jockey","Disgraced Noble","Diver","Diviner","Doctor","Doctor/physician","Domestic Staff","Doorman","Drakologist","Draper","Dressmaker","Driving Instructor","Drug Dealer","Drug Lord","Druid","Drummer/fifer","Drunkard","Duelist","Duke/duchess","Dungeon Delver","Dyer","Economist","Editor","Elder","Electrician","Elementalist","Embalmer","Embroiderer","Emperor/empress","Enchanter/enchantress","Engineer","Engraver","Entomologist","Entrepreneur","Equilibrist","Estate Agent","Events Organiser","Evoker","Executioner","Exile","Exorcist","Explorer","Exterminator","Extortioner","Factory Worker","Fairground Worker","Falconer","Farm Worker","Farmer","Farrier","Fashion Designer","Fbi Agent","Fence","Ferryman","Film Director","Financial Advisor","Firefighter","First Mate","Fisher","Fisherman/woman","Fitness Instructor","Fletcher","Florist","Flower Arranger","Flying Instructor","Folk Hero","Food & Drink Taster","Footballer","Forager","Forester","Forger","Forklift Driver","Foster Parent","Fowler","Fugitive","Fundraiser","Funeral Director","Furniture Artisan","Furrier","Gambler","Gamekeeper","Gang Leader","Gangster","Garden Designer","Gardener","Gardener/landscaper","Gas Fitter","Genealogist","General","General Contractor","Geneticist","Geologist","Gladiator","Glasspainter","Glassworker","Glazier","Glove Maker","God","Goldsmith/silversmith","Gong Farmer","Graphic Designer","Grave Digger","Grave Keeper","Grave Robber/tomb Raider","Gravedigger","Gremlin","Grim Reaper","Grocer","Groom","Groundskeeper","Groundsperson","Guard","Guard/sentinel","Guild Master","Hacker","Hair Stylist","Hairdresser","Handyman","Hatter/milliner","Head Hunter","Healer","Health Visitor","Healthcare Assistant","Hearth Witch/hearth Wizard","Heating Engineer","Helmsman","Herald","Herbalist","Herder","Heretic","Hermit","High Priest/pope","Highwayman","Historian","Home-worker","Homemaker","Homeopath","Horologist","Horse Trainer","Horticulturist","Housekeeper","Housewife/househusband","Hunter","Hypnotherapist","Illuminator","Illusionist","Illustrator","Immigration Officer","Independent Means","Innkeeper","Inquisitor","Inspection Officer","Instrument Maker","Insurance Consultant","Intelligence Officer","Interior Designer","Interpreter","Inventor","It Consultant","Jack Of All Trades","Jack The Ripper","Jailer","Jester","Jeweler","Jeweller","Jewellery Maker","Jockey","Journalist","Judge","Juggler","Kennel Worker","Kidnapper","King/queen","Kitchen Drudge","Knacker","Knight","Laboratory Technician","Labourer","Lady","Lamplighter","Land Surveyor","Landowner","Lap Dancer","Lapidary","Laundry Worker","Lawyer","Lawyer/advocate","Leaflet Distributor","Leatherworker","Lector","Lecturer","Legal Secretary","Librarian","Lieutenant","Lifeguard","Lift Engineer","Lighthouse Keeper","Limner","Linguist","Literary Agent","Loan Shark","Local Govt Worker","Lock Keeper","Locksmith","Longshoreman","Lord","Lorry Driver","Lumberjack","Luthier","Machinist","Mafia Princess","Mage","Magician","Magistrate","Maid","Makeup Artist","Management Consultant","Managing Director","Manicurist","Market Trader","Marketing Director","Marksman/archer","Marquess/marchioness","Marshall","Martial Artist","Mason","Massage Therapist","Master","Mathematician","Mayor","Mechanic","Medic","Medical Student","Medium","Mercenary","Mercer","Merchant","Merchant Navy Personnel","Messenger","Meteorologist","Meter Reader","Midwife","Miller","Miner","Minister","Minstrel","Missionary","Model","Model Maker","Moneychanger","Moneylender","Monk","Mortician","Musician","Nanny","Nanny/nursemaid","Navigator","Necromancer","Ninja","Noble","Noble/aristocrat","Notary","Nun","Nurse","Occupational Therapist","Oceanographer","Oil Rig Crew","Operator","Optician","Optometrist","Oracle","Orator/spokesman","Osteopath","Page","Painter","Paladin","Paramedic","Pardoner","Park Ranger","Park-keeper","Party Planner","Pastry Chef","Pathfinder","Pathologist","Pawnbroker","Peddler","Pest Controller","Pharmacist","Philosopher","Photographer","Physicist","Physiotherapist","Pickpocket","Picture Framer","Pilgrim","Pilot","Pimp/madame","Pirate","Plantation Owner","Plasterer","Playwright","Plumber","Plumer","Poacher","Poet","Poisoner","Police Officer","Politician","Pop Star","Porter","Postal Delivery Worker","Postman Or Postwoman","Potion Master","Potter","Preacher","Priest","Priestess","Prince","Prince/princess","Princess","Print Manager","Printer","Prison Officer","Prisoner","Private Investigator","Private Tutor","Privateer","Probation Officer","Producer","Professor","Prop Maker","Property Developer","Prophet","Prospector","Prostitute","Psychiatrist","Psychologist","Publican","Publisher","Purser","Quarryman/quarrywoman","Quartermaster","Racing Driver","Radio Presenter","Raider/marauder","Ranger","Rebel/political Dissident","Receptionist","Refugee","Refuse Collector","Renderer","Reporter","Researcher","Restorer","Retired","Ringmaster/ringmistress","Ritualist","Road Sweeper","Roadlayer/streetlayer","Roofer","Roofer/thatcher","Room Attendant","Ropemaker","Ropewalker","Roustabout","Royal Guard","Rugmaker","Runaway Slave","Runecaster","Runner","Saddler","Sage","Sailor","Salesperson","Sapper","Scaffolder","Scanner Unit","Scavenger/mudlark/tosher","Scholar/researcher","School Crossing Warden","School Meals Supervisor","Scientist","Scout","Scribe","Sculptor","Sea Captain","Seamstress","Seamstress/tailor","Secretary","Security Guard","Seer/oracle","Senator","Sergeant","Servant","Sexton","Shaman","Shapeshifter","Shepard","Shepherd","Sheriff","Ship Builder","Shipwright","Shoe Repairer","Shoemaker","Shop Assistant","Shop Owner","Shopfitter","Shrine Priestess","Siege Artillerist","Singer","Singer/soprano","Skald","Slave","Slave Driver","Slayer","Smuggler","Soaper","Social Worker","Software Developer","Soldier","Soldier/man","Solicitor","Song Writer","Sorcerer/sorceress","Soul Piper","Soul Reaper","Special Constable","Special Force Soldier","Speculator","Speech Therapist","Spirit Medium","Sports Coach","Sportsperson","Spy","Spymaster","Squatter","Squire","Stablehand","Stage Magician","Stagehand","Stay At Home Mom","Steeplejack","Steward","Stockbroker","Stonemason","Street Entertainer","Student","Stuntman/stuntwoman","Summoner","Surgeon","Surgeon/chirurgeon","Surveyor","Tactician","Tailor","Tailor Or Dressmaker","Talent Scout","Tanner","Tarot Reader","Tattooist","Tax Collector","Tax Inspector","Taxi Driver","Taxidermist","Taxonomist","Teacher","Teaching Assistant","Telephonist","Telesales Person","Television Presenter","Templar","Theater Director","Theologian","Thief","Thresher","Thrift Dealer","Thug","Tinker","Toilet Attendant","Tollkeeper","Toolmaker","Torturer","Tour Guide","Town Crier","Toymaker","Tradesman","Traffic Warden","Train Conductor","Train Driver","Trainer","Translator","Transmuter","Trapper","Travel Agent","Traveler/wanderer/vagabond","Tunner","Tutor","Typist","Undertaker","Unemployed","Urchin","Vendor","Veterinarian","Vintner","Viscount/viscountess","Waiting Staff","Ward","Warden","Warlock","Warmage","Warrior","Watchmaker","Water Bearer","Water Witch","Weaponsmith","Weaver","Welder","Wet Nurse","Wheelwright","Whittler/woodcarver","Window Cleaner","Witch","Witchdoctor","Wizard","Wordsmith","Wrestler","Writer","Zookeeper","Zoologist"];
export const mbtiOptions: string[] = ["ENFJ","ENFP","ENTJ","ENTP","ESFJ","ESFP","ESTJ","ESTP","INFJ","INFP","INTJ","INTP","ISFJ","ISFP","ISTJ","ISTP"];
export const moralOptions: string[] = ["Chaotic Evil","Chaotic Good","Chaotic Neutral","Lawful Evil","Lawful Good","Lawful Neutral","Neutral Evil","Neutral Good","True Neutral"];
export const positive_traitsOptions: string[] = ["ACCESSIBLE","ACTIVE","ADAPTABLE","ADMIRABLE","ADVENTUROUS","AGREEABLE","ALERT","ALLOCENTRIC","ATTRACTIVE","BALANCED","BENEVOLENT","BRILLIANT","CALM","CAPABLE","CAPTIVATING","CARING","CHALLENGING","CHARISMATIC","CHARMING","CHEERFUL","CLEAN","CLEAR-HEADED","CLEVER","COLORFUL","COMPANIONLY","COMPASSIONATE","CONCILIATORY","CONFIDENT","CONSCIENTIOUS","CONSIDERATE","CONSTANT","CONTEMPLATIVE","COOPERATIVE","COURAGEOUS","COURTEOUS","CREATIVE","CULTURED","CURIOUS","DARING","DEBONAIR","DECENT","DECISIVE","DEDICATED","DEEP","DIGNIFIED","DIRECTED","DISCIPLINED","DISCREET","DRAMATIC","DUTIFUL","DYNAMIC","EARNEST","EBULLIENT","EDUCATED","EFFICIENT","ELEGANT","ELOQUENT","EMPATHETIC","ENERGETIC","ENTHUSIASTIC","ESTHETIC","EXCITING","EXTRAORDINARY","FAIR","FAITHFUL","FARSIGHTED","FEARLESS","FELICIFIC","FIRM","FLEXIBLE","FOCUSED","FORCEFUL","FORGIVING","FORTHRIGHT","FREETHINKING","FRIENDLY","FUN-LOVING","GALLANT","GENEROUS","GENTLE","GENUINE","GOOD-NATURED","GRACIOUS","HARDWORKING","HEALTHY","HEARTY","HELPFUL","HEROIC","HIGH-MINDED","HONEST","HONORABLE","HUMBLE","HUMOROUS","IDEALISTIC","IMAGINATIVE","IMPRESSIVE","INCISIVE","INCORRUPTIBLE","INDEPENDENT","INDIVIDUALISTIC","INNOVATIVE","INOFFENSIVE","INSIGHTFUL","INSOUCIANT","INTELLIGENT","INTUITIVE","INVULNERABLE","KIND","KNOWLEDGE","LEADERLY","LEISURELY","LIBERAL","LOGICAL","LOVABLE","LOYAL","LYRICAL","MAGNANIMOUS","MANY-SIDED","MASCULINE (MANLY)","MATURE","METHODICAL","METICULOUS","MODERATE","MODEST","MULTI-LEVELED","NEAT","NON AUTHORITARIAN","OBJECTIVE","OBSERVANT","OPEN","OPTIMISTIC","ORDERLY","ORGANIZED","ORIGINAL","PAINSTAKING","PASSIONATE","PATIENT","PATRIOTIC","PEACEFUL","PERCEPTIVE","PERFECTIONIST","PERSONABLE","PERSUASIVE","PLANFUL","PLAYFUL","POLISHED","POPULAR","PRACTICAL","PRECISE","PRINCIPLED","PROFOUND","PROTEAN","PROTECTIVE","PROVIDENTIAL","PRUDENT","PUNCTUAL","PURPOSEFUL","RATIONAL","REALISTIC","REFLECTIVE","RELAXED","RELIABLE","RESILIENT","RESOURCEFUL","RESPECTFUL","RESPONSIBLE","RESPONSIVE","REVERENTIAL","ROMANTIC","RUSTIC","SAGE","SANE","SCHOLARLY","SCRUPULOUS","SECURE","SELF-CRITICAL","SELF-DEFACING","SELF-DENYING","SELF-RELIANT","SELF-SUFFICIENT","SELFLESS","SENSITIVE","SENTIMENTAL","SERAPHIC","SERIOUS","SEXY","SHARING","SHREWD","SIMPLE","SKILLFUL","SOBER","SOCIABLE","SOLID","SOPHISTICATED","SPONTANEOUS","SPORTING","STABLE","STEADFAST","STEADY","STOIC","STRONG","STUDIOUS","SUAVE","SUBTLE","SWEET","SYMPATHETIC","SYSTEMATIC","TASTEFUL","TEACHERLY","THOROUGH","TIDY","TOLERANT","TRACTABLE","TRUSTING","UNCOMPLAINING","UNDERSTANDING","UNDOGMATIC","UNFOOLABLE","UPRIGHT","URBANE","VENTURESOME","VIVACIOUS","WARM","WELL-BRED","WELL-READ","WELL-ROUNDED","WINNING","WISE","WITTY","YOUTHFUL"];
export const neutral_traitsOptions: string[] = ["ABSENTMINDED","AGGRESSIVE","AMBITIOUS","AMUSING","ARTFUL","ASCETIC","AUTHORITARIAN","BIG-THINKING","CHUMMY","CIRCUMSPECT","COMPETITIVE","COMPLEX","CONFIDENTIAL","CONSERVATIVE","CONTRADICTORY","CRISP","CUTE","DECEPTIVE","DETERMINED","DOMINATING","DREAMY","DRIVING","DROLL","DRY","EARTHY","EFFEMINATE","EMOTIONAL","ENIGMATIC","EXPERIMENTAL","FAMILIAL","FOLKSY","FORMAL","FREEWHEELING","FRUGAL","GLAMOROUS","GUILELESS","HIGH-SPIRITED","HURIED","HYPNOTIC","ICONOCLASTIC","IDIOSYNCRATIC","IMPASSIVE","IMPERSONAL","IMPRESSIONABLE","INTENSE","INVISIBLE","IRRELIGIOUS","IRREVERENT","MATERNAL","MELLOW","MODERN","MORALISTIC","MYSTICAL","NEUTRAL","NONCOMMITTAL","NONCOMPETITIVE","OBEDIENT","OLD-FASHIONED","ORDINARY","OUTSPOKEN","PATERNALISTIC","PHYSICAL","PLACID","POLITICAL","PREDICTABLE","PREOCCUPIED","PRIVATE","PROGRESSIVE","PROUD","PURE","QUESTIONING","QUIET","RELIGIOUS","RESERVED","RESTRAINED","RETIRING","SARCASTIC","SELF-CONSCIOUS","SENSUAL","SKEPTICAL","SMOOTH","SOFT","SOLEMN","SOLITARY","STERN","STOLID","STRICT","STUBBORN","STYLISH","SUBJECTIVE","SURPRISING","TOUGH","UNAGGRESSIVE","UNAMBITIOUS","UNCEREMONIOUS","UNCHANGING","UNDEMANDING","UNFATHOMABLE","UNHURRIED","UNINHIBITED","UNPATRIOTIC","UNPREDICTABLE","UNRELIGIOUS","UNSENTIMENTAL","WHIMSICAL"];
export const negative_traitsOptions: string[] = ["ABRASIVE","ABRUPT","AGONIZING","AIMLESS","AIRY","ALOOF","AMORAL","ANGRY","ASOCIAL","ASSERTIVE","ASTIGMATIC","BARBARIC","BEWILDERED","BIZARRE","BLAND","BLUNT","BOISTEROUS","BRITTLE","BRUTAL","CALCULATING","CALLOUS","CANTANKEROUS","CARELESS","CAUTIOUS","CHARMLESS","CHILDISH","CLUMSY","COARSE","COLD","COLORLESS","COMPLACENT","COMPLAINTIVE","COMPULSIVE","CONCEITED","CONDEMNATORY","CONFORMIST","CONFUSED","CONTEMPTIBLE","CONVENTIONAL","COWARDLY","CRAFTY","CRASS","CRAZY","CRIMINAL","CRITICAL","CRUDE","CRUEL","CYNICAL","DECADENT","DECEITFUL","DELICATE","DEMANDING","DEPENDENT","DESPERATE","DESTRUCTIVE","DEVIOUS","DIFFICULT","DIRTY","DISCONCERTING","DISCONTENTED","DISCOURAGING","DISCOURTEOUS","DISHONEST","DISLOYAL","DISOBEDIENT","DISORDERLY","DISORGANIZED","DISPUTATIOUS","DISRESPECTFUL","DISRUPTIVE","DISSOLUTE","DISSONANT","DISTRACTIBLE","DISTURBING","DOGMATIC","DOMINEERING","DULL","EASILY DISCOURAGED","EGOCENTRIC","ENERVATED","ENVIOUS","ERRATIC","ESCAPIST","EXCITABLE","EXPEDIENT","EXTRAVAGANT","EXTREME","FAITHLESS","FANATICAL","FANCIFUL","FATALISTIC","FAWNING","FEARFUL","FICKLE","FIERY","FIXED","FLAMBOYANT","FOOLISH","FORGETFUL","FRAUDULENT","FRIGHTENING","FRIVOLOUS","GLOOMY","GRACELESS","GRAND","GREEDY","GRIM","GULLIBLE","HATEFUL","HAUGHTY","HEDONISTIC","HESITANT","HIDEBOUND","HIGH-HANDED","HOSTILE","IGNORANT","IMITATIVE","IMPATIENT","IMPRACTICAL","IMPRUDENT","IMPULSIVE","INCONSIDERATE","INCURIOUS","INDECISIVE","INDULGENT","INERT","INHIBITED","INSECURE","INSENSITIVE","INSINCERE","INSULTING","INTOLERANT","IRASCIBLE","IRRATIONAL","IRRESPONSIBLE","IRRITABLE","LAZY","LIBIDINOUS","LOQUACIOUS","MALICIOUS","MANIPULATIVE","MANNERED","MANNERLESS","MAWKISH","MEALY MOUTHED","MECHANICAL","MEDDLESOME","MELANCHOLIC","MERETRICIOUS","MESSY","MISERABLE","MISERLY","MISGUIDED","MISTAKEN","MONEY-MINDED","MONSTROUS","MOODY","MORBID","MUDDLE-HEADED","NAIVE","NARCISSISTIC","NARROW","NARROW-MINDED","NATTY","NEGATIVISTIC","NEGLECTFUL","NEUROTIC","NIHILISTIC","OBNOXIOUS","OBSESSIVE","OBVIOUS","ODD","OFFHAND","ONE-DIMENSIONAL","ONE-SIDED","OPINIONATED","OPPORTUNISTIC","OPPRESSED","OUTRAGEOUS","OVER IMAGINATIVE","PARANOID","PASSIVE","PEDANTIC","PERVERSE","PETTY","PHARISAICAL","PHLEGMATIC","PLODDING","POMPOUS","POSSESSIVE","POWER-HUNGRY","PREDATORY","PREJUDICED","PRESUMPTUOUS","PRETENTIOUS","PRIM","PROCRASTINATING","PROFLIGATE","PROVOCATIVE","PUGNACIOUS","PURITANICAL","QUIRKY","REACTIONARY","REACTIVE","REGIMENTAL","REGRETFUL","REPENTANT","REPRESSED","RESENTFUL","RIDICULOUS","RIGID","RITUALISTIC","ROWDY","RUINED","SADISTIC","SANCTIMONIOUS","SCHEMING","SCORNFUL","SECRETIVE","SEDENTARY","SELF-INDULGENT","SELFISH","SHALLOW","SHORTSIGHTED","SHY","SILLY","SINGLE-MINDED","SLOPPY","SLOW","SLY","SMALL-THINKING","SOFT HEADED","SORDID","STEELY","STIFF","STRONG-WILLED","STUPID","SUBMISSIVE","SUPERFICIAL","SUPERSTITIOUS","SUSPICIOUS","TACTLESS","TASTELESS","TENSE","THIEVISH","THOUGHTLESS","TIMID","TRANSPARENT","TREACHEROUS","TRENDY","TROUBLESOME","UNAPPRECIATIVE","UNCARING","UNCHARITABLE","UNCONVINCING","UNCOOPERATIVE","UNCREATIVE","UNCRITICAL","UNCTUOUS","UNDISCIPLINED","UNFRIENDLY","UNGRATEFUL","UNHEALTHY","UNIMAGINATIVE","UNIMPRESSIVE","UNLOVABLE","UNPOLISHED","UNPREDICTABLE","UNPRINCIPLED","UNREALISTIC","UNREFLECTIVE","UNRELIABLE","UNRESTRAINED","UNSELF-CRITICAL","UNSTABLE","VACUOUS","VAGUE","VENAL","VENOMOUS","VINDICTIVE","VULNERABLE","WEAK","WEAK-WILLED","WELL-MEANING","WILLFUL","WISHFUL","ZANY"];
export const genderOptions: string[] = ["Agender","Androgynous","Bigender","Cisgender","Demiboy","Demigirl","Genderfluid","Genderqueer","Intersex","Neutrois","Non-binary","Pangender","Third Gender","Transgender","Two-spirit"];
