// Auto-generated file - do not edit manually
// Generated from: dropdown_options table in database
// This file is a FALLBACK - the database is the primary source of truth
// The useDropdownOptions hook fetches from database first, then falls back to this file
// Run: npx tsx scripts/utilities/generate-dropdown-options.ts
// Last generated: 2025-12-17T13:50:59.430Z

export const csvOptions: Record<string, string[]> = {
  "accent": [
    "Boston",
    "Brazilian Portuguese",
    "Californian",
    "Canadian",
    "Caribbean",
    "Chicago",
    "Chicano English (Mexican-American)",
    "Chinese",
    "Dutch",
    "German",
    "Greek",
    "Hawaiian Pidgin",
    "Indian",
    "Jamaican",
    "Japanese",
    "Korean",
    "Midwestern",
    "Minnesotan",
    "New Orleans (cajun)",
    "New York",
    "New Zealand",
    "Pacific Northwest",
    "Philadelphia",
    "Polish",
    "Russian",
    "South African",
    "Southern Appalachian",
    "Southern Californian (SoCal)",
    "Texan",
    "Turkish",
    "Valley (California)",
    "Welsh"
  ],
  "ethnicity_race": [
    "African",
    "African Descent",
    "Afro-Caribbean",
    "Afro-Latinx",
    "Arab",
    "Armenian",
    "Ashkenazi Jewish",
    "Asian",
    "Asian Descent",
    "Australian Aboriginal",
    "Basque",
    "Bengali",
    "Berber",
    "Bhutanese",
    "Brazilian",
    "Burmese",
    "Cambodian",
    "Caribbean",
    "Caucasian",
    "Caucasian / Pacific Islander",
    "Chicano",
    "Chinese",
    "Creole",
    "Cuban",
    "Dominican",
    "Druze",
    "Eastern European",
    "Egyptian",
    "Ethiopian",
    "Finnish",
    "First Nations",
    "French",
    "German",
    "German Descent",
    "Gerudo / Sheikah",
    "Ghanaian",
    "Greek Descent",
    "Guatemalan",
    "Haitian",
    "Hmong",
    "Hylian",
    "Icelandic",
    "Igbo",
    "Indigenous Australian",
    "Indigenous Canadian",
    "Inuit",
    "Iranian",
    "Iraqi",
    "Israeli",
    "Italian",
    "Italian/Chinese",
    "Japanese",
    "Japanese/British",
    "Jewish",
    "Kazakh",
    "Korean",
    "Kurdish",
    "Latinx",
    "Lebanese",
    "Lithuanian",
    "Lithuanian / Romanian",
    "Lithuanian/Mediterranean/French/Arabian",
    "Lithuanian/Romanian/French/Arabian",
    "Maori",
    "Mayan",
    "Mediterranean",
    "Mediterranean Caucasian Mix",
    "Mediterranean Descent",
    "Meowth",
    "Mestizo",
    "Mexican",
    "Mexican-American",
    "Middle Eastern",
    "Mongolian",
    "Moravian",
    "Nigerian",
    "Pacific Islander",
    "Palestinian",
    "Pashtun",
    "Persian",
    "Polynesian Descent",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Roma",
    "Romanian",
    "Russian",
    "Samoan",
    "Sardinian",
    "Scandinavian",
    "Scanner",
    "Sephardic Jewish",
    "Sicilian",
    "Somali",
    "South Asian",
    "Southeast Asian",
    "Swahili",
    "Syrian",
    "Tibetan",
    "Tlingit",
    "Tongan",
    "Turkish",
    "Uyghur",
    "Venezuelan",
    "Vietnamese",
    "West African",
    "White",
    "Yoruba"
  ],
  "eye_color": [
    "Ash",
    "Azure",
    "Black",
    "Black/Silver",
    "Blood",
    "Blue",
    "Brown",
    "Bubblegum",
    "Burnt",
    "Cardinal",
    "Carmine",
    "Coral",
    "Crimson",
    "Deep",
    "Espresso",
    "Gold",
    "Gray",
    "Green",
    "Green/Pink",
    "Ice",
    "Indigo",
    "Lemon",
    "Light",
    "Lilac",
    "Lime",
    "Multi",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "Yellow"
  ],
  "gender_identity": [
    "Agender",
    "Androgynous",
    "Bigender",
    "Cisgender",
    "Demiboy",
    "Demigirl",
    "Genderfluid",
    "Genderqueer",
    "Intersex",
    "Neutrois",
    "Non-binary",
    "Pangender",
    "Third Gender",
    "Transgender",
    "Two-spirit"
  ],
  "hair_color": [
    "Ash",
    "Baby",
    "Beige",
    "Black",
    "Black/Silver",
    "Blonde",
    "Blue",
    "Brown",
    "Cobalt",
    "Cool",
    "Dark",
    "Dusty",
    "Dusty Rose",
    "Fern",
    "Gray",
    "Green",
    "Jade",
    "Medium",
    "Neutral",
    "Olive",
    "Orange",
    "Pink",
    "Pumpkin",
    "Purple",
    "Silver",
    "Soft",
    "Tawny",
    "White"
  ],
  "mbti": [
    "ENFJ",
    "ENFP",
    "ENTJ",
    "ENTP",
    "ESFJ",
    "ESFP",
    "ESTJ",
    "ESTP",
    "INFJ",
    "INFP",
    "INTJ",
    "INTP",
    "ISFJ",
    "ISFP",
    "ISTJ",
    "ISTP"
  ],
  "moral": [
    "Chaotic Evil",
    "Chaotic Good",
    "Chaotic Neutral",
    "Lawful Evil",
    "Lawful Good",
    "Lawful Neutral",
    "Neutral Evil",
    "Neutral Good",
    "True Neutral"
  ],
  "nationality": [
    "Afghan",
    "American",
    "Argentine",
    "Australian",
    "Austrian",
    "Bangladeshi",
    "Belgian",
    "Bosnian",
    "Brazilian",
    "British",
    "Bulgarian",
    "Canadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Czech",
    "Danish",
    "Dominican",
    "Dutch",
    "Egyptian",
    "Emirati",
    "Ethiopian",
    "Filipino",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Haitian",
    "Hungarian",
    "Icelandic",
    "Inariko",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kenyan",
    "Konohagakure",
    "Korean",
    "Lebanese",
    "Malaysian",
    "Mexican",
    "Mongolian",
    "Moroccan",
    "New Zealander (Kiwi)",
    "Nigerian",
    "Norwegian",
    "Pakistani",
    "Palestinian",
    "Panamanian",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Rudania",
    "Russian",
    "Saudi Arabian",
    "Scottish",
    "Serbian",
    "Singaporean",
    "South African",
    "Spanish",
    "Sri Lankan",
    "Sun Empire",
    "Sunagakure",
    "Swedish",
    "Swiss",
    "Syrian",
    "Thai",
    "Trinidadian",
    "Turkish",
    "Ukrainian",
    "Venezuelan",
    "Vhintl",
    "Vietnamese",
    "Welsh"
  ],
  "negative_traits": [
    "ABRASIVE",
    "ABRUPT",
    "AGONIZING",
    "AIMLESS",
    "AIRY",
    "ALOOF",
    "AMORAL",
    "ANGRY",
    "ASOCIAL",
    "ASSERTIVE",
    "ASTIGMATIC",
    "BARBARIC",
    "BEWILDERED",
    "BIZARRE",
    "BLAND",
    "BLUNT",
    "BOISTEROUS",
    "BRITTLE",
    "BRUTAL",
    "CALCULATING",
    "CALLOUS",
    "CANTANKEROUS",
    "CARELESS",
    "CAUTIOUS",
    "CHARMLESS",
    "CHILDISH",
    "CLUMSY",
    "COARSE",
    "COLD",
    "COLORLESS",
    "COMPLACENT",
    "COMPLAINTIVE",
    "COMPULSIVE",
    "CONCEITED",
    "CONDEMNATORY",
    "CONFORMIST",
    "CONFUSED",
    "CONTEMPTIBLE",
    "CONVENTIONAL",
    "COWARDLY",
    "CRAFTY",
    "CRASS",
    "CRAZY",
    "CRIMINAL",
    "CRITICAL",
    "CRUDE",
    "CRUEL",
    "CYNICAL",
    "DECADENT",
    "DECEITFUL",
    "DELICATE",
    "DEMANDING",
    "DEPENDENT",
    "DESPERATE",
    "DESTRUCTIVE",
    "DEVIOUS",
    "DIFFICULT",
    "DIRTY",
    "DISCONCERTING",
    "DISCONTENTED",
    "DISCOURAGING",
    "DISCOURTEOUS",
    "DISHONEST",
    "DISLOYAL",
    "DISOBEDIENT",
    "DISORDERLY",
    "DISORGANIZED",
    "DISPUTATIOUS",
    "DISRESPECTFUL",
    "DISRUPTIVE",
    "DISSOLUTE",
    "DISSONANT",
    "DISTRACTIBLE",
    "DISTURBING",
    "DOGMATIC",
    "DOMINEERING",
    "DULL",
    "EASILY DISCOURAGED",
    "EGOCENTRIC",
    "ENERVATED",
    "ENVIOUS",
    "ERRATIC",
    "ESCAPIST",
    "EXCITABLE",
    "EXPEDIENT",
    "EXTRAVAGANT",
    "EXTREME",
    "FAITHLESS",
    "FANATICAL",
    "FANCIFUL",
    "FATALISTIC",
    "FAWNING",
    "FEARFUL",
    "FICKLE",
    "FIERY",
    "FIXED",
    "FLAMBOYANT",
    "FOOLISH",
    "FORGETFUL",
    "FRAUDULENT",
    "FRIGHTENING",
    "FRIVOLOUS",
    "GLOOMY",
    "GRACELESS",
    "GRAND",
    "GREEDY",
    "GRIM",
    "GULLIBLE",
    "HATEFUL",
    "HAUGHTY",
    "HEDONISTIC",
    "HESITANT",
    "HIDEBOUND",
    "HIGH-HANDED",
    "HOSTILE",
    "IGNORANT",
    "IMITATIVE",
    "IMPATIENT",
    "IMPRACTICAL",
    "IMPRUDENT",
    "IMPULSIVE",
    "INCONSIDERATE",
    "INCURIOUS",
    "INDECISIVE",
    "INDULGENT",
    "INERT",
    "INHIBITED",
    "INSECURE",
    "INSENSITIVE",
    "INSINCERE",
    "INSULTING",
    "INTOLERANT",
    "IRASCIBLE",
    "IRRATIONAL",
    "IRRESPONSIBLE",
    "IRRITABLE",
    "LAZY",
    "LIBIDINOUS",
    "LOQUACIOUS",
    "MALICIOUS",
    "MANIPULATIVE",
    "MANNERED",
    "MANNERLESS",
    "MAWKISH",
    "MEALY MOUTHED",
    "MECHANICAL",
    "MEDDLESOME",
    "MELANCHOLIC",
    "MERETRICIOUS",
    "MESSY",
    "MISERABLE",
    "MISERLY",
    "MISGUIDED",
    "MISTAKEN",
    "MONEY-MINDED",
    "MONSTROUS",
    "MOODY",
    "MORBID",
    "MUDDLE-HEADED",
    "NAIVE",
    "NARCISSISTIC",
    "NARROW",
    "NARROW-MINDED",
    "NATTY",
    "NEGATIVISTIC",
    "NEGLECTFUL",
    "NEUROTIC",
    "NIHILISTIC",
    "OBNOXIOUS",
    "OBSESSIVE",
    "OBVIOUS",
    "ODD",
    "OFFHAND",
    "ONE-DIMENSIONAL",
    "ONE-SIDED",
    "OPINIONATED",
    "OPPORTUNISTIC",
    "OPPRESSED",
    "OUTRAGEOUS",
    "OVER IMAGINATIVE",
    "PARANOID",
    "PASSIVE",
    "PEDANTIC",
    "PERVERSE",
    "PETTY",
    "PHARISAICAL",
    "PHLEGMATIC",
    "PLODDING",
    "POMPOUS",
    "POSSESSIVE",
    "POWER-HUNGRY",
    "PREDATORY",
    "PREJUDICED",
    "PRESUMPTUOUS",
    "PRETENTIOUS",
    "PRIM",
    "PROCRASTINATING",
    "PROFLIGATE",
    "PROVOCATIVE",
    "PUGNACIOUS",
    "PURITANICAL",
    "QUIRKY",
    "REACTIONARY",
    "REACTIVE",
    "REGIMENTAL",
    "REGRETFUL",
    "REPENTANT",
    "REPRESSED",
    "RESENTFUL",
    "RIDICULOUS",
    "RIGID",
    "RITUALISTIC",
    "ROWDY",
    "RUINED",
    "SADISTIC",
    "SANCTIMONIOUS",
    "SCHEMING",
    "SCORNFUL",
    "SECRETIVE",
    "SEDENTARY",
    "SELF-INDULGENT",
    "SELFISH",
    "SHALLOW",
    "SHORTSIGHTED",
    "SHY",
    "SILLY",
    "SINGLE-MINDED",
    "SLOPPY",
    "SLOW",
    "SLY",
    "SMALL-THINKING",
    "SOFT HEADED",
    "SORDID",
    "STEELY",
    "STIFF",
    "STRONG-WILLED",
    "STUBBORN",
    "STUPID",
    "SUBMISSIVE",
    "SUPERFICIAL",
    "SUPERSTITIOUS",
    "SUSPICIOUS",
    "TACTLESS",
    "TASTELESS",
    "TENSE",
    "TEST123",
    "THIEVISH",
    "THOUGHTLESS",
    "TIMID",
    "TRANSPARENT",
    "TREACHEROUS",
    "TRENDY",
    "TROUBLESOME",
    "UNAPPRECIATIVE",
    "UNCARING",
    "UNCHARITABLE",
    "UNCONVINCING",
    "UNCOOPERATIVE",
    "UNCREATIVE",
    "UNCRITICAL",
    "UNCTUOUS",
    "UNDISCIPLINED",
    "UNFRIENDLY",
    "UNGRATEFUL",
    "UNHEALTHY",
    "UNIMAGINATIVE",
    "UNIMPRESSIVE",
    "UNLOVABLE",
    "UNPOLISHED",
    "UNPREDICTABLE",
    "UNPRINCIPLED",
    "UNREALISTIC",
    "UNREFLECTIVE",
    "UNRELIABLE",
    "UNRESTRAINED",
    "UNSELF-CRITICAL",
    "UNSTABLE",
    "VACUOUS",
    "VAGUE",
    "VENAL",
    "VENOMOUS",
    "VINDICTIVE",
    "VULNERABLE",
    "WEAK",
    "WEAK-WILLED",
    "WELL-MEANING",
    "WILLFUL",
    "WISHFUL",
    "ZANY"
  ],
  "neutral_traits": [
    "ABSENTMINDED",
    "AGGRESSIVE",
    "AMBITIOUS",
    "AMUSING",
    "ARTFUL",
    "ASCETIC",
    "AUTHORITARIAN",
    "BIG-THINKING",
    "CHUMMY",
    "CIRCUMSPECT",
    "COMPETITIVE",
    "COMPLEX",
    "CONFIDENTIAL",
    "CONSERVATIVE",
    "CONTRADICTORY",
    "CRISP",
    "CUTE",
    "DECEPTIVE",
    "DETERMINED",
    "DOMINATING",
    "DREAMY",
    "DRIVING",
    "DROLL",
    "DRY",
    "EARTHY",
    "EFFEMINATE",
    "EMOTIONAL",
    "ENIGMATIC",
    "EXPERIMENTAL",
    "FAMILIAL",
    "FOLKSY",
    "FORMAL",
    "FREEWHEELING",
    "FRUGAL",
    "GLAMOROUS",
    "GUILELESS",
    "HIGH-SPIRITED",
    "HURIED",
    "HYPNOTIC",
    "ICONOCLASTIC",
    "IDIOSYNCRATIC",
    "IMPASSIVE",
    "IMPERSONAL",
    "IMPRESSIONABLE",
    "INTENSE",
    "INVISIBLE",
    "IRRELIGIOUS",
    "IRREVERENT",
    "MATERNAL",
    "MELLOW",
    "MODERN",
    "MORALISTIC",
    "MYSTICAL",
    "NEUTRAL",
    "NONCOMMITTAL",
    "NONCOMPETITIVE",
    "OBEDIENT",
    "OLD-FASHIONED",
    "ORDINARY",
    "OUTSPOKEN",
    "PATERNALISTIC",
    "PHYSICAL",
    "PLACID",
    "POLITICAL",
    "PREDICTABLE",
    "PREOCCUPIED",
    "PRIVATE",
    "PROGRESSIVE",
    "PROUD",
    "PURE",
    "QUESTIONING",
    "QUIET",
    "RELIGIOUS",
    "RESERVED",
    "RESTRAINED",
    "RETIRING",
    "SARCASTIC",
    "SELF-CONSCIOUS",
    "SENSUAL",
    "SKEPTICAL",
    "SMOOTH",
    "SOFT",
    "SOLEMN",
    "SOLITARY",
    "STERN",
    "STOLID",
    "STRICT",
    "STUBBORN",
    "STYLISH",
    "SUBJECTIVE",
    "SURPRISING",
    "TOUGH",
    "UNAGGRESSIVE",
    "UNAMBITIOUS",
    "UNCEREMONIOUS",
    "UNCHANGING",
    "UNDEMANDING",
    "UNFATHOMABLE",
    "UNHURRIED",
    "UNINHIBITED",
    "UNPATRIOTIC",
    "UNPREDICTABLE",
    "UNRELIGIOUS",
    "UNSENTIMENTAL",
    "WHIMSICAL"
  ],
  "occupation": [
    "Abbot/abbess",
    "Abecedarian",
    "Abjurer",
    "Acater",
    "Accoucheur/obstetrician/midwife",
    "Accountant",
    "Accoutrements/coinsmith",
    "Acolyte",
    "Acrobat",
    "Actor",
    "Actuary",
    "Acupuncturist",
    "Administrator",
    "Admiral",
    "Adventurer",
    "Advertising Executive",
    "Aerialist/trapezist",
    "Affeeror",
    "Agister",
    "Air Traffic Controller",
    "Aircraft Engineer",
    "Alchemist",
    "Alderman",
    "Alienist",
    "Almoner",
    "Anaesthetist",
    "Animal Breeder",
    "Animal Collector/monster Collector",
    "Animal/monster Handler",
    "Anthropologist",
    "Antique Dealer",
    "Apothecary",
    "Appraiser",
    "Apprentice",
    "Arborist",
    "Archaeologist",
    "Archbishop",
    "Architect",
    "Archivist",
    "Archmage",
    "Armorer",
    "Aromatherapist",
    "Arranger",
    "Art Critic",
    "Art Dealer",
    "Art Historian",
    "Art Therapist",
    "Artificer",
    "Artist",
    "Arts / Artists / Artistic",
    "Assassin",
    "Assay Master",
    "Assayer",
    "Assembly Line Worker",
    "Assistant",
    "Astrologer",
    "Astronomer",
    "Athlete",
    "Au Pair",
    "Auctioneer",
    "Auditor",
    "Author",
    "Baggage Handler",
    "Bagnio Keeper",
    "Bailiff",
    "Baker",
    "Baler",
    "Bandit",
    "Bank Clerk",
    "Bank Manager",
    "Banker",
    "Bar Staff",
    "Barber",
    "Bard",
    "Barkeep",
    "Barmaid/barboy",
    "Baron/baroness",
    "Barrister",
    "Beekeeper",
    "Beggar/pauper",
    "Billboard Poster",
    "Biochemist",
    "Biologist",
    "Bishop",
    "Blacksmith",
    "Bladesmith",
    "Blood Hunter/monster Hunter",
    "Bloodletter",
    "Boat Builder",
    "Boatman",
    "Bodyguard",
    "Bone Oracle",
    "Bookbinder",
    "Bookkeeper",
    "Bookmaker",
    "Bosun",
    "Botanist",
    "Bottler",
    "Bouncer",
    "Bounty Hunter",
    "Bowyer",
    "Breeder",
    "Brewer",
    "Brewery Worker",
    "Brick Mason / Bricklayer / Mason",
    "Bricklayer",
    "Brickmaker",
    "Broadcaster",
    "Broom Maker",
    "Brothel Keeper",
    "Bug Catcher",
    "Builder",
    "Building Labourer",
    "Burglar",
    "Bus Driver",
    "Business Consultant",
    "Business Owner",
    "Busker/street Musician",
    "Butcher",
    "Butler",
    "Cabbie/wagoner",
    "Cabin Boy/cabin Girl",
    "Cabin Crew",
    "Cabinet Maker",
    "Calligraphist",
    "Camera Operator",
    "Candlemaker",
    "Cantor",
    "Captain",
    "Car Dealer",
    "Car Wash Attendant",
    "Caravaneer",
    "Cardinal",
    "Care Assistant",
    "Career Criminal",
    "Careers Advisor",
    "Caregiver",
    "Caretaker",
    "Carpenter",
    "Carpet Fitter",
    "Carter",
    "Cartographer",
    "Cartoonist",
    "Cartwright",
    "Cashier",
    "Castellan",
    "Casual Worker",
    "Catering Staff",
    "Cavalryman/cavalier",
    "Celebrity",
    "Cemetery Worker",
    "Ceo",
    "Chancellor",
    "Chandler",
    "Chaplain",
    "Charcoal Maker",
    "Charioteer",
    "Charlatan/conman",
    "Chatelaine/majordomo",
    "Chauffeur",
    "Chef",
    "Chef Or Cook",
    "Chemist",
    "Chief",
    "Childcare Worker",
    "Childminder",
    "Childrens Entertainer",
    "Chimney Sweep",
    "Chimney Sweeper",
    "Chiropodist",
    "Chiropractor",
    "Choirmaster",
    "Choreographer",
    "Circus Worker",
    "City Watch",
    "Civil Servant",
    "Clairvoyant",
    "Cleaner",
    "Clergyman",
    "Cleric",
    "Clerical Assistant",
    "Clerk",
    "Clockmaker",
    "Clown",
    "Coastguard",
    "Cobbler",
    "Cockfighter/game Fighter",
    "Collector",
    "Comedian",
    "Commissar",
    "Community Worker",
    "Company Director",
    "Composer",
    "Composer Or Songwriter",
    "Computer Analyst",
    "Computer Engineer",
    "Computer Programmer",
    "Con Artist",
    "Conductor",
    "Confessor",
    "Conjuror",
    "Conservationist",
    "Constable",
    "Construction Worker",
    "Contortionist",
    "Cook",
    "Cooper/hooper",
    "Copyist",
    "Coroner",
    "Costume Designer",
    "Costumer",
    "Councillor",
    "Counsellor",
    "Count/earl/countess",
    "Courier",
    "Courtier",
    "Cowherd",
    "Craftsperson",
    "Crane Driver",
    "Crematorium Worker",
    "Crime",
    "Crime Boss",
    "Crossing Sweeper",
    "Croupier",
    "Crown Prosecutor",
    "Cult Leader",
    "Cultist",
    "Curator",
    "Customs Officer",
    "Cutler",
    "Cutpurse",
    "Dairy Boy/dairymaid",
    "Dancer",
    "Data Processor",
    "Deacon",
    "Dean",
    "Debt Collector",
    "Decorator",
    "Deity",
    "Delivery Driver",
    "Dental Hygienist",
    "Dental Nurse",
    "Dentist",
    "Deserter",
    "Designer",
    "Detective/investigator",
    "Dietician",
    "Diplomat",
    "Director",
    "Disc Jockey",
    "Disgraced Noble",
    "Diver",
    "Diviner",
    "Doctor",
    "Doctor/physician",
    "Domestic Staff",
    "Doorman",
    "Drakologist",
    "Draper",
    "Dressmaker",
    "Driving Instructor",
    "Drug Dealer",
    "Drug Lord",
    "Druid",
    "Drummer/fifer",
    "Drunkard",
    "Duelist",
    "Duke/duchess",
    "Dungeon Delver",
    "Dyer",
    "Economist",
    "Editor",
    "Elder",
    "Electrician",
    "Elementalist",
    "Embalmer",
    "Embroiderer",
    "Emperor/empress",
    "Enchanter/enchantress",
    "Engineer",
    "Engraver",
    "Entomologist",
    "Entrepreneur"
  ]
};

// Individual exports for convenience
export const accentOptions: string[] = ["Boston","Brazilian Portuguese","Californian","Canadian","Caribbean","Chicago","Chicano English (Mexican-American)","Chinese","Dutch","German","Greek","Hawaiian Pidgin","Indian","Jamaican","Japanese","Korean","Midwestern","Minnesotan","New Orleans (cajun)","New York","New Zealand","Pacific Northwest","Philadelphia","Polish","Russian","South African","Southern Appalachian","Southern Californian (SoCal)","Texan","Turkish","Valley (California)","Welsh"];
export const ethnicity_raceOptions: string[] = ["African","African Descent","Afro-Caribbean","Afro-Latinx","Arab","Armenian","Ashkenazi Jewish","Asian","Asian Descent","Australian Aboriginal","Basque","Bengali","Berber","Bhutanese","Brazilian","Burmese","Cambodian","Caribbean","Caucasian","Caucasian / Pacific Islander","Chicano","Chinese","Creole","Cuban","Dominican","Druze","Eastern European","Egyptian","Ethiopian","Finnish","First Nations","French","German","German Descent","Gerudo / Sheikah","Ghanaian","Greek Descent","Guatemalan","Haitian","Hmong","Hylian","Icelandic","Igbo","Indigenous Australian","Indigenous Canadian","Inuit","Iranian","Iraqi","Israeli","Italian","Italian/Chinese","Japanese","Japanese/British","Jewish","Kazakh","Korean","Kurdish","Latinx","Lebanese","Lithuanian","Lithuanian / Romanian","Lithuanian/Mediterranean/French/Arabian","Lithuanian/Romanian/French/Arabian","Maori","Mayan","Mediterranean","Mediterranean Caucasian Mix","Mediterranean Descent","Meowth","Mestizo","Mexican","Mexican-American","Middle Eastern","Mongolian","Moravian","Nigerian","Pacific Islander","Palestinian","Pashtun","Persian","Polynesian Descent","Portuguese","Punjabi","Quechua","Roma","Romanian","Russian","Samoan","Sardinian","Scandinavian","Scanner","Sephardic Jewish","Sicilian","Somali","South Asian","Southeast Asian","Swahili","Syrian","Tibetan","Tlingit","Tongan","Turkish","Uyghur","Venezuelan","Vietnamese","West African","White","Yoruba"];
export const eye_colorOptions: string[] = ["Ash","Azure","Black","Black/Silver","Blood","Blue","Brown","Bubblegum","Burnt","Cardinal","Carmine","Coral","Crimson","Deep","Espresso","Gold","Gray","Green","Green/Pink","Ice","Indigo","Lemon","Light","Lilac","Lime","Multi","Orange","Pink","Purple","Red","Yellow"];
export const gender_identityOptions: string[] = ["Agender","Androgynous","Bigender","Cisgender","Demiboy","Demigirl","Genderfluid","Genderqueer","Intersex","Neutrois","Non-binary","Pangender","Third Gender","Transgender","Two-spirit"];
export const hair_colorOptions: string[] = ["Ash","Baby","Beige","Black","Black/Silver","Blonde","Blue","Brown","Cobalt","Cool","Dark","Dusty","Dusty Rose","Fern","Gray","Green","Jade","Medium","Neutral","Olive","Orange","Pink","Pumpkin","Purple","Silver","Soft","Tawny","White"];
export const mbtiOptions: string[] = ["ENFJ","ENFP","ENTJ","ENTP","ESFJ","ESFP","ESTJ","ESTP","INFJ","INFP","INTJ","INTP","ISFJ","ISFP","ISTJ","ISTP"];
export const moralOptions: string[] = ["Chaotic Evil","Chaotic Good","Chaotic Neutral","Lawful Evil","Lawful Good","Lawful Neutral","Neutral Evil","Neutral Good","True Neutral"];
export const nationalityOptions: string[] = ["Afghan","American","Argentine","Australian","Austrian","Bangladeshi","Belgian","Bosnian","Brazilian","British","Bulgarian","Canadian","Chilean","Chinese","Colombian","Costa Rican","Croatian","Cuban","Czech","Danish","Dominican","Dutch","Egyptian","Emirati","Ethiopian","Filipino","Finnish","French","German","Greek","Haitian","Hungarian","Icelandic","Inariko","Indian","Indonesian","Iranian","Iraqi","Irish","Israeli","Italian","Jamaican","Japanese","Jordanian","Kenyan","Konohagakure","Korean","Lebanese","Malaysian","Mexican","Mongolian","Moroccan","New Zealander (Kiwi)","Nigerian","Norwegian","Pakistani","Palestinian","Panamanian","Peruvian","Polish","Portuguese","Romanian","Rudania","Russian","Saudi Arabian","Scottish","Serbian","Singaporean","South African","Spanish","Sri Lankan","Sun Empire","Sunagakure","Swedish","Swiss","Syrian","Thai","Trinidadian","Turkish","Ukrainian","Venezuelan","Vhintl","Vietnamese","Welsh"];
export const negative_traitsOptions: string[] = ["ABRASIVE","ABRUPT","AGONIZING","AIMLESS","AIRY","ALOOF","AMORAL","ANGRY","ASOCIAL","ASSERTIVE","ASTIGMATIC","BARBARIC","BEWILDERED","BIZARRE","BLAND","BLUNT","BOISTEROUS","BRITTLE","BRUTAL","CALCULATING","CALLOUS","CANTANKEROUS","CARELESS","CAUTIOUS","CHARMLESS","CHILDISH","CLUMSY","COARSE","COLD","COLORLESS","COMPLACENT","COMPLAINTIVE","COMPULSIVE","CONCEITED","CONDEMNATORY","CONFORMIST","CONFUSED","CONTEMPTIBLE","CONVENTIONAL","COWARDLY","CRAFTY","CRASS","CRAZY","CRIMINAL","CRITICAL","CRUDE","CRUEL","CYNICAL","DECADENT","DECEITFUL","DELICATE","DEMANDING","DEPENDENT","DESPERATE","DESTRUCTIVE","DEVIOUS","DIFFICULT","DIRTY","DISCONCERTING","DISCONTENTED","DISCOURAGING","DISCOURTEOUS","DISHONEST","DISLOYAL","DISOBEDIENT","DISORDERLY","DISORGANIZED","DISPUTATIOUS","DISRESPECTFUL","DISRUPTIVE","DISSOLUTE","DISSONANT","DISTRACTIBLE","DISTURBING","DOGMATIC","DOMINEERING","DULL","EASILY DISCOURAGED","EGOCENTRIC","ENERVATED","ENVIOUS","ERRATIC","ESCAPIST","EXCITABLE","EXPEDIENT","EXTRAVAGANT","EXTREME","FAITHLESS","FANATICAL","FANCIFUL","FATALISTIC","FAWNING","FEARFUL","FICKLE","FIERY","FIXED","FLAMBOYANT","FOOLISH","FORGETFUL","FRAUDULENT","FRIGHTENING","FRIVOLOUS","GLOOMY","GRACELESS","GRAND","GREEDY","GRIM","GULLIBLE","HATEFUL","HAUGHTY","HEDONISTIC","HESITANT","HIDEBOUND","HIGH-HANDED","HOSTILE","IGNORANT","IMITATIVE","IMPATIENT","IMPRACTICAL","IMPRUDENT","IMPULSIVE","INCONSIDERATE","INCURIOUS","INDECISIVE","INDULGENT","INERT","INHIBITED","INSECURE","INSENSITIVE","INSINCERE","INSULTING","INTOLERANT","IRASCIBLE","IRRATIONAL","IRRESPONSIBLE","IRRITABLE","LAZY","LIBIDINOUS","LOQUACIOUS","MALICIOUS","MANIPULATIVE","MANNERED","MANNERLESS","MAWKISH","MEALY MOUTHED","MECHANICAL","MEDDLESOME","MELANCHOLIC","MERETRICIOUS","MESSY","MISERABLE","MISERLY","MISGUIDED","MISTAKEN","MONEY-MINDED","MONSTROUS","MOODY","MORBID","MUDDLE-HEADED","NAIVE","NARCISSISTIC","NARROW","NARROW-MINDED","NATTY","NEGATIVISTIC","NEGLECTFUL","NEUROTIC","NIHILISTIC","OBNOXIOUS","OBSESSIVE","OBVIOUS","ODD","OFFHAND","ONE-DIMENSIONAL","ONE-SIDED","OPINIONATED","OPPORTUNISTIC","OPPRESSED","OUTRAGEOUS","OVER IMAGINATIVE","PARANOID","PASSIVE","PEDANTIC","PERVERSE","PETTY","PHARISAICAL","PHLEGMATIC","PLODDING","POMPOUS","POSSESSIVE","POWER-HUNGRY","PREDATORY","PREJUDICED","PRESUMPTUOUS","PRETENTIOUS","PRIM","PROCRASTINATING","PROFLIGATE","PROVOCATIVE","PUGNACIOUS","PURITANICAL","QUIRKY","REACTIONARY","REACTIVE","REGIMENTAL","REGRETFUL","REPENTANT","REPRESSED","RESENTFUL","RIDICULOUS","RIGID","RITUALISTIC","ROWDY","RUINED","SADISTIC","SANCTIMONIOUS","SCHEMING","SCORNFUL","SECRETIVE","SEDENTARY","SELF-INDULGENT","SELFISH","SHALLOW","SHORTSIGHTED","SHY","SILLY","SINGLE-MINDED","SLOPPY","SLOW","SLY","SMALL-THINKING","SOFT HEADED","SORDID","STEELY","STIFF","STRONG-WILLED","STUBBORN","STUPID","SUBMISSIVE","SUPERFICIAL","SUPERSTITIOUS","SUSPICIOUS","TACTLESS","TASTELESS","TENSE","TEST123","THIEVISH","THOUGHTLESS","TIMID","TRANSPARENT","TREACHEROUS","TRENDY","TROUBLESOME","UNAPPRECIATIVE","UNCARING","UNCHARITABLE","UNCONVINCING","UNCOOPERATIVE","UNCREATIVE","UNCRITICAL","UNCTUOUS","UNDISCIPLINED","UNFRIENDLY","UNGRATEFUL","UNHEALTHY","UNIMAGINATIVE","UNIMPRESSIVE","UNLOVABLE","UNPOLISHED","UNPREDICTABLE","UNPRINCIPLED","UNREALISTIC","UNREFLECTIVE","UNRELIABLE","UNRESTRAINED","UNSELF-CRITICAL","UNSTABLE","VACUOUS","VAGUE","VENAL","VENOMOUS","VINDICTIVE","VULNERABLE","WEAK","WEAK-WILLED","WELL-MEANING","WILLFUL","WISHFUL","ZANY"];
export const neutral_traitsOptions: string[] = ["ABSENTMINDED","AGGRESSIVE","AMBITIOUS","AMUSING","ARTFUL","ASCETIC","AUTHORITARIAN","BIG-THINKING","CHUMMY","CIRCUMSPECT","COMPETITIVE","COMPLEX","CONFIDENTIAL","CONSERVATIVE","CONTRADICTORY","CRISP","CUTE","DECEPTIVE","DETERMINED","DOMINATING","DREAMY","DRIVING","DROLL","DRY","EARTHY","EFFEMINATE","EMOTIONAL","ENIGMATIC","EXPERIMENTAL","FAMILIAL","FOLKSY","FORMAL","FREEWHEELING","FRUGAL","GLAMOROUS","GUILELESS","HIGH-SPIRITED","HURIED","HYPNOTIC","ICONOCLASTIC","IDIOSYNCRATIC","IMPASSIVE","IMPERSONAL","IMPRESSIONABLE","INTENSE","INVISIBLE","IRRELIGIOUS","IRREVERENT","MATERNAL","MELLOW","MODERN","MORALISTIC","MYSTICAL","NEUTRAL","NONCOMMITTAL","NONCOMPETITIVE","OBEDIENT","OLD-FASHIONED","ORDINARY","OUTSPOKEN","PATERNALISTIC","PHYSICAL","PLACID","POLITICAL","PREDICTABLE","PREOCCUPIED","PRIVATE","PROGRESSIVE","PROUD","PURE","QUESTIONING","QUIET","RELIGIOUS","RESERVED","RESTRAINED","RETIRING","SARCASTIC","SELF-CONSCIOUS","SENSUAL","SKEPTICAL","SMOOTH","SOFT","SOLEMN","SOLITARY","STERN","STOLID","STRICT","STUBBORN","STYLISH","SUBJECTIVE","SURPRISING","TOUGH","UNAGGRESSIVE","UNAMBITIOUS","UNCEREMONIOUS","UNCHANGING","UNDEMANDING","UNFATHOMABLE","UNHURRIED","UNINHIBITED","UNPATRIOTIC","UNPREDICTABLE","UNRELIGIOUS","UNSENTIMENTAL","WHIMSICAL"];
export const occupationOptions: string[] = ["Abbot/abbess","Abecedarian","Abjurer","Acater","Accoucheur/obstetrician/midwife","Accountant","Accoutrements/coinsmith","Acolyte","Acrobat","Actor","Actuary","Acupuncturist","Administrator","Admiral","Adventurer","Advertising Executive","Aerialist/trapezist","Affeeror","Agister","Air Traffic Controller","Aircraft Engineer","Alchemist","Alderman","Alienist","Almoner","Anaesthetist","Animal Breeder","Animal Collector/monster Collector","Animal/monster Handler","Anthropologist","Antique Dealer","Apothecary","Appraiser","Apprentice","Arborist","Archaeologist","Archbishop","Architect","Archivist","Archmage","Armorer","Aromatherapist","Arranger","Art Critic","Art Dealer","Art Historian","Art Therapist","Artificer","Artist","Arts / Artists / Artistic","Assassin","Assay Master","Assayer","Assembly Line Worker","Assistant","Astrologer","Astronomer","Athlete","Au Pair","Auctioneer","Auditor","Author","Baggage Handler","Bagnio Keeper","Bailiff","Baker","Baler","Bandit","Bank Clerk","Bank Manager","Banker","Bar Staff","Barber","Bard","Barkeep","Barmaid/barboy","Baron/baroness","Barrister","Beekeeper","Beggar/pauper","Billboard Poster","Biochemist","Biologist","Bishop","Blacksmith","Bladesmith","Blood Hunter/monster Hunter","Bloodletter","Boat Builder","Boatman","Bodyguard","Bone Oracle","Bookbinder","Bookkeeper","Bookmaker","Bosun","Botanist","Bottler","Bouncer","Bounty Hunter","Bowyer","Breeder","Brewer","Brewery Worker","Brick Mason / Bricklayer / Mason","Bricklayer","Brickmaker","Broadcaster","Broom Maker","Brothel Keeper","Bug Catcher","Builder","Building Labourer","Burglar","Bus Driver","Business Consultant","Business Owner","Busker/street Musician","Butcher","Butler","Cabbie/wagoner","Cabin Boy/cabin Girl","Cabin Crew","Cabinet Maker","Calligraphist","Camera Operator","Candlemaker","Cantor","Captain","Car Dealer","Car Wash Attendant","Caravaneer","Cardinal","Care Assistant","Career Criminal","Careers Advisor","Caregiver","Caretaker","Carpenter","Carpet Fitter","Carter","Cartographer","Cartoonist","Cartwright","Cashier","Castellan","Casual Worker","Catering Staff","Cavalryman/cavalier","Celebrity","Cemetery Worker","Ceo","Chancellor","Chandler","Chaplain","Charcoal Maker","Charioteer","Charlatan/conman","Chatelaine/majordomo","Chauffeur","Chef","Chef Or Cook","Chemist","Chief","Childcare Worker","Childminder","Childrens Entertainer","Chimney Sweep","Chimney Sweeper","Chiropodist","Chiropractor","Choirmaster","Choreographer","Circus Worker","City Watch","Civil Servant","Clairvoyant","Cleaner","Clergyman","Cleric","Clerical Assistant","Clerk","Clockmaker","Clown","Coastguard","Cobbler","Cockfighter/game Fighter","Collector","Comedian","Commissar","Community Worker","Company Director","Composer","Composer Or Songwriter","Computer Analyst","Computer Engineer","Computer Programmer","Con Artist","Conductor","Confessor","Conjuror","Conservationist","Constable","Construction Worker","Contortionist","Cook","Cooper/hooper","Copyist","Coroner","Costume Designer","Costumer","Councillor","Counsellor","Count/earl/countess","Courier","Courtier","Cowherd","Craftsperson","Crane Driver","Crematorium Worker","Crime","Crime Boss","Crossing Sweeper","Croupier","Crown Prosecutor","Cult Leader","Cultist","Curator","Customs Officer","Cutler","Cutpurse","Dairy Boy/dairymaid","Dancer","Data Processor","Deacon","Dean","Debt Collector","Decorator","Deity","Delivery Driver","Dental Hygienist","Dental Nurse","Dentist","Deserter","Designer","Detective/investigator","Dietician","Diplomat","Director","Disc Jockey","Disgraced Noble","Diver","Diviner","Doctor","Doctor/physician","Domestic Staff","Doorman","Drakologist","Draper","Dressmaker","Driving Instructor","Drug Dealer","Drug Lord","Druid","Drummer/fifer","Drunkard","Duelist","Duke/duchess","Dungeon Delver","Dyer","Economist","Editor","Elder","Electrician","Elementalist","Embalmer","Embroiderer","Emperor/empress","Enchanter/enchantress","Engineer","Engraver","Entomologist","Entrepreneur"];
