// Auto-generated file - do not edit manually
// Generated from: dropdown_options table in database
// This file is a FALLBACK - the database is the primary source of truth
// The useDropdownOptions hook fetches from database first, then falls back to this file
// Run: npx tsx scripts/utilities/generate-dropdown-options.ts
// Last generated: 2025-12-17T14:24:35.698Z

export const csvOptions: Record<string, string[]> = {
  "accent": [
    "Boston",
    "Brazilian Portuguese",
    "Californian",
    "Canadian",
    "Caribbean",
    "Chicago",
    "Chicano English (Mexican-American)",
    "Chinese",
    "DEVELOPMENT",
    "Dutch",
    "German",
    "Greek",
    "Hawaiian Pidgin",
    "Indian",
    "Jamaican",
    "Japanese",
    "Korean",
    "Midwestern",
    "Minnesotan",
    "New Orleans (cajun)",
    "New York",
    "New Zealand",
    "Pacific Northwest",
    "Philadelphia",
    "Polish",
    "Russian",
    "South African",
    "Southern Appalachian",
    "Southern Californian (SoCal)",
    "Texan",
    "Turkish",
    "Valley (California)",
    "Welsh"
  ],
  "ethnicity_race": [
    "African",
    "African Descent",
    "Afro-Caribbean",
    "Afro-Latinx",
    "Arab",
    "Armenian",
    "Ashkenazi Jewish",
    "Asian",
    "Asian Descent",
    "Australian Aboriginal",
    "Basque",
    "Bengali",
    "Berber",
    "Bhutanese",
    "Brazilian",
    "Burmese",
    "Cambodian",
    "Caribbean",
    "Caucasian",
    "Caucasian / Pacific Islander",
    "Chicano",
    "Chinese",
    "Creole",
    "Cuban",
    "Dominican",
    "Druze",
    "Eastern European",
    "Egyptian",
    "Ethiopian",
    "Finnish",
    "First Nations",
    "French",
    "German",
    "German Descent",
    "Gerudo / Sheikah",
    "Ghanaian",
    "Greek Descent",
    "Guatemalan",
    "Haitian",
    "Hmong",
    "Hylian",
    "Icelandic",
    "Igbo",
    "Indigenous Australian",
    "Indigenous Canadian",
    "Inuit",
    "Iranian",
    "Iraqi",
    "Israeli",
    "Italian",
    "Italian/Chinese",
    "Japanese",
    "Japanese/British",
    "Jewish",
    "Kazakh",
    "Korean",
    "Kurdish",
    "Latinx",
    "Lebanese",
    "Lithuanian",
    "Lithuanian / Romanian",
    "Lithuanian/Mediterranean/French/Arabian",
    "Lithuanian/Romanian/French/Arabian",
    "Maori",
    "Mayan",
    "Mediterranean",
    "Mediterranean Caucasian Mix",
    "Mediterranean Descent",
    "Meowth",
    "Mestizo",
    "Mexican",
    "Mexican-American",
    "Middle Eastern",
    "Mongolian",
    "Moravian",
    "Nigerian",
    "Pacific Islander",
    "Palestinian",
    "Pashtun",
    "Persian",
    "Polynesian Descent",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Roma",
    "Romanian",
    "Russian",
    "Samoan",
    "Sardinian",
    "Scandinavian",
    "Scanner",
    "Sephardic Jewish",
    "Sicilian",
    "Somali",
    "South Asian",
    "Southeast Asian",
    "Swahili",
    "Syrian",
    "Tibetan",
    "Tlingit",
    "Tongan",
    "Turkish",
    "Uyghur",
    "Venezuelan",
    "Vietnamese",
    "West African",
    "White",
    "Yoruba"
  ],
  "eye_color": [
    "Ash",
    "Azure",
    "Black",
    "Black/Silver",
    "Black; Ash",
    "Black; Black/Silver",
    "Black; Charcoal",
    "Black; Jet",
    "Black; Midnight",
    "Black; Obsidian",
    "Black; Onyx",
    "Black; Raven",
    "Black; Soft",
    "Blonde; Ash",
    "Blonde; Beige",
    "Blonde; Butter",
    "Blonde; Champagne",
    "Blonde; Cream",
    "Blonde; Dark",
    "Blonde; Frosted",
    "Blonde; Golden",
    "Blonde; Honey",
    "Blonde; Lemon",
    "Blonde; Light",
    "Blonde; Medium",
    "Blonde; Neutral",
    "Blonde; Platinum",
    "Blonde; Sandy",
    "Blonde; Silver",
    "Blonde; Sunflower",
    "Blonde; Vanilla",
    "Blonde; White",
    "Blood",
    "Blue",
    "Blue; Aqua",
    "Blue; Azure",
    "Blue; Baby",
    "Blue; Cerulean",
    "Blue; Cobalt",
    "Blue; Cyan",
    "Blue; Dark",
    "Blue; Deep",
    "Blue; Denim",
    "Blue; Ice",
    "Blue; Indigo",
    "Blue; Light",
    "Blue; Midnight",
    "Blue; Navy",
    "Blue; Pale",
    "Blue; Royal",
    "Blue; Sapphire",
    "Blue; Sky",
    "Blue; Slate",
    "Blue; Soft",
    "Blue; Steel",
    "Blue; Storm",
    "Blue; Teal",
    "Blue; Turquoise",
    "Blue; Ultramarine",
    "Brown",
    "Brown; Auburn",
    "Brown; Caramel",
    "Brown; Chestnut",
    "Brown; Chocolate",
    "Brown; Coffee",
    "Brown; Cool",
    "Brown; Copper",
    "Brown; Dark",
    "Brown; Dark Mahogany",
    "Brown; Espresso",
    "Brown; Hazel",
    "Brown; Light",
    "Brown; Mahogany",
    "Brown; Medium",
    "Brown; Mocha",
    "Brown; Neutral",
    "Brown; Rose",
    "Brown; Sandy",
    "Brown; Sepia",
    "Brown; Soft Copper",
    "Brown; Tawny",
    "Brown; Walnut",
    "Brown; Warm",
    "Bubblegum",
    "Burnt",
    "Cardinal",
    "Carmine",
    "Coral",
    "Crimson",
    "Deep",
    "Espresso",
    "Gold",
    "Gold; Amber",
    "Gold; Bright",
    "Gold; Dark",
    "Gold; Honey",
    "Gold; Light",
    "Gold; Metallic",
    "Gold; Soft",
    "Gold; Warm",
    "Gray",
    "Gray; Ash",
    "Gray; Charcoal",
    "Gray; Cool",
    "Gray; Dark",
    "Gray; Gunmetal",
    "Gray; Light",
    "Gray; Metallic",
    "Gray; Pale",
    "Gray; Pearl",
    "Gray; Platinum",
    "Gray; Slate",
    "Gray; Smoke",
    "Gray; Smoky",
    "Gray; Soft",
    "Gray; Steel",
    "Gray; Warm",
    "Green",
    "Green/Pink",
    "Green; Aquatic",
    "Green; Chartreuse",
    "Green; Cool",
    "Green; Dark",
    "Green; Emerald",
    "Green; Fern",
    "Green; Forest",
    "Green; Jade",
    "Green; Kelly",
    "Green; Light",
    "Green; Lime",
    "Green; Mint",
    "Green; Neon",
    "Green; Olive",
    "Green; Pale",
    "Green; Peacock",
    "Green; Pistachio",
    "Green; Sage",
    "Green; Sea",
    "Green; Soft",
    "Green; Warm",
    "Heterochromia; Central",
    "Heterochromia; L Blue / R Brown",
    "Heterochromia; L Blue / R Green",
    "Heterochromia; L Brown / R Blue",
    "Heterochromia; L Brown / R Green",
    "Heterochromia; L Gold / R Blue",
    "Heterochromia; L Gold / R Brown",
    "Heterochromia; L Gold / R Green",
    "Heterochromia; L Gray / R Blue",
    "Heterochromia; L Gray / R Brown",
    "Heterochromia; L Gray / R Green",
    "Heterochromia; L Green / R Blue",
    "Heterochromia; L Green / R Brown",
    "Heterochromia; L Hazel / R Blue",
    "Heterochromia; L Hazel / R Green",
    "Heterochromia; Sectoral",
    "Ice",
    "Indigo",
    "Lemon",
    "Light",
    "Lilac",
    "Lime",
    "Multi",
    "Orange",
    "Orange; Apricot",
    "Orange; Burnt",
    "Orange; Dark",
    "Orange; Light",
    "Orange; Peach",
    "Orange; Pumpkin",
    "Orange; Rust",
    "Orange; Sunset",
    "Orange; Tangerine",
    "Orange; Vermilion",
    "Orange; Warm",
    "Pink",
    "Pink; Baby",
    "Pink; Blush",
    "Pink; Bubblegum",
    "Pink; Candy",
    "Pink; Coral",
    "Pink; Dark",
    "Pink; Dusty",
    "Pink; Dusty Rose",
    "Pink; Fuchsia",
    "Pink; Hot",
    "Pink; Light",
    "Pink; Magenta",
    "Pink; Neon",
    "Pink; Pastel",
    "Pink; Peach",
    "Pink; Rose",
    "Pink; Salmon",
    "Pink; Soft",
    "Purple",
    "Purple; Amethyst",
    "Purple; Dark",
    "Purple; Deep",
    "Purple; Eggplant",
    "Purple; Grape",
    "Purple; Indigo",
    "Purple; Lavender",
    "Purple; Light",
    "Purple; Lilac",
    "Purple; Magenta",
    "Purple; Mauve",
    "Purple; Mulberry",
    "Purple; Orchid",
    "Purple; Periwinkle",
    "Purple; Plum",
    "Purple; Raspberry",
    "Purple; Soft",
    "Purple; Soft Lavender",
    "Purple; Violet",
    "Red",
    "Red; Auburn",
    "Red; Blood",
    "Red; Burgundy",
    "Red; Burnt Copper",
    "Red; Carmine",
    "Red; Cherry",
    "Red; Cool",
    "Red; Copper",
    "Red; Crimson",
    "Red; Dark",
    "Red; Deep Copper",
    "Red; Fire",
    "Red; Ginger",
    "Red; Light",
    "Red; Raspberry",
    "Red; Ruby",
    "Red; Scarlet",
    "Red; Strawberry Blonde",
    "Red; Warm",
    "Red; Wine",
    "Silver; Ash",
    "Silver; Dark",
    "Silver; Ice",
    "Silver; Light",
    "Silver; Metallic",
    "Silver; Platinum",
    "Silver; Soft",
    "Silver; Steel",
    "Silver; White",
    "White; Beige",
    "White; Cool",
    "White; Cream",
    "White; Frost",
    "White; Ghost",
    "White; Ice",
    "White; Ivory",
    "White; Pearl",
    "White; Pure",
    "White; Snow",
    "White; Soft",
    "White; Warm",
    "Yellow",
    "Yellow; Canary",
    "Yellow; Dark",
    "Yellow; Lemon",
    "Yellow; Light",
    "Yellow; Mustard",
    "Yellow; Saffron"
  ],
  "gender_identity": [
    "Agender",
    "Androgynous",
    "Bigender",
    "Cisgender",
    "Demiboy",
    "Demigirl",
    "Genderfluid",
    "Genderqueer",
    "Intersex",
    "Neutrois",
    "Non-binary",
    "Pangender",
    "Third Gender",
    "Transgender",
    "Two-spirit"
  ],
  "hair_color": [
    "Ash",
    "Baby",
    "Beige",
    "Black",
    "Black/Silver",
    "Black; Ash",
    "Black; Black/Silver",
    "Black; Charcoal",
    "Black; Jet",
    "Black; Midnight",
    "Black; Obsidian",
    "Black; Onyx",
    "Black; Raven",
    "Black; Soft",
    "Blonde",
    "Blonde; Ash",
    "Blonde; Beige",
    "Blonde; Butter",
    "Blonde; Champagne",
    "Blonde; Cream",
    "Blonde; Dark",
    "Blonde; Frosted",
    "Blonde; Golden",
    "Blonde; Honey",
    "Blonde; Lemon",
    "Blonde; Light",
    "Blonde; Medium",
    "Blonde; Neutral",
    "Blonde; Platinum",
    "Blonde; Sandy",
    "Blonde; Silver",
    "Blonde; Sunflower",
    "Blonde; Vanilla",
    "Blonde; White",
    "Blue",
    "Blue; Aqua",
    "Blue; Azure",
    "Blue; Baby",
    "Blue; Cerulean",
    "Blue; Cobalt",
    "Blue; Cyan",
    "Blue; Dark",
    "Blue; Deep",
    "Blue; Denim",
    "Blue; Ice",
    "Blue; Indigo",
    "Blue; Light",
    "Blue; Midnight",
    "Blue; Navy",
    "Blue; Pale",
    "Blue; Royal",
    "Blue; Sapphire",
    "Blue; Sky",
    "Blue; Slate",
    "Blue; Soft",
    "Blue; Steel",
    "Blue; Storm",
    "Blue; Teal",
    "Blue; Turquoise",
    "Blue; Ultramarine",
    "Brown",
    "Brown; Auburn",
    "Brown; Caramel",
    "Brown; Chestnut",
    "Brown; Chocolate",
    "Brown; Coffee",
    "Brown; Cool",
    "Brown; Copper",
    "Brown; Dark",
    "Brown; Dark Mahogany",
    "Brown; Espresso",
    "Brown; Hazel",
    "Brown; Light",
    "Brown; Mahogany",
    "Brown; Medium",
    "Brown; Mocha",
    "Brown; Neutral",
    "Brown; Rose",
    "Brown; Sandy",
    "Brown; Sepia",
    "Brown; Soft Copper",
    "Brown; Tawny",
    "Brown; Walnut",
    "Brown; Warm",
    "Cobalt",
    "Cool",
    "Dark",
    "Dusty",
    "Dusty Rose",
    "Fern",
    "Gold; Amber",
    "Gold; Bright",
    "Gold; Dark",
    "Gold; Honey",
    "Gold; Light",
    "Gold; Metallic",
    "Gold; Soft",
    "Gold; Warm",
    "Gray",
    "Gray; Ash",
    "Gray; Charcoal",
    "Gray; Cool",
    "Gray; Dark",
    "Gray; Gunmetal",
    "Gray; Light",
    "Gray; Metallic",
    "Gray; Pale",
    "Gray; Pearl",
    "Gray; Platinum",
    "Gray; Slate",
    "Gray; Smoke",
    "Gray; Smoky",
    "Gray; Soft",
    "Gray; Steel",
    "Gray; Warm",
    "Green",
    "Green; Aquatic",
    "Green; Chartreuse",
    "Green; Cool",
    "Green; Dark",
    "Green; Emerald",
    "Green; Fern",
    "Green; Forest",
    "Green; Jade",
    "Green; Kelly",
    "Green; Light",
    "Green; Lime",
    "Green; Mint",
    "Green; Neon",
    "Green; Olive",
    "Green; Pale",
    "Green; Peacock",
    "Green; Pistachio",
    "Green; Sage",
    "Green; Sea",
    "Green; Soft",
    "Green; Warm",
    "Heterochromia; Central",
    "Heterochromia; L Blue / R Brown",
    "Heterochromia; L Blue / R Green",
    "Heterochromia; L Brown / R Blue",
    "Heterochromia; L Brown / R Green",
    "Heterochromia; L Gold / R Blue",
    "Heterochromia; L Gold / R Brown",
    "Heterochromia; L Gold / R Green",
    "Heterochromia; L Gray / R Blue",
    "Heterochromia; L Gray / R Brown",
    "Heterochromia; L Gray / R Green",
    "Heterochromia; L Green / R Blue",
    "Heterochromia; L Green / R Brown",
    "Heterochromia; L Hazel / R Blue",
    "Heterochromia; L Hazel / R Green",
    "Heterochromia; Sectoral",
    "Jade",
    "Medium",
    "Neutral",
    "Olive",
    "Orange",
    "Orange; Apricot",
    "Orange; Burnt",
    "Orange; Dark",
    "Orange; Light",
    "Orange; Peach",
    "Orange; Pumpkin",
    "Orange; Rust",
    "Orange; Sunset",
    "Orange; Tangerine",
    "Orange; Vermilion",
    "Orange; Warm",
    "Pink",
    "Pink; Baby",
    "Pink; Blush",
    "Pink; Bubblegum",
    "Pink; Candy",
    "Pink; Coral",
    "Pink; Dark",
    "Pink; Dusty",
    "Pink; Dusty Rose",
    "Pink; Fuchsia",
    "Pink; Hot",
    "Pink; Light",
    "Pink; Magenta",
    "Pink; Neon",
    "Pink; Pastel",
    "Pink; Peach",
    "Pink; Rose",
    "Pink; Salmon",
    "Pink; Soft",
    "Pumpkin",
    "Purple",
    "Purple; Amethyst",
    "Purple; Dark",
    "Purple; Deep",
    "Purple; Eggplant",
    "Purple; Grape",
    "Purple; Indigo",
    "Purple; Lavender",
    "Purple; Light",
    "Purple; Lilac",
    "Purple; Magenta",
    "Purple; Mauve",
    "Purple; Mulberry",
    "Purple; Orchid",
    "Purple; Periwinkle",
    "Purple; Plum",
    "Purple; Raspberry",
    "Purple; Soft",
    "Purple; Soft Lavender",
    "Purple; Violet",
    "Red; Auburn",
    "Red; Blood",
    "Red; Burgundy",
    "Red; Burnt Copper",
    "Red; Carmine",
    "Red; Cherry",
    "Red; Cool",
    "Red; Copper",
    "Red; Crimson",
    "Red; Dark",
    "Red; Deep Copper",
    "Red; Fire",
    "Red; Ginger",
    "Red; Light",
    "Red; Raspberry",
    "Red; Ruby",
    "Red; Scarlet",
    "Red; Strawberry Blonde",
    "Red; Warm",
    "Red; Wine",
    "Silver",
    "Silver; Ash",
    "Silver; Dark",
    "Silver; Ice",
    "Silver; Light",
    "Silver; Metallic",
    "Silver; Platinum",
    "Silver; Soft",
    "Silver; Steel",
    "Silver; White",
    "Soft",
    "Tawny",
    "White",
    "White; Beige",
    "White; Cool",
    "White; Cream",
    "White; Frost",
    "White; Ghost",
    "White; Ice",
    "White; Ivory",
    "White; Pearl",
    "White; Pure",
    "White; Snow",
    "White; Soft",
    "White; Warm",
    "Yellow; Canary",
    "Yellow; Dark",
    "Yellow; Lemon",
    "Yellow; Light",
    "Yellow; Mustard",
    "Yellow; Saffron"
  ],
  "mbti": [
    "ENFJ",
    "ENFP",
    "ENTJ",
    "ENTP",
    "ESFJ",
    "ESFP",
    "ESTJ",
    "ESTP",
    "INFJ",
    "INFP",
    "INTJ",
    "INTP",
    "ISFJ",
    "ISFP",
    "ISTJ",
    "ISTP"
  ],
  "moral": [
    "Chaotic Evil",
    "Chaotic Good",
    "Chaotic Neutral",
    "Lawful Evil",
    "Lawful Good",
    "Lawful Neutral",
    "Neutral Evil",
    "Neutral Good",
    "True Neutral"
  ],
  "nationality": [
    "Afghan",
    "American",
    "Argentine",
    "Australian",
    "Austrian",
    "Bangladeshi",
    "Belgian",
    "Bosnian",
    "Brazilian",
    "British",
    "Bulgarian",
    "Canadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Czech",
    "Danish",
    "Dominican",
    "Dutch",
    "Egyptian",
    "Emirati",
    "Ethiopian",
    "Filipino",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Haitian",
    "Hungarian",
    "Icelandic",
    "Inariko",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kenyan",
    "Konohagakure",
    "Korean",
    "Lebanese",
    "Malaysian",
    "Mexican",
    "Mongolian",
    "Moroccan",
    "New Zealander (Kiwi)",
    "Nigerian",
    "Norwegian",
    "Pakistani",
    "Palestinian",
    "Panamanian",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Rudania",
    "Russian",
    "Saudi Arabian",
    "Scottish",
    "Serbian",
    "Singaporean",
    "South African",
    "Spanish",
    "Sri Lankan",
    "Sun Empire",
    "Sunagakure",
    "Swedish",
    "Swiss",
    "Syrian",
    "Thai",
    "Trinidadian",
    "Turkish",
    "Ukrainian",
    "Venezuelan",
    "Vhintl",
    "Vietnamese",
    "Welsh"
  ],
  "negative_traits": [
    "ABRASIVE",
    "ABRUPT",
    "AGONIZING",
    "AIMLESS",
    "AIRY",
    "ALOOF",
    "AMORAL",
    "ANGRY",
    "ASOCIAL",
    "ASSERTIVE",
    "ASTIGMATIC",
    "BARBARIC",
    "BEWILDERED",
    "BIZARRE",
    "BLAND",
    "BLUNT",
    "BOISTEROUS",
    "BRITTLE",
    "BRUTAL",
    "CALCULATING",
    "CALLOUS",
    "CANTANKEROUS",
    "CARELESS",
    "CAUTIOUS",
    "CHARMLESS",
    "CHILDISH",
    "CLUMSY",
    "COARSE",
    "COLD",
    "COLORLESS",
    "COMPLACENT",
    "COMPLAINTIVE",
    "COMPULSIVE",
    "CONCEITED",
    "CONDEMNATORY",
    "CONFORMIST",
    "CONFUSED",
    "CONTEMPTIBLE",
    "CONVENTIONAL",
    "COWARDLY",
    "CRAFTY",
    "CRASS",
    "CRAZY",
    "CRIMINAL",
    "CRITICAL",
    "CRUDE",
    "CRUEL",
    "CYNICAL",
    "DECADENT",
    "DECEITFUL",
    "DELICATE",
    "DEMANDING",
    "DEPENDENT",
    "DESPERATE",
    "DESTRUCTIVE",
    "DEVIOUS",
    "DIFFICULT",
    "DIRTY",
    "DISCONCERTING",
    "DISCONTENTED",
    "DISCOURAGING",
    "DISCOURTEOUS",
    "DISHONEST",
    "DISLOYAL",
    "DISOBEDIENT",
    "DISORDERLY",
    "DISORGANIZED",
    "DISPUTATIOUS",
    "DISRESPECTFUL",
    "DISRUPTIVE",
    "DISSOLUTE",
    "DISSONANT",
    "DISTRACTIBLE",
    "DISTURBING",
    "DOGMATIC",
    "DOMINEERING",
    "DULL",
    "EASILY DISCOURAGED",
    "EGOCENTRIC",
    "ENERVATED",
    "ENVIOUS",
    "ERRATIC",
    "ESCAPIST",
    "EXCITABLE",
    "EXPEDIENT",
    "EXTRAVAGANT",
    "EXTREME",
    "FAITHLESS",
    "FANATICAL",
    "FANCIFUL",
    "FATALISTIC",
    "FAWNING",
    "FEARFUL",
    "FICKLE",
    "FIERY",
    "FIXED",
    "FLAMBOYANT",
    "FOOLISH",
    "FORGETFUL",
    "FRAUDULENT",
    "FRIGHTENING",
    "FRIVOLOUS",
    "GLOOMY",
    "GRACELESS",
    "GRAND",
    "GREEDY",
    "GRIM",
    "GULLIBLE",
    "HATEFUL",
    "HAUGHTY",
    "HEDONISTIC",
    "HESITANT",
    "HIDEBOUND",
    "HIGH-HANDED",
    "HOSTILE",
    "IGNORANT",
    "IMITATIVE",
    "IMPATIENT",
    "IMPRACTICAL",
    "IMPRUDENT",
    "IMPULSIVE",
    "INCONSIDERATE",
    "INCURIOUS",
    "INDECISIVE",
    "INDULGENT",
    "INERT",
    "INHIBITED",
    "INSECURE",
    "INSENSITIVE",
    "INSINCERE",
    "INSULTING",
    "INTOLERANT",
    "IRASCIBLE",
    "IRRATIONAL",
    "IRRESPONSIBLE",
    "IRRITABLE",
    "LAZY",
    "LIBIDINOUS",
    "LOQUACIOUS",
    "MALICIOUS",
    "MANIPULATIVE",
    "MANNERED",
    "MANNERLESS",
    "MAWKISH",
    "MEALY MOUTHED",
    "MECHANICAL",
    "MEDDLESOME",
    "MELANCHOLIC",
    "MERETRICIOUS",
    "MESSY",
    "MISERABLE",
    "MISERLY",
    "MISGUIDED",
    "MISTAKEN",
    "MONEY-MINDED",
    "MONSTROUS",
    "MOODY",
    "MORBID",
    "MUDDLE-HEADED",
    "NAIVE",
    "NARCISSISTIC",
    "NARROW",
    "NARROW-MINDED",
    "NATTY",
    "NEGATIVISTIC",
    "NEGLECTFUL",
    "NEUROTIC",
    "NIHILISTIC",
    "OBNOXIOUS",
    "OBSESSIVE",
    "OBVIOUS",
    "ODD",
    "OFFHAND",
    "ONE-DIMENSIONAL",
    "ONE-SIDED",
    "OPINIONATED",
    "OPPORTUNISTIC",
    "OPPRESSED",
    "OUTRAGEOUS",
    "OVER IMAGINATIVE",
    "PARANOID",
    "PASSIVE",
    "PEDANTIC",
    "PERVERSE",
    "PETTY",
    "PHARISAICAL",
    "PHLEGMATIC",
    "PLODDING",
    "POMPOUS",
    "POSSESSIVE",
    "POWER-HUNGRY",
    "PREDATORY",
    "PREJUDICED",
    "PRESUMPTUOUS",
    "PRETENTIOUS",
    "PRIM",
    "PROCRASTINATING",
    "PROFLIGATE",
    "PROVOCATIVE",
    "PUGNACIOUS",
    "PURITANICAL",
    "QUIRKY",
    "REACTIONARY",
    "REACTIVE",
    "REGIMENTAL",
    "REGRETFUL",
    "REPENTANT",
    "REPRESSED",
    "RESENTFUL",
    "RIDICULOUS",
    "RIGID",
    "RITUALISTIC"
  ]
};

// Hex codes for color options (field -> option -> hex_code)
export const colorHexCodes: Record<string, Record<string, string>> = {
  "eye_color": {
    "Black": "#3d2817",
    "Black; Ash": "#2a2a2a",
    "Black; Black/Silver": "#1a1a2a",
    "Black; Charcoal": "#1c1c1c",
    "Black; Jet": "#000000",
    "Black; Midnight": "#0d0d0d",
    "Black; Obsidian": "#0b0b0b",
    "Black; Onyx": "#0f0f0f",
    "Black; Raven": "#0a0a0a",
    "Black; Soft": "#1a1a1a",
    "Blonde; Ash": "#e6d3a3",
    "Blonde; Beige": "#f5f5dc",
    "Blonde; Butter": "#fff8dc",
    "Blonde; Champagne": "#f7e7ce",
    "Blonde; Cream": "#fffdd0",
    "Blonde; Dark": "#daa520",
    "Blonde; Frosted": "#e6e6fa",
    "Blonde; Golden": "#ffd700",
    "Blonde; Honey": "#f0c674",
    "Blonde; Lemon": "#fffacd",
    "Blonde; Light": "#faf0be",
    "Blonde; Medium": "#f5deb3",
    "Blonde; Neutral": "#f5deb3",
    "Blonde; Platinum": "#e5e4e2",
    "Blonde; Sandy": "#f4a460",
    "Blonde; Silver": "#c0c0c0",
    "Blonde; Sunflower": "#ffdb00",
    "Blonde; Vanilla": "#f3e5ab",
    "Blonde; White": "#faf0e6",
    "Blue; Aqua": "#00ffff",
    "Blue; Azure": "#007fff",
    "Blue; Baby": "#89cff0",
    "Blue; Cerulean": "#007ba7",
    "Blue; Cobalt": "#0047ab",
    "Blue; Cyan": "#00ffff",
    "Blue; Dark": "#00008b",
    "Blue; Deep": "#00008b",
    "Blue; Denim": "#1560bd",
    "Blue; Ice": "#b0e0e6",
    "Blue; Indigo": "#4b0082",
    "Blue; Light": "#add8e6",
    "Blue; Midnight": "#191970",
    "Blue; Navy": "#000080",
    "Blue; Pale": "#afeeee",
    "Blue; Royal": "#4169e1",
    "Blue; Sapphire": "#0f52ba",
    "Blue; Sky": "#87ceeb",
    "Blue; Slate": "#708090",
    "Blue; Soft": "#87ceeb",
    "Blue; Steel": "#4682b4",
    "Blue; Storm": "#4f6d7a",
    "Blue; Teal": "#008080",
    "Blue; Turquoise": "#40e0d0",
    "Blue; Ultramarine": "#120a8f",
    "Brown": "#8b4513",
    "Brown; Auburn": "#a52a2a",
    "Brown; Caramel": "#af6e4d",
    "Brown; Chestnut": "#954535",
    "Brown; Chocolate": "#7b3f00",
    "Brown; Coffee": "#6f4e37",
    "Brown; Cool": "#5c4033",
    "Brown; Copper": "#b87333",
    "Brown; Dark": "#3d2817",
    "Brown; Dark Mahogany": "#8b0000",
    "Brown; Espresso": "#3d2817",
    "Brown; Hazel": "#8b7355",
    "Brown; Light": "#a0826d",
    "Brown; Mahogany": "#c04000",
    "Brown; Medium": "#6b4423",
    "Brown; Mocha": "#6f4e37",
    "Brown; Neutral": "#6b4423",
    "Brown; Rose": "#8b5a5a",
    "Brown; Sandy": "#f4a460",
    "Brown; Sepia": "#704214",
    "Brown; Soft Copper": "#cd7f32",
    "Brown; Tawny": "#cd853f",
    "Brown; Walnut": "#5c4033",
    "Brown; Warm": "#8b4513",
    "Gold; Amber": "#ffbf00",
    "Gold; Bright": "#ffd700",
    "Gold; Dark": "#b8860b",
    "Gold; Honey": "#f0c674",
    "Gold; Light": "#ffd700",
    "Gold; Metallic": "#d4af37",
    "Gold; Soft": "#f4c430",
    "Gold; Warm": "#ffd700",
    "Gray; Ash": "#b2beb5",
    "Gray; Charcoal": "#36454f",
    "Gray; Cool": "#808080",
    "Gray; Dark": "#696969",
    "Gray; Gunmetal": "#2a3439",
    "Gray; Light": "#d3d3d3",
    "Gray; Metallic": "#8c8c8c",
    "Gray; Pale": "#d3d3d3",
    "Gray; Pearl": "#e8e0d9",
    "Gray; Platinum": "#e5e4e2",
    "Gray; Slate": "#708090",
    "Gray; Smoke": "#848484",
    "Gray; Smoky": "#848484",
    "Gray; Soft": "#c0c0c0",
    "Gray; Steel": "#4682b4",
    "Gray; Warm": "#a9a9a9",
    "Green; Aquatic": "#00ced1",
    "Green; Chartreuse": "#7fff00",
    "Green; Cool": "#2e8b57",
    "Green; Dark": "#006400",
    "Green; Emerald": "#50c878",
    "Green; Fern": "#4f7942",
    "Green; Forest": "#228b22",
    "Green; Jade": "#00a86b",
    "Green; Kelly": "#4cbb17",
    "Green; Light": "#90ee90",
    "Green; Lime": "#32cd32",
    "Green; Mint": "#98ff98",
    "Green; Neon": "#39ff14",
    "Green; Olive": "#808000",
    "Green; Pale": "#98fb98",
    "Green; Peacock": "#33a1c9",
    "Green; Pistachio": "#93c572",
    "Green; Sage": "#87ae73",
    "Green; Sea": "#2e8b57",
    "Green; Soft": "#90ee90",
    "Green; Warm": "#228b22",
    "Heterochromia; Central": "#808080",
    "Heterochromia; L Blue / R Brown": "#4169e1",
    "Heterochromia; L Blue / R Green": "#4169e1",
    "Heterochromia; L Brown / R Blue": "#8b4513",
    "Heterochromia; L Brown / R Green": "#8b4513",
    "Heterochromia; L Gold / R Blue": "#ffd700",
    "Heterochromia; L Gold / R Brown": "#ffd700",
    "Heterochromia; L Gold / R Green": "#ffd700",
    "Heterochromia; L Gray / R Blue": "#808080",
    "Heterochromia; L Gray / R Brown": "#808080",
    "Heterochromia; L Gray / R Green": "#808080",
    "Heterochromia; L Green / R Blue": "#228b22",
    "Heterochromia; L Green / R Brown": "#228b22",
    "Heterochromia; L Hazel / R Blue": "#8b7355",
    "Heterochromia; L Hazel / R Green": "#8b7355",
    "Heterochromia; Sectoral": "#808080",
    "Light": "#f5deb3",
    "Orange; Apricot": "#fbceb1",
    "Orange; Burnt": "#cc5500",
    "Orange; Dark": "#ff8c00",
    "Orange; Light": "#ffb347",
    "Orange; Peach": "#ffdab9",
    "Orange; Pumpkin": "#ff7518",
    "Orange; Rust": "#b7410e",
    "Orange; Sunset": "#fd5e53",
    "Orange; Tangerine": "#ffa500",
    "Orange; Vermilion": "#e34234",
    "Orange; Warm": "#ff7f50",
    "Pink; Baby": "#f4c2c2",
    "Pink; Blush": "#de5d83",
    "Pink; Bubblegum": "#ffc1cc",
    "Pink; Candy": "#ff1493",
    "Pink; Coral": "#ff7f50",
    "Pink; Dark": "#c71585",
    "Pink; Dusty": "#d4a5a5",
    "Pink; Dusty Rose": "#b76e79",
    "Pink; Fuchsia": "#ff00ff",
    "Pink; Hot": "#ff69b4",
    "Pink; Light": "#ffb6c1",
    "Pink; Magenta": "#ff00ff",
    "Pink; Neon": "#ff1493",
    "Pink; Pastel": "#ffb6c1",
    "Pink; Peach": "#ffdab9",
    "Pink; Rose": "#ff007f",
    "Pink; Salmon": "#fa8072",
    "Pink; Soft": "#ffb6c1",
    "Purple; Amethyst": "#9966cc",
    "Purple; Dark": "#4b0082",
    "Purple; Deep": "#4b0082",
    "Purple; Eggplant": "#614051",
    "Purple; Grape": "#6f2da8",
    "Purple; Indigo": "#4b0082",
    "Purple; Lavender": "#e6e6fa",
    "Purple; Light": "#d8bfd8",
    "Purple; Lilac": "#c8a2c8",
    "Purple; Magenta": "#ff00ff",
    "Purple; Mauve": "#e0b0ff",
    "Purple; Mulberry": "#c54b8c",
    "Purple; Orchid": "#da70d6",
    "Purple; Periwinkle": "#cc99ff",
    "Purple; Plum": "#dda0dd",
    "Purple; Raspberry": "#e30b5d",
    "Purple; Soft": "#d8bfd8",
    "Purple; Soft Lavender": "#e6e6fa",
    "Purple; Violet": "#8a2be2",
    "Red; Auburn": "#a52a2a",
    "Red; Blood": "#8b0000",
    "Red; Burgundy": "#800020",
    "Red; Burnt Copper": "#cc5500",
    "Red; Carmine": "#960018",
    "Red; Cherry": "#de3163",
    "Red; Cool": "#b22222",
    "Red; Copper": "#b87333",
    "Red; Crimson": "#dc143c",
    "Red; Dark": "#8b0000",
    "Red; Deep Copper": "#b87333",
    "Red; Fire": "#ff4500",
    "Red; Ginger": "#b06500",
    "Red; Light": "#ff6b6b",
    "Red; Raspberry": "#e30b5d",
    "Red; Ruby": "#e0115f",
    "Red; Scarlet": "#ff2400",
    "Red; Strawberry Blonde": "#ffdbcc",
    "Red; Warm": "#dc143c",
    "Red; Wine": "#722f37",
    "Silver; Ash": "#b2beb5",
    "Silver; Dark": "#808080",
    "Silver; Ice": "#b0e0e6",
    "Silver; Light": "#c0c0c0",
    "Silver; Metallic": "#aaa9ad",
    "Silver; Platinum": "#e5e4e2",
    "Silver; Soft": "#c9c0bb",
    "Silver; Steel": "#a8a8a8",
    "Silver; White": "#c0c0c0",
    "White; Beige": "#f5f5dc",
    "White; Cool": "#f0f8ff",
    "White; Cream": "#fffdd0",
    "White; Frost": "#e8f5e9",
    "White; Ghost": "#f8f8ff",
    "White; Ice": "#b0e0e6",
    "White; Ivory": "#fffff0",
    "White; Pearl": "#f8f6f0",
    "White; Pure": "#ffffff",
    "White; Snow": "#fffafa",
    "White; Soft": "#fafafa",
    "White; Warm": "#fdf5e6",
    "Yellow; Canary": "#ffef00",
    "Yellow; Dark": "#cccc00",
    "Yellow; Lemon": "#fff700",
    "Yellow; Light": "#ffff99",
    "Yellow; Mustard": "#ffdb58",
    "Yellow; Saffron": "#f4c430"
  },
  "hair_color": {
    "Black": "#3d2817",
    "Black; Ash": "#2a2a2a",
    "Black; Black/Silver": "#1a1a2a",
    "Black; Charcoal": "#1c1c1c",
    "Black; Jet": "#000000",
    "Black; Midnight": "#0d0d0d",
    "Black; Obsidian": "#0b0b0b",
    "Black; Onyx": "#0f0f0f",
    "Black; Raven": "#0a0a0a",
    "Black; Soft": "#1a1a1a",
    "Blonde; Ash": "#e6d3a3",
    "Blonde; Beige": "#f5f5dc",
    "Blonde; Butter": "#fff8dc",
    "Blonde; Champagne": "#f7e7ce",
    "Blonde; Cream": "#fffdd0",
    "Blonde; Dark": "#daa520",
    "Blonde; Frosted": "#e6e6fa",
    "Blonde; Golden": "#ffd700",
    "Blonde; Honey": "#f0c674",
    "Blonde; Lemon": "#fffacd",
    "Blonde; Light": "#faf0be",
    "Blonde; Medium": "#f5deb3",
    "Blonde; Neutral": "#f5deb3",
    "Blonde; Platinum": "#e5e4e2",
    "Blonde; Sandy": "#f4a460",
    "Blonde; Silver": "#c0c0c0",
    "Blonde; Sunflower": "#ffdb00",
    "Blonde; Vanilla": "#f3e5ab",
    "Blonde; White": "#faf0e6",
    "Blue; Aqua": "#00ffff",
    "Blue; Azure": "#007fff",
    "Blue; Baby": "#89cff0",
    "Blue; Cerulean": "#007ba7",
    "Blue; Cobalt": "#0047ab",
    "Blue; Cyan": "#00ffff",
    "Blue; Dark": "#00008b",
    "Blue; Deep": "#00008b",
    "Blue; Denim": "#1560bd",
    "Blue; Ice": "#b0e0e6",
    "Blue; Indigo": "#4b0082",
    "Blue; Light": "#add8e6",
    "Blue; Midnight": "#191970",
    "Blue; Navy": "#000080",
    "Blue; Pale": "#afeeee",
    "Blue; Royal": "#4169e1",
    "Blue; Sapphire": "#0f52ba",
    "Blue; Sky": "#87ceeb",
    "Blue; Slate": "#708090",
    "Blue; Soft": "#87ceeb",
    "Blue; Steel": "#4682b4",
    "Blue; Storm": "#4f6d7a",
    "Blue; Teal": "#008080",
    "Blue; Turquoise": "#40e0d0",
    "Blue; Ultramarine": "#120a8f",
    "Brown": "#8b4513",
    "Brown; Auburn": "#a52a2a",
    "Brown; Caramel": "#af6e4d",
    "Brown; Chestnut": "#954535",
    "Brown; Chocolate": "#7b3f00",
    "Brown; Coffee": "#6f4e37",
    "Brown; Cool": "#5c4033",
    "Brown; Copper": "#b87333",
    "Brown; Dark": "#3d2817",
    "Brown; Dark Mahogany": "#8b0000",
    "Brown; Espresso": "#3d2817",
    "Brown; Hazel": "#8b7355",
    "Brown; Light": "#a0826d",
    "Brown; Mahogany": "#c04000",
    "Brown; Medium": "#6b4423",
    "Brown; Mocha": "#6f4e37",
    "Brown; Neutral": "#6b4423",
    "Brown; Rose": "#8b5a5a",
    "Brown; Sandy": "#f4a460",
    "Brown; Sepia": "#704214",
    "Brown; Soft Copper": "#cd7f32",
    "Brown; Tawny": "#cd853f",
    "Brown; Walnut": "#5c4033",
    "Brown; Warm": "#8b4513",
    "Gold; Amber": "#ffbf00",
    "Gold; Bright": "#ffd700",
    "Gold; Dark": "#b8860b",
    "Gold; Honey": "#f0c674",
    "Gold; Light": "#ffd700",
    "Gold; Metallic": "#d4af37",
    "Gold; Soft": "#f4c430",
    "Gold; Warm": "#ffd700",
    "Gray; Ash": "#b2beb5",
    "Gray; Charcoal": "#36454f",
    "Gray; Cool": "#808080",
    "Gray; Dark": "#696969",
    "Gray; Gunmetal": "#2a3439",
    "Gray; Light": "#d3d3d3",
    "Gray; Metallic": "#8c8c8c",
    "Gray; Pale": "#d3d3d3",
    "Gray; Pearl": "#e8e0d9",
    "Gray; Platinum": "#e5e4e2",
    "Gray; Slate": "#708090",
    "Gray; Smoke": "#848484",
    "Gray; Smoky": "#848484",
    "Gray; Soft": "#c0c0c0",
    "Gray; Steel": "#4682b4",
    "Gray; Warm": "#a9a9a9",
    "Green; Aquatic": "#00ced1",
    "Green; Chartreuse": "#7fff00",
    "Green; Cool": "#2e8b57",
    "Green; Dark": "#006400",
    "Green; Emerald": "#50c878",
    "Green; Fern": "#4f7942",
    "Green; Forest": "#228b22",
    "Green; Jade": "#00a86b",
    "Green; Kelly": "#4cbb17",
    "Green; Light": "#90ee90",
    "Green; Lime": "#32cd32",
    "Green; Mint": "#98ff98",
    "Green; Neon": "#39ff14",
    "Green; Olive": "#808000",
    "Green; Pale": "#98fb98",
    "Green; Peacock": "#33a1c9",
    "Green; Pistachio": "#93c572",
    "Green; Sage": "#87ae73",
    "Green; Sea": "#2e8b57",
    "Green; Soft": "#90ee90",
    "Green; Warm": "#228b22",
    "Heterochromia; Central": "#808080",
    "Heterochromia; L Blue / R Brown": "#4169e1",
    "Heterochromia; L Blue / R Green": "#4169e1",
    "Heterochromia; L Brown / R Blue": "#8b4513",
    "Heterochromia; L Brown / R Green": "#8b4513",
    "Heterochromia; L Gold / R Blue": "#ffd700",
    "Heterochromia; L Gold / R Brown": "#ffd700",
    "Heterochromia; L Gold / R Green": "#ffd700",
    "Heterochromia; L Gray / R Blue": "#808080",
    "Heterochromia; L Gray / R Brown": "#808080",
    "Heterochromia; L Gray / R Green": "#808080",
    "Heterochromia; L Green / R Blue": "#228b22",
    "Heterochromia; L Green / R Brown": "#228b22",
    "Heterochromia; L Hazel / R Blue": "#8b7355",
    "Heterochromia; L Hazel / R Green": "#8b7355",
    "Heterochromia; Sectoral": "#808080",
    "Medium": "#d2b48c",
    "Olive": "#bab86c",
    "Orange; Apricot": "#fbceb1",
    "Orange; Burnt": "#cc5500",
    "Orange; Dark": "#ff8c00",
    "Orange; Light": "#ffb347",
    "Orange; Peach": "#ffdab9",
    "Orange; Pumpkin": "#ff7518",
    "Orange; Rust": "#b7410e",
    "Orange; Sunset": "#fd5e53",
    "Orange; Tangerine": "#ffa500",
    "Orange; Vermilion": "#e34234",
    "Orange; Warm": "#ff7f50",
    "Pink; Baby": "#f4c2c2",
    "Pink; Blush": "#de5d83",
    "Pink; Bubblegum": "#ffc1cc",
    "Pink; Candy": "#ff1493",
    "Pink; Coral": "#ff7f50",
    "Pink; Dark": "#c71585",
    "Pink; Dusty": "#d4a5a5",
    "Pink; Dusty Rose": "#b76e79",
    "Pink; Fuchsia": "#ff00ff",
    "Pink; Hot": "#ff69b4",
    "Pink; Light": "#ffb6c1",
    "Pink; Magenta": "#ff00ff",
    "Pink; Neon": "#ff1493",
    "Pink; Pastel": "#ffb6c1",
    "Pink; Peach": "#ffdab9",
    "Pink; Rose": "#ff007f",
    "Pink; Salmon": "#fa8072",
    "Pink; Soft": "#ffb6c1",
    "Purple; Amethyst": "#9966cc",
    "Purple; Dark": "#4b0082",
    "Purple; Deep": "#4b0082",
    "Purple; Eggplant": "#614051",
    "Purple; Grape": "#6f2da8",
    "Purple; Indigo": "#4b0082",
    "Purple; Lavender": "#e6e6fa",
    "Purple; Light": "#d8bfd8",
    "Purple; Lilac": "#c8a2c8",
    "Purple; Magenta": "#ff00ff",
    "Purple; Mauve": "#e0b0ff",
    "Purple; Mulberry": "#c54b8c",
    "Purple; Orchid": "#da70d6",
    "Purple; Periwinkle": "#cc99ff",
    "Purple; Plum": "#dda0dd",
    "Purple; Raspberry": "#e30b5d",
    "Purple; Soft": "#d8bfd8",
    "Purple; Soft Lavender": "#e6e6fa",
    "Purple; Violet": "#8a2be2",
    "Red; Auburn": "#a52a2a",
    "Red; Blood": "#8b0000",
    "Red; Burgundy": "#800020",
    "Red; Burnt Copper": "#cc5500",
    "Red; Carmine": "#960018",
    "Red; Cherry": "#de3163",
    "Red; Cool": "#b22222",
    "Red; Copper": "#b87333",
    "Red; Crimson": "#dc143c",
    "Red; Dark": "#8b0000",
    "Red; Deep Copper": "#b87333",
    "Red; Fire": "#ff4500",
    "Red; Ginger": "#b06500",
    "Red; Light": "#ff6b6b",
    "Red; Raspberry": "#e30b5d",
    "Red; Ruby": "#e0115f",
    "Red; Scarlet": "#ff2400",
    "Red; Strawberry Blonde": "#ffdbcc",
    "Red; Warm": "#dc143c",
    "Red; Wine": "#722f37",
    "Silver; Ash": "#b2beb5",
    "Silver; Dark": "#808080",
    "Silver; Ice": "#b0e0e6",
    "Silver; Light": "#c0c0c0",
    "Silver; Metallic": "#aaa9ad",
    "Silver; Platinum": "#e5e4e2",
    "Silver; Soft": "#c9c0bb",
    "Silver; Steel": "#a8a8a8",
    "Silver; White": "#c0c0c0",
    "White; Beige": "#f5f5dc",
    "White; Cool": "#f0f8ff",
    "White; Cream": "#fffdd0",
    "White; Frost": "#e8f5e9",
    "White; Ghost": "#f8f8ff",
    "White; Ice": "#b0e0e6",
    "White; Ivory": "#fffff0",
    "White; Pearl": "#f8f6f0",
    "White; Pure": "#ffffff",
    "White; Snow": "#fffafa",
    "White; Soft": "#fafafa",
    "White; Warm": "#fdf5e6",
    "Yellow; Canary": "#ffef00",
    "Yellow; Dark": "#cccc00",
    "Yellow; Lemon": "#fff700",
    "Yellow; Light": "#ffff99",
    "Yellow; Mustard": "#ffdb58",
    "Yellow; Saffron": "#f4c430"
  }
};

// Individual exports for convenience
export const accentOptions: string[] = ["Boston","Brazilian Portuguese","Californian","Canadian","Caribbean","Chicago","Chicano English (Mexican-American)","Chinese","DEVELOPMENT","Dutch","German","Greek","Hawaiian Pidgin","Indian","Jamaican","Japanese","Korean","Midwestern","Minnesotan","New Orleans (cajun)","New York","New Zealand","Pacific Northwest","Philadelphia","Polish","Russian","South African","Southern Appalachian","Southern Californian (SoCal)","Texan","Turkish","Valley (California)","Welsh"];
export const ethnicity_raceOptions: string[] = ["African","African Descent","Afro-Caribbean","Afro-Latinx","Arab","Armenian","Ashkenazi Jewish","Asian","Asian Descent","Australian Aboriginal","Basque","Bengali","Berber","Bhutanese","Brazilian","Burmese","Cambodian","Caribbean","Caucasian","Caucasian / Pacific Islander","Chicano","Chinese","Creole","Cuban","Dominican","Druze","Eastern European","Egyptian","Ethiopian","Finnish","First Nations","French","German","German Descent","Gerudo / Sheikah","Ghanaian","Greek Descent","Guatemalan","Haitian","Hmong","Hylian","Icelandic","Igbo","Indigenous Australian","Indigenous Canadian","Inuit","Iranian","Iraqi","Israeli","Italian","Italian/Chinese","Japanese","Japanese/British","Jewish","Kazakh","Korean","Kurdish","Latinx","Lebanese","Lithuanian","Lithuanian / Romanian","Lithuanian/Mediterranean/French/Arabian","Lithuanian/Romanian/French/Arabian","Maori","Mayan","Mediterranean","Mediterranean Caucasian Mix","Mediterranean Descent","Meowth","Mestizo","Mexican","Mexican-American","Middle Eastern","Mongolian","Moravian","Nigerian","Pacific Islander","Palestinian","Pashtun","Persian","Polynesian Descent","Portuguese","Punjabi","Quechua","Roma","Romanian","Russian","Samoan","Sardinian","Scandinavian","Scanner","Sephardic Jewish","Sicilian","Somali","South Asian","Southeast Asian","Swahili","Syrian","Tibetan","Tlingit","Tongan","Turkish","Uyghur","Venezuelan","Vietnamese","West African","White","Yoruba"];
export const eye_colorOptions: string[] = ["Ash","Azure","Black","Black/Silver","Black; Ash","Black; Black/Silver","Black; Charcoal","Black; Jet","Black; Midnight","Black; Obsidian","Black; Onyx","Black; Raven","Black; Soft","Blonde; Ash","Blonde; Beige","Blonde; Butter","Blonde; Champagne","Blonde; Cream","Blonde; Dark","Blonde; Frosted","Blonde; Golden","Blonde; Honey","Blonde; Lemon","Blonde; Light","Blonde; Medium","Blonde; Neutral","Blonde; Platinum","Blonde; Sandy","Blonde; Silver","Blonde; Sunflower","Blonde; Vanilla","Blonde; White","Blood","Blue","Blue; Aqua","Blue; Azure","Blue; Baby","Blue; Cerulean","Blue; Cobalt","Blue; Cyan","Blue; Dark","Blue; Deep","Blue; Denim","Blue; Ice","Blue; Indigo","Blue; Light","Blue; Midnight","Blue; Navy","Blue; Pale","Blue; Royal","Blue; Sapphire","Blue; Sky","Blue; Slate","Blue; Soft","Blue; Steel","Blue; Storm","Blue; Teal","Blue; Turquoise","Blue; Ultramarine","Brown","Brown; Auburn","Brown; Caramel","Brown; Chestnut","Brown; Chocolate","Brown; Coffee","Brown; Cool","Brown; Copper","Brown; Dark","Brown; Dark Mahogany","Brown; Espresso","Brown; Hazel","Brown; Light","Brown; Mahogany","Brown; Medium","Brown; Mocha","Brown; Neutral","Brown; Rose","Brown; Sandy","Brown; Sepia","Brown; Soft Copper","Brown; Tawny","Brown; Walnut","Brown; Warm","Bubblegum","Burnt","Cardinal","Carmine","Coral","Crimson","Deep","Espresso","Gold","Gold; Amber","Gold; Bright","Gold; Dark","Gold; Honey","Gold; Light","Gold; Metallic","Gold; Soft","Gold; Warm","Gray","Gray; Ash","Gray; Charcoal","Gray; Cool","Gray; Dark","Gray; Gunmetal","Gray; Light","Gray; Metallic","Gray; Pale","Gray; Pearl","Gray; Platinum","Gray; Slate","Gray; Smoke","Gray; Smoky","Gray; Soft","Gray; Steel","Gray; Warm","Green","Green/Pink","Green; Aquatic","Green; Chartreuse","Green; Cool","Green; Dark","Green; Emerald","Green; Fern","Green; Forest","Green; Jade","Green; Kelly","Green; Light","Green; Lime","Green; Mint","Green; Neon","Green; Olive","Green; Pale","Green; Peacock","Green; Pistachio","Green; Sage","Green; Sea","Green; Soft","Green; Warm","Heterochromia; Central","Heterochromia; L Blue / R Brown","Heterochromia; L Blue / R Green","Heterochromia; L Brown / R Blue","Heterochromia; L Brown / R Green","Heterochromia; L Gold / R Blue","Heterochromia; L Gold / R Brown","Heterochromia; L Gold / R Green","Heterochromia; L Gray / R Blue","Heterochromia; L Gray / R Brown","Heterochromia; L Gray / R Green","Heterochromia; L Green / R Blue","Heterochromia; L Green / R Brown","Heterochromia; L Hazel / R Blue","Heterochromia; L Hazel / R Green","Heterochromia; Sectoral","Ice","Indigo","Lemon","Light","Lilac","Lime","Multi","Orange","Orange; Apricot","Orange; Burnt","Orange; Dark","Orange; Light","Orange; Peach","Orange; Pumpkin","Orange; Rust","Orange; Sunset","Orange; Tangerine","Orange; Vermilion","Orange; Warm","Pink","Pink; Baby","Pink; Blush","Pink; Bubblegum","Pink; Candy","Pink; Coral","Pink; Dark","Pink; Dusty","Pink; Dusty Rose","Pink; Fuchsia","Pink; Hot","Pink; Light","Pink; Magenta","Pink; Neon","Pink; Pastel","Pink; Peach","Pink; Rose","Pink; Salmon","Pink; Soft","Purple","Purple; Amethyst","Purple; Dark","Purple; Deep","Purple; Eggplant","Purple; Grape","Purple; Indigo","Purple; Lavender","Purple; Light","Purple; Lilac","Purple; Magenta","Purple; Mauve","Purple; Mulberry","Purple; Orchid","Purple; Periwinkle","Purple; Plum","Purple; Raspberry","Purple; Soft","Purple; Soft Lavender","Purple; Violet","Red","Red; Auburn","Red; Blood","Red; Burgundy","Red; Burnt Copper","Red; Carmine","Red; Cherry","Red; Cool","Red; Copper","Red; Crimson","Red; Dark","Red; Deep Copper","Red; Fire","Red; Ginger","Red; Light","Red; Raspberry","Red; Ruby","Red; Scarlet","Red; Strawberry Blonde","Red; Warm","Red; Wine","Silver; Ash","Silver; Dark","Silver; Ice","Silver; Light","Silver; Metallic","Silver; Platinum","Silver; Soft","Silver; Steel","Silver; White","White; Beige","White; Cool","White; Cream","White; Frost","White; Ghost","White; Ice","White; Ivory","White; Pearl","White; Pure","White; Snow","White; Soft","White; Warm","Yellow","Yellow; Canary","Yellow; Dark","Yellow; Lemon","Yellow; Light","Yellow; Mustard","Yellow; Saffron"];
export const gender_identityOptions: string[] = ["Agender","Androgynous","Bigender","Cisgender","Demiboy","Demigirl","Genderfluid","Genderqueer","Intersex","Neutrois","Non-binary","Pangender","Third Gender","Transgender","Two-spirit"];
export const hair_colorOptions: string[] = ["Ash","Baby","Beige","Black","Black/Silver","Black; Ash","Black; Black/Silver","Black; Charcoal","Black; Jet","Black; Midnight","Black; Obsidian","Black; Onyx","Black; Raven","Black; Soft","Blonde","Blonde; Ash","Blonde; Beige","Blonde; Butter","Blonde; Champagne","Blonde; Cream","Blonde; Dark","Blonde; Frosted","Blonde; Golden","Blonde; Honey","Blonde; Lemon","Blonde; Light","Blonde; Medium","Blonde; Neutral","Blonde; Platinum","Blonde; Sandy","Blonde; Silver","Blonde; Sunflower","Blonde; Vanilla","Blonde; White","Blue","Blue; Aqua","Blue; Azure","Blue; Baby","Blue; Cerulean","Blue; Cobalt","Blue; Cyan","Blue; Dark","Blue; Deep","Blue; Denim","Blue; Ice","Blue; Indigo","Blue; Light","Blue; Midnight","Blue; Navy","Blue; Pale","Blue; Royal","Blue; Sapphire","Blue; Sky","Blue; Slate","Blue; Soft","Blue; Steel","Blue; Storm","Blue; Teal","Blue; Turquoise","Blue; Ultramarine","Brown","Brown; Auburn","Brown; Caramel","Brown; Chestnut","Brown; Chocolate","Brown; Coffee","Brown; Cool","Brown; Copper","Brown; Dark","Brown; Dark Mahogany","Brown; Espresso","Brown; Hazel","Brown; Light","Brown; Mahogany","Brown; Medium","Brown; Mocha","Brown; Neutral","Brown; Rose","Brown; Sandy","Brown; Sepia","Brown; Soft Copper","Brown; Tawny","Brown; Walnut","Brown; Warm","Cobalt","Cool","Dark","Dusty","Dusty Rose","Fern","Gold; Amber","Gold; Bright","Gold; Dark","Gold; Honey","Gold; Light","Gold; Metallic","Gold; Soft","Gold; Warm","Gray","Gray; Ash","Gray; Charcoal","Gray; Cool","Gray; Dark","Gray; Gunmetal","Gray; Light","Gray; Metallic","Gray; Pale","Gray; Pearl","Gray; Platinum","Gray; Slate","Gray; Smoke","Gray; Smoky","Gray; Soft","Gray; Steel","Gray; Warm","Green","Green; Aquatic","Green; Chartreuse","Green; Cool","Green; Dark","Green; Emerald","Green; Fern","Green; Forest","Green; Jade","Green; Kelly","Green; Light","Green; Lime","Green; Mint","Green; Neon","Green; Olive","Green; Pale","Green; Peacock","Green; Pistachio","Green; Sage","Green; Sea","Green; Soft","Green; Warm","Heterochromia; Central","Heterochromia; L Blue / R Brown","Heterochromia; L Blue / R Green","Heterochromia; L Brown / R Blue","Heterochromia; L Brown / R Green","Heterochromia; L Gold / R Blue","Heterochromia; L Gold / R Brown","Heterochromia; L Gold / R Green","Heterochromia; L Gray / R Blue","Heterochromia; L Gray / R Brown","Heterochromia; L Gray / R Green","Heterochromia; L Green / R Blue","Heterochromia; L Green / R Brown","Heterochromia; L Hazel / R Blue","Heterochromia; L Hazel / R Green","Heterochromia; Sectoral","Jade","Medium","Neutral","Olive","Orange","Orange; Apricot","Orange; Burnt","Orange; Dark","Orange; Light","Orange; Peach","Orange; Pumpkin","Orange; Rust","Orange; Sunset","Orange; Tangerine","Orange; Vermilion","Orange; Warm","Pink","Pink; Baby","Pink; Blush","Pink; Bubblegum","Pink; Candy","Pink; Coral","Pink; Dark","Pink; Dusty","Pink; Dusty Rose","Pink; Fuchsia","Pink; Hot","Pink; Light","Pink; Magenta","Pink; Neon","Pink; Pastel","Pink; Peach","Pink; Rose","Pink; Salmon","Pink; Soft","Pumpkin","Purple","Purple; Amethyst","Purple; Dark","Purple; Deep","Purple; Eggplant","Purple; Grape","Purple; Indigo","Purple; Lavender","Purple; Light","Purple; Lilac","Purple; Magenta","Purple; Mauve","Purple; Mulberry","Purple; Orchid","Purple; Periwinkle","Purple; Plum","Purple; Raspberry","Purple; Soft","Purple; Soft Lavender","Purple; Violet","Red; Auburn","Red; Blood","Red; Burgundy","Red; Burnt Copper","Red; Carmine","Red; Cherry","Red; Cool","Red; Copper","Red; Crimson","Red; Dark","Red; Deep Copper","Red; Fire","Red; Ginger","Red; Light","Red; Raspberry","Red; Ruby","Red; Scarlet","Red; Strawberry Blonde","Red; Warm","Red; Wine","Silver","Silver; Ash","Silver; Dark","Silver; Ice","Silver; Light","Silver; Metallic","Silver; Platinum","Silver; Soft","Silver; Steel","Silver; White","Soft","Tawny","White","White; Beige","White; Cool","White; Cream","White; Frost","White; Ghost","White; Ice","White; Ivory","White; Pearl","White; Pure","White; Snow","White; Soft","White; Warm","Yellow; Canary","Yellow; Dark","Yellow; Lemon","Yellow; Light","Yellow; Mustard","Yellow; Saffron"];
export const mbtiOptions: string[] = ["ENFJ","ENFP","ENTJ","ENTP","ESFJ","ESFP","ESTJ","ESTP","INFJ","INFP","INTJ","INTP","ISFJ","ISFP","ISTJ","ISTP"];
export const moralOptions: string[] = ["Chaotic Evil","Chaotic Good","Chaotic Neutral","Lawful Evil","Lawful Good","Lawful Neutral","Neutral Evil","Neutral Good","True Neutral"];
export const nationalityOptions: string[] = ["Afghan","American","Argentine","Australian","Austrian","Bangladeshi","Belgian","Bosnian","Brazilian","British","Bulgarian","Canadian","Chilean","Chinese","Colombian","Costa Rican","Croatian","Cuban","Czech","Danish","Dominican","Dutch","Egyptian","Emirati","Ethiopian","Filipino","Finnish","French","German","Greek","Haitian","Hungarian","Icelandic","Inariko","Indian","Indonesian","Iranian","Iraqi","Irish","Israeli","Italian","Jamaican","Japanese","Jordanian","Kenyan","Konohagakure","Korean","Lebanese","Malaysian","Mexican","Mongolian","Moroccan","New Zealander (Kiwi)","Nigerian","Norwegian","Pakistani","Palestinian","Panamanian","Peruvian","Polish","Portuguese","Romanian","Rudania","Russian","Saudi Arabian","Scottish","Serbian","Singaporean","South African","Spanish","Sri Lankan","Sun Empire","Sunagakure","Swedish","Swiss","Syrian","Thai","Trinidadian","Turkish","Ukrainian","Venezuelan","Vhintl","Vietnamese","Welsh"];
export const negative_traitsOptions: string[] = ["ABRASIVE","ABRUPT","AGONIZING","AIMLESS","AIRY","ALOOF","AMORAL","ANGRY","ASOCIAL","ASSERTIVE","ASTIGMATIC","BARBARIC","BEWILDERED","BIZARRE","BLAND","BLUNT","BOISTEROUS","BRITTLE","BRUTAL","CALCULATING","CALLOUS","CANTANKEROUS","CARELESS","CAUTIOUS","CHARMLESS","CHILDISH","CLUMSY","COARSE","COLD","COLORLESS","COMPLACENT","COMPLAINTIVE","COMPULSIVE","CONCEITED","CONDEMNATORY","CONFORMIST","CONFUSED","CONTEMPTIBLE","CONVENTIONAL","COWARDLY","CRAFTY","CRASS","CRAZY","CRIMINAL","CRITICAL","CRUDE","CRUEL","CYNICAL","DECADENT","DECEITFUL","DELICATE","DEMANDING","DEPENDENT","DESPERATE","DESTRUCTIVE","DEVIOUS","DIFFICULT","DIRTY","DISCONCERTING","DISCONTENTED","DISCOURAGING","DISCOURTEOUS","DISHONEST","DISLOYAL","DISOBEDIENT","DISORDERLY","DISORGANIZED","DISPUTATIOUS","DISRESPECTFUL","DISRUPTIVE","DISSOLUTE","DISSONANT","DISTRACTIBLE","DISTURBING","DOGMATIC","DOMINEERING","DULL","EASILY DISCOURAGED","EGOCENTRIC","ENERVATED","ENVIOUS","ERRATIC","ESCAPIST","EXCITABLE","EXPEDIENT","EXTRAVAGANT","EXTREME","FAITHLESS","FANATICAL","FANCIFUL","FATALISTIC","FAWNING","FEARFUL","FICKLE","FIERY","FIXED","FLAMBOYANT","FOOLISH","FORGETFUL","FRAUDULENT","FRIGHTENING","FRIVOLOUS","GLOOMY","GRACELESS","GRAND","GREEDY","GRIM","GULLIBLE","HATEFUL","HAUGHTY","HEDONISTIC","HESITANT","HIDEBOUND","HIGH-HANDED","HOSTILE","IGNORANT","IMITATIVE","IMPATIENT","IMPRACTICAL","IMPRUDENT","IMPULSIVE","INCONSIDERATE","INCURIOUS","INDECISIVE","INDULGENT","INERT","INHIBITED","INSECURE","INSENSITIVE","INSINCERE","INSULTING","INTOLERANT","IRASCIBLE","IRRATIONAL","IRRESPONSIBLE","IRRITABLE","LAZY","LIBIDINOUS","LOQUACIOUS","MALICIOUS","MANIPULATIVE","MANNERED","MANNERLESS","MAWKISH","MEALY MOUTHED","MECHANICAL","MEDDLESOME","MELANCHOLIC","MERETRICIOUS","MESSY","MISERABLE","MISERLY","MISGUIDED","MISTAKEN","MONEY-MINDED","MONSTROUS","MOODY","MORBID","MUDDLE-HEADED","NAIVE","NARCISSISTIC","NARROW","NARROW-MINDED","NATTY","NEGATIVISTIC","NEGLECTFUL","NEUROTIC","NIHILISTIC","OBNOXIOUS","OBSESSIVE","OBVIOUS","ODD","OFFHAND","ONE-DIMENSIONAL","ONE-SIDED","OPINIONATED","OPPORTUNISTIC","OPPRESSED","OUTRAGEOUS","OVER IMAGINATIVE","PARANOID","PASSIVE","PEDANTIC","PERVERSE","PETTY","PHARISAICAL","PHLEGMATIC","PLODDING","POMPOUS","POSSESSIVE","POWER-HUNGRY","PREDATORY","PREJUDICED","PRESUMPTUOUS","PRETENTIOUS","PRIM","PROCRASTINATING","PROFLIGATE","PROVOCATIVE","PUGNACIOUS","PURITANICAL","QUIRKY","REACTIONARY","REACTIVE","REGIMENTAL","REGRETFUL","REPENTANT","REPRESSED","RESENTFUL","RIDICULOUS","RIGID","RITUALISTIC"];
