-- Seed setting/location options to dropdown_options table
INSERT INTO dropdown_options (field, option) VALUES
('setting', 'A Villa'),
('setting', 'Abattoir (Slaughterhouse)'),
('setting', 'Abbey'),
('setting', 'Academy'),
('setting', 'Academy (Alchemist)'),
('setting', 'Academy (Arcane)'),
('setting', 'Academy (Artificer''s)'),
('setting', 'Academy (Bards)'),
('setting', 'Academy (Healers)'),
('setting', 'Academy (Mages)'),
('setting', 'Academy (Military)'),
('setting', 'Academy (Naval)'),
('setting', 'Academy (Royal)'),
('setting', 'Academy (Science)'),
('setting', 'An Oasis'),
('setting', 'Aquarium'),
('setting', 'Aqueduct'),
('setting', 'Arcade'),
('setting', 'Archives'),
('setting', 'Archway'),
('setting', 'Arena'),
('setting', 'Arena (Gladiatorial)'),
('setting', 'Arena (Music)'),
('setting', 'Arena (Performance)'),
('setting', 'Arena (Racing)'),
('setting', 'Arena (Sports)'),
('setting', 'Army Base'),
('setting', 'Art Gallery'),
('setting', 'Art Museum'),
('setting', 'Asylum'),
('setting', 'Auction House'),
('setting', 'Auditorium'),
('setting', 'Aviary'),
('setting', 'Bakery'),
('setting', 'Balcony'),
('setting', 'Bar'),
('setting', 'Barn'),
('setting', 'Barracks'),
('setting', 'Basement'),
('setting', 'Basement (Cellar)'),
('setting', 'Bathhouse'),
('setting', 'Battle Ground'),
('setting', 'Bazaar'),
('setting', 'Beach'),
('setting', 'Behind a Waterfall'),
('setting', 'Bistro'),
('setting', 'Black Market'),
('setting', 'Black Market (Underground Market)'),
('setting', 'Blue Lagoon'),
('setting', 'Board (Message)'),
('setting', 'Board (Quest)'),
('setting', 'Boutique'),
('setting', 'Brewery'),
('setting', 'Bridge'),
('setting', 'Bridge (Covered Bridge)'),
('setting', 'Bridge (Draw Bridge)'),
('setting', 'Bridge (Rope Bridge)'),
('setting', 'Bridge (Sky Bridge)'),
('setting', 'Broadway'),
('setting', 'Brothel'),
('setting', 'Bungalow'),
('setting', 'Burial Mound'),
('setting', 'Cabin'),
('setting', 'Cache'),
('setting', 'Cache (Pirates)'),
('setting', 'Cache (Rebel)'),
('setting', 'Cache (Smugglers)'),
('setting', 'Cache (Thieves)'),
('setting', 'Caer / Cair (Stronghold)'),
('setting', 'Cafe'),
('setting', 'Cairn'),
('setting', 'Canal'),
('setting', 'Caravan (Wagons)'),
('setting', 'Caravan (Merchant)'),
('setting', 'Caravan (Military)'),
('setting', 'Caravan (Nomads)'),
('setting', 'Caravan (Pilgrims)'),
('setting', 'Caravan (Prison)'),
('setting', 'Caravan (Refugee)'),
('setting', 'Caravan (Settlers)'),
('setting', 'Caravan (Slavers)'),
('setting', 'Casino'),
('setting', 'Casino (Gambling Hall)'),
('setting', 'Castle'),
('setting', 'Catacombs'),
('setting', 'Cathedral'),
('setting', 'Causeway'),
('setting', 'Cellar'),
('setting', 'Cellar (Root)'),
('setting', 'Cellar (Storm)'),
('setting', 'Cellar (Wine)'),
('setting', 'Cemetery'),
('setting', 'Chain Tower'),
('setting', 'Chapel'),
('setting', 'Chapel Bridge'),
('setting', 'Chateau'),
('setting', 'Church'),
('setting', 'Circle of Stones'),
('setting', 'Circle of Wagons'),
('setting', 'Circus'),
('setting', 'Cistern'),
('setting', 'Citadel'),
('setting', 'City'),
('setting', 'City Hall'),
('setting', 'Civic Center'),
('setting', 'Cliff Dwellings'),
('setting', 'Clinic'),
('setting', 'Clock Tower'),
('setting', 'College'),
('setting', 'College (Alchemist)'),
('setting', 'College (Arcane)'),
('setting', 'College (Bards)'),
('setting', 'College (Healers)'),
('setting', 'College (Mages)'),
('setting', 'College (Naval)'),
('setting', 'College (Of Artificers)'),
('setting', 'College (Of Science)'),
('setting', 'College (Royal)'),
('setting', 'Colosseum'),
('setting', 'Community Center'),
('setting', 'Conservatory'),
('setting', 'Conservatory (Greenhouse)'),
('setting', 'Corral'),
('setting', 'Corral (Cattle)'),
('setting', 'Corral (Horse)'),
('setting', 'Corral (Livestock)'),
('setting', 'Cottage'),
('setting', 'Courthouse'),
('setting', 'Crater Lake'),
('setting', 'Crematorium'),
('setting', 'Croft'),
('setting', 'Crypt'),
('setting', 'Dam'),
('setting', 'Dance Studio'),
('setting', 'Death Valley'),
('setting', 'Den'),
('setting', 'Den (Assassins)'),
('setting', 'Den (Drug)'),
('setting', 'Den (Gambling)'),
('setting', 'Den (Hookah)'),
('setting', 'Den (Opium)'),
('setting', 'Den (Smugglers)'),
('setting', 'Den (Thieves)'),
('setting', 'Desert'),
('setting', 'Dig Site'),
('setting', 'Dig Site (Fossils)'),
('setting', 'Dig Site (Minerals)'),
('setting', 'Dig Site (Ruins)'),
('setting', 'Dike'),
('setting', 'Dock'),
('setting', 'Dock (Boat)'),
('setting', 'Dock (Ship)'),
('setting', 'Dock (Airship)'),
('setting', 'Dockyard'),
('setting', 'Dojo'),
('setting', 'Dojo (Sparring Hall)'),
('setting', 'Dojo (Training Hall)'),
('setting', 'Dome'),
('setting', 'Drug Den'),
('setting', 'Drug Lounge'),
('setting', 'Drug Parlor'),
('setting', 'Dugout'),
('setting', 'Dugout (Pit-House)'),
('setting', 'Dungeon'),
('setting', 'Embassy'),
('setting', 'Embassy (Country)'),
('setting', 'Embassy (Race)'),
('setting', 'Embassy (Realm)'),
('setting', 'Embassy (World)'),
('setting', 'Emporium'),
('setting', 'Estate'),
('setting', 'Factory'),
('setting', 'Factory (Assembly Line)'),
('setting', 'Fairgrounds'),
('setting', 'Farm'),
('setting', 'Farm (Animal)'),
('setting', 'Farm (Crop)'),
('setting', 'Farm (Dairy)'),
('setting', 'Farm (Share Croppers)'),
('setting', 'Farmer''s Market'),
('setting', 'Farmhouse'),
('setting', 'Ferry'),
('setting', 'Fighting Pit'),
('setting', 'Fisherman''s Wharf'),
('setting', 'Florist'),
('setting', 'Flotilla'),
('setting', 'Flotilla (Town)'),
('setting', 'Flotilla (Village)'),
('setting', 'Flotilla (City)'),
('setting', 'Forest'),
('setting', 'Forester''s House'),
('setting', 'Forge'),
('setting', 'Fort'),
('setting', 'Fortress'),
('setting', 'Fort (Coastal)'),
('setting', 'Fort (Island)'),
('setting', 'Fort (Mountain)'),
('setting', 'Fort (Sea)'),
('setting', 'Fort (Wooden)'),
('setting', 'Fort (Stone)'),
('setting', 'Fort (Metal)'),
('setting', 'Fortifications'),
('setting', 'Fortifications (Cheval De Frise)'),
('setting', 'Fortifications (Moat)'),
('setting', 'Fortifications (Palisade)'),
('setting', 'Fortifications (Towers)'),
('setting', 'Fortifications (Trench)'),
('setting', 'Fortifications (Wall)'),
('setting', 'Fortifications (Wooden Stakes)'),
('setting', 'Funeral Home'),
('setting', 'Gallery'),
('setting', 'Gallows'),
('setting', 'Gallows (Gibbet)'),
('setting', 'Gambling Den'),
('setting', 'Gambling Hall'),
('setting', 'Gambling Lounge'),
('setting', 'Gambling Parlor'),
('setting', 'Garden'),
('setting', 'Gardens'),
('setting', 'Garden (Crop)'),
('setting', 'Garden (Flower)'),
('setting', 'Garden (Hanging)'),
('setting', 'Garden (Herb)'),
('setting', 'Garden (Mushroom)'),
('setting', 'Garden (Rock)'),
('setting', 'Garden (Rooftop)'),
('setting', 'Garden (Sculpture)'),
('setting', 'Garden (Zen)'),
('setting', 'Garrison'),
('setting', 'Gate House'),
('setting', 'Gate'),
('setting', 'Gates'),
('setting', 'Ghost Town'),
('setting', 'Giant''s Causeway'),
('setting', 'Gibbet'),
('setting', 'Glacier'),
('setting', 'Granary'),
('setting', 'Grange'),
('setting', 'Grave'),
('setting', 'Grave (Fresh)'),
('setting', 'Grave (Marker)'),
('setting', 'Grave (Mass)'),
('setting', 'Grave (Open)'),
('setting', 'Grave (Site)'),
('setting', 'Grave (Stone)'),
('setting', 'Grave (Vacated)'),
('setting', 'Grave (Yard)'),
('setting', 'Graveyard'),
('setting', 'Greenhouse'),
('setting', 'Grounds'),
('setting', 'Grounds (Burial)'),
('setting', 'Grounds (Fair)'),
('setting', 'Grounds (Parade)'),
('setting', 'Grounds (Sacred)'),
('setting', 'Grounds (Tourney)'),
('setting', 'Grounds (Training)'),
('setting', 'Guard Post'),
('setting', 'Guild'),
('setting', 'Guild Hall'),
('setting', 'Guild House'),
('setting', 'Haberdashery'),
('setting', 'Hall'),
('setting', 'Hall (City)'),
('setting', 'Hall (Gambling)'),
('setting', 'Hall (Guild)'),
('setting', 'Hall (Mead)'),
('setting', 'Hall (Meeting)'),
('setting', 'Hall (Music)'),
('setting', 'Hall (Opera)'),
('setting', 'Hall (Town)'),
('setting', 'Hall (Training)'),
('setting', 'Harbor'),
('setting', 'Hatchery'),
('setting', 'Hatchery (Animal)'),
('setting', 'Hatchery (Beast)'),
('setting', 'Hatchery (Monster)'),
('setting', 'Heaven'),
('setting', 'Hedge Maze'),
('setting', 'Henge'),
('setting', 'Hideout'),
('setting', 'Hold'),
('setting', 'Horreum'),
('setting', 'Horreum (Warehouse)'),
('setting', 'Hospital'),
('setting', 'Hostel'),
('setting', 'Hostel (Bed & Breakfast)'),
('setting', 'House'),
('setting', 'House (Bath)'),
('setting', 'House (Boat)'),
('setting', 'House (Coach)'),
('setting', 'House (Coffee)'),
('setting', 'House (Farm)'),
('setting', 'House (Guest)'),
('setting', 'House (Guild)'),
('setting', 'House (Long)'),
('setting', 'House (Manor)'),
('setting', 'House (Opera)'),
('setting', 'House (Ritual)'),
('setting', 'House (Safe)'),
('setting', 'House (Smoke)'),
('setting', 'House (Summer)'),
('setting', 'House (Tea)'),
('setting', 'House (Theater)'),
('setting', 'House (Turf)'),
('setting', 'House (Winter)'),
('setting', 'Hovel'),
('setting', 'Hut'),
('setting', 'Huts'),
('setting', 'Hut (Adobe)'),
('setting', 'Hut (Cloth)'),
('setting', 'Hut (Earthen)'),
('setting', 'Hut (Grass)'),
('setting', 'Hut (Hide)'),
('setting', 'Hut (Ice)'),
('setting', 'Hut (Mud)'),
('setting', 'Hut (Snow)'),
('setting', 'Hut (Stone)'),
('setting', 'Hut (Straw)'),
('setting', 'Hut (Wood)'),
('setting', 'Inn'),
('setting', 'Island'),
('setting', 'Jail'),
('setting', 'Junkyard'),
('setting', 'Keep'),
('setting', 'Kremlin'),
('setting', 'Labyrinth'),
('setting', 'Library'),
('setting', 'Library (Arcane)'),
('setting', 'Library (Great)'),
('setting', 'Library (Royal)'),
('setting', 'Lift'),
('setting', 'Lift (Wench & Platform)'),
('setting', 'Lighthouse'),
('setting', 'Lock'),
('setting', 'Locks'),
('setting', 'Lock (Waterway)'),
('setting', 'Lodge'),
('setting', 'Lodge (Hunting)'),
('setting', 'Lodge (Masons)'),
('setting', 'Lodge (Medicine)'),
('setting', 'Lodge (Porters)'),
('setting', 'Lodge (Safari)'),
('setting', 'Lodge (Secret Society)'),
('setting', 'Lodge (Sweat)'),
('setting', 'Lodge (Wardens)'),
('setting', 'Lost City'),
('setting', 'Lumberyard'),
('setting', 'Magical Construct'),
('setting', 'Magical Construct (Energy Construct)'),
('setting', 'Magical Construct (Giant Levitating Crystal)'),
('setting', 'Magical Construct (Moving Sculpture)'),
('setting', 'Magical Construct (Rune Stones)'),
('setting', 'Magical Construct (Sigil Stones)'),
('setting', 'Mall'),
('setting', 'Manor'),
('setting', 'Marina'),
('setting', 'Marker Stone'),
('setting', 'Marker Stone (Border Stone)'),
('setting', 'Marker Stone (Boundary Stone)'),
('setting', 'Market'),
('setting', 'Market Place'),
('setting', 'Market Square'),
('setting', 'Matterhorn'),
('setting', 'Mausoleum'),
('setting', 'Mead Hall'),
('setting', 'Meadow'),
('setting', 'Mecca'),
('setting', 'Meeting House'),
('setting', 'Memorial'),
('setting', 'Meteor Crater'),
('setting', 'Mews'),
('setting', 'Midden'),
('setting', 'Midden (Heap)'),
('setting', 'Midden (Mound)'),
('setting', 'Midden (Pile)'),
('setting', 'Mill'),
('setting', 'Minaret'),
('setting', 'Mine'),
('setting', 'Mines'),
('setting', 'Mine (Coal)'),
('setting', 'Mine (Crystal)'),
('setting', 'Mine (Crystal - Normal)'),
('setting', 'Mine (Crystal - Magic)'),
('setting', 'Mine (Gem Stone)'),
('setting', 'Mine (Gem Stone - Normal)'),
('setting', 'Mine (Gem Stone - Magic)'),
('setting', 'Mine (Guano)'),
('setting', 'Mine (Metal)'),
('setting', 'Mine (Metal - Normal)'),
('setting', 'Mine (Metal - Magic)'),
('setting', 'Mine (Mineral)'),
('setting', 'Mine (Mineral - Normal)'),
('setting', 'Mine (Mineral - Magic)'),
('setting', 'Mine (Salt)'),
('setting', 'Mine (Substance)'),
('setting', 'Moat'),
('setting', 'Moat (Dry)'),
('setting', 'Moat (Lava)'),
('setting', 'Moat (Mud)'),
('setting', 'Moat (Quicksand)'),
('setting', 'Moat (Spiked)'),
('setting', 'Moat (Tar)'),
('setting', 'Moat (Water)'),
('setting', 'Monastery'),
('setting', 'Monolith'),
('setting', 'Monument'),
('setting', 'Mosque'),
('setting', 'Mound'),
('setting', 'Mound (Burial)'),
('setting', 'Mound (Ceremonial)'),
('setting', 'Mound (Midden)'),
('setting', 'Mound (Shell)'),
('setting', 'Mound (Temple)'),
('setting', 'Museum'),
('setting', 'No Man''s Land'),
('setting', 'Nunnery'),
('setting', 'Nunnery (Convent)'),
('setting', 'Nursery'),
('setting', 'Oasis'),
('setting', 'Obelisk'),
('setting', 'Observation Tower'),
('setting', 'Observatory'),
('setting', 'Ocean Floor'),
('setting', 'Opera Hall'),
('setting', 'Opera House'),
('setting', 'Opium Den'),
('setting', 'Orchard'),
('setting', 'Orphanage'),
('setting', 'Outpost'),
('setting', 'Paddock'),
('setting', 'Palace'),
('setting', 'Parade Grounds'),
('setting', 'Parade Grounds (Training Grounds)'),
('setting', 'Park'),
('setting', 'Parlor'),
('setting', 'Parlour'),
('setting', 'Parlor (Drug)'),
('setting', 'Parlor (Massage)'),
('setting', 'Parlor (Tattoo)'),
('setting', 'Pawnshop'),
('setting', 'Pharmacy'),
('setting', 'Pier'),
('setting', 'Pillar'),
('setting', 'Pillars'),
('setting', 'Pirate Ship'),
('setting', 'Pit'),
('setting', 'Pit (Dwelling)'),
('setting', 'Pit (Fighting)'),
('setting', 'Pit (Monster)'),
('setting', 'Pit (Prison)'),
('setting', 'Pit (Slave)'),
('setting', 'Plantation'),
('setting', 'Playground'),
('setting', 'Piazza'),
('setting', 'Port'),
('setting', 'Prison'),
('setting', 'Pub'),
('setting', 'Public Garden'),
('setting', 'Public Square'),
('setting', 'Pyramid'),
('setting', 'Pyre'),
('setting', 'Pyre (Funeral)'),
('setting', 'Quarry'),
('setting', 'Quarry (Crystal)'),
('setting', 'Quarry (Magic Crystal)'),
('setting', 'Quarry (Metal)'),
('setting', 'Quarry (Mineral)'),
('setting', 'Quarry (Stone)'),
('setting', 'Quarry (Substance)'),
('setting', 'Rainforest'),
('setting', 'Ranch'),
('setting', 'Ranch (Animal)'),
('setting', 'Ranch (Monster)'),
('setting', 'Root Cellar'),
('setting', 'Ruins'),
('setting', 'Rune Stone'),
('setting', 'Saloon'),
('setting', 'Sanctuary'),
('setting', 'Sauna'),
('setting', 'Sawmill'),
('setting', 'School'),
('setting', 'Sculpture'),
('setting', 'Sculpture (Large)'),
('setting', 'Sculpture (Giant)'),
('setting', 'Sculpture (Garden)'),
('setting', 'Sculpture (Scale City Model)'),
('setting', 'Sea Gate'),
('setting', 'Sea Wall'),
('setting', 'Sewer'),
('setting', 'Sewers'),
('setting', 'Shack'),
('setting', 'Shanty Town'),
('setting', 'Shelter'),
('setting', 'Ship Graveyard'),
('setting', 'Shipwreck'),
('setting', 'Shipyard'),
('setting', 'Shipyards'),
('setting', 'Shrine'),
('setting', 'Shrine (Deity)'),
('setting', 'Shrine (Druidic)'),
('setting', 'Shrine (Element)'),
('setting', 'Shrine (Power)'),
('setting', 'Shrine (Environment)'),
('setting', 'Shrine (Guardian)'),
('setting', 'Shrine (Luck)'),
('setting', 'Shrine (Magic)'),
('setting', 'Shrine (Old One)'),
('setting', 'Shrine (Outsider)'),
('setting', 'Shrine (Spirit)'),
('setting', 'Siege Tower'),
('setting', 'Site'),
('setting', 'Site (Building)'),
('setting', 'Site (Camp)'),
('setting', 'Site (Construction)'),
('setting', 'Site (Dig)'),
('setting', 'Site (Excavation)'),
('setting', 'Site (Grave)'),
('setting', 'Site (Ritual)'),
('setting', 'Skyscraper'),
('setting', 'Slaughter House'),
('setting', 'Slums'),
('setting', 'Smithy'),
('setting', 'Sparring Hall'),
('setting', 'Square'),
('setting', 'Square (Market)'),
('setting', 'Square (Public)'),
('setting', 'Square (Town)'),
('setting', 'Stables'),
('setting', 'Stadium'),
('setting', 'Statue'),
('setting', 'Statue (Idol)'),
('setting', 'Statue (Large)'),
('setting', 'Statue (Giant)'),
('setting', 'Statue (Guardian)'),
('setting', 'Statue (Monument)'),
('setting', 'Stockade'),
('setting', 'Stockyard'),
('setting', 'Stonehenge'),
('setting', 'Storehouse'),
('setting', 'Warehouse'),
('setting', 'Street Vendors'),
('setting', 'Street Vendors (Alcove)'),
('setting', 'Street Vendors (Booth)'),
('setting', 'Street Vendors (Cart)'),
('setting', 'Street Vendors (Stall)'),
('setting', 'Street Vendors (Stand)'),
('setting', 'Street Vendors (Tent)'),
('setting', 'Stronghold'),
('setting', 'Sunken City'),
('setting', 'Sunken Ruins'),
('setting', 'Sunken Ship'),
('setting', 'Sunken Temple'),
('setting', 'Supply Post'),
('setting', 'Swamp'),
('setting', 'Sweat Shop'),
('setting', 'Tailor'),
('setting', 'Taphouse'),
('setting', 'Tavern'),
('setting', 'Tea House'),
('setting', 'Tearoom'),
('setting', 'Temple'),
('setting', 'Tent City'),
('setting', 'Tent City (Merchant)'),
('setting', 'Tent City (Military)'),
('setting', 'Tent City (Nomads)'),
('setting', 'Tent City (Pilgrims)'),
('setting', 'Tent City (Refugee)'),
('setting', 'Tent City (Settlers)'),
('setting', 'Tent City (Squatters)'),
('setting', 'Tomb'),
('setting', 'Totem Pole'),
('setting', 'Tower'),
('setting', 'Tower (Bell)'),
('setting', 'Tower (Chain)'),
('setting', 'Tower (Clock)'),
('setting', 'Tower (Guard)'),
('setting', 'Tower (Peel)'),
('setting', 'Tower (Siege)'),
('setting', 'Tower (Signal)'),
('setting', 'Tower (Watch)'),
('setting', 'Tower (Wizard)'),
('setting', 'Tower Bridge'),
('setting', 'Town'),
('setting', 'Town Hall'),
('setting', 'Trade Route'),
('setting', 'Trading Post'),
('setting', 'Train'),
('setting', 'Training Grounds'),
('setting', 'Training Hall'),
('setting', 'Tree House'),
('setting', 'Tree Town'),
('setting', 'Tunnel'),
('setting', 'University'),
('setting', 'University (Alchemist)'),
('setting', 'University (Arcane)'),
('setting', 'University (Artificer''s)'),
('setting', 'University (Bards)'),
('setting', 'University (Healers)'),
('setting', 'University (Mages)'),
('setting', 'University (Naval)'),
('setting', 'University (Of Science)'),
('setting', 'University (Royal)'),
('setting', 'Vault'),
('setting', 'Villa'),
('setting', 'Villa (Large Country House / Estate)'),
('setting', 'Village'),
('setting', 'Vineyard'),
('setting', 'Watch Tower'),
('setting', 'Water Mill'),
('setting', 'Waterfall'),
('setting', 'Well'),
('setting', 'Well (Artesian)'),
('setting', 'Well (Covered)'),
('setting', 'Well (Dry)'),
('setting', 'Well (House)'),
('setting', 'Well (Of Magic)'),
('setting', 'Well (Water)'),
('setting', 'Well House'),
('setting', 'Wharf'),
('setting', 'Windmill'),
('setting', 'Winery'),
('setting', 'Work Camp'),
('setting', 'Yurt'),
('setting', 'Zoo'),
('setting', 'Zoo (Mundane)'),
('setting', 'Zoo (Rare)'),
('setting', 'Zoo (Exotic)'),
('setting', 'Zoo (Magical)'),
('setting', 'Zoo (Alien Creatures)')
ON CONFLICT (field, option) DO NOTHING;
