-- Seed trope options to dropdown_options table
INSERT INTO dropdown_options (field, option) VALUES
('trope', 'Absent Father'),
('trope', 'Absent-Minded Professor'),
('trope', 'Ace Pilot'),
('trope', 'Action Hero'),
('trope', 'Addict'),
('trope', 'Ambitious Queen'),
('trope', 'Angry Chef'),
('trope', 'Annoying Neighbor'),
('trope', 'Anti-Hero'),
('trope', 'Authority Figure'),
('trope', 'Backstabbing Friend'),
('trope', 'Bad Boy'),
('trope', 'Bad Friend'),
('trope', 'Bard'),
('trope', 'Beatnik'),
('trope', 'Believer'),
('trope', 'Benevolent Ruler'),
('trope', 'Besterman'),
('trope', 'Bitter War Veteran'),
('trope', 'Black Knight'),
('trope', 'Blind Seer'),
('trope', 'Boss'),
('trope', 'Boy Next Door'),
('trope', 'Braggart'),
('trope', 'Brains and Brawn'),
('trope', 'Bully'),
('trope', 'Bumbling Sidekick'),
('trope', 'Bureaucrat'),
('trope', 'Byronic Hero'),
('trope', 'Career Criminal'),
('trope', 'Caretaker'),
('trope', 'Cat Lady'),
('trope', 'Catalyst'),
('trope', 'Child Saviour'),
('trope', 'Childhood Friend'),
('trope', 'Chooser of the Chosen One'),
('trope', 'Chosen One'),
('trope', 'Chuunibyou'),
('trope', 'Cinderella Type'),
('trope', 'Class Clown'),
('trope', 'Comic Relief'),
('trope', 'Competent Man'),
('trope', 'Complicated Past'),
('trope', 'Con Artist'),
('trope', 'Contender'),
('trope', 'Coward'),
('trope', 'Crazy Cat Lady'),
('trope', 'Creepy Twins'),
('trope', 'Crone'),
('trope', 'Curmudgeon'),
('trope', 'Damsel in Distress'),
('trope', 'Dandere'),
('trope', 'Dandy'),
('trope', 'Dark Jester'),
('trope', 'Dark Lady'),
('trope', 'Dark Lord'),
('trope', 'Dastardly Whiplash'),
('trope', 'Deredere'),
('trope', 'Devil Incarnate / Dark Lord'),
('trope', 'Devotee'),
('trope', 'Divorced Dad'),
('trope', 'Doppelgänger'),
('trope', 'Double Agent'),
('trope', 'Dragon Lady'),
('trope', 'Dreamer'),
('trope', 'Drill Sergeant'),
('trope', 'Dumb Blonde'),
('trope', 'Dumb Muscle'),
('trope', 'Easy Adapter'),
('trope', 'Eccentric Foreigner'),
('trope', 'Elderly Martial Arts Master'),
('trope', 'Elderly Master'),
('trope', 'Emotionally Repressed'),
('trope', 'Empath'),
('trope', 'Enabler'),
('trope', 'Eternal Klutz'),
('trope', 'Everyman/Woman'),
('trope', 'Evil Clown'),
('trope', 'Evil Matriarch'),
('trope', 'Evil Twin'),
('trope', 'Experiment Gone Wrong'),
('trope', 'Explorer'),
('trope', 'Fall Guy'),
('trope', 'Fallen / Corrupter'),
('trope', 'Farmer''s Daughter'),
('trope', 'Farmer''s Wife'),
('trope', 'Female Clown'),
('trope', 'Femme Fatale'),
('trope', 'Final Girl'),
('trope', 'Foil'),
('trope', 'Folk Hero'),
('trope', 'Fool'),
('trope', 'Fop'),
('trope', 'French Maid'),
('trope', 'Friendly Rival'),
('trope', 'Gay Best Friend'),
('trope', 'Geek'),
('trope', 'Generic Horror Girl'),
('trope', 'Generic Slasher'),
('trope', 'Genius'),
('trope', 'Gentle Giant'),
('trope', 'Gentleman Thief'),
('trope', 'Gifted Child'),
('trope', 'Girl Next Door'),
('trope', 'God / Goddess'),
('trope', 'Good Guy / Traditional Hero'),
('trope', 'Good Samaritan'),
('trope', 'Grande Dame'),
('trope', 'Grieving Widow'),
('trope', 'Groupie'),
('trope', 'Guardian Grandparents'),
('trope', 'Guide'),
('trope', 'Hag'),
('trope', 'Halfbreed Harlot'),
('trope', 'Hard Worker'),
('trope', 'Hard-Boiled Detective'),
('trope', 'Harlequin'),
('trope', 'Harsh Judge'),
('trope', 'Hedonist'),
('trope', 'Hermit'),
('trope', 'Himbo/Bimbo'),
('trope', 'Hime/Ouji Dere'),
('trope', 'Hippy'),
('trope', 'Holmesian Detective'),
('trope', 'Hooker with a Heart of Gold'),
('trope', 'Hopeless Romantic'),
('trope', 'Hotshot'),
('trope', 'Housewife'),
('trope', 'Idiot'),
('trope', 'Idiot Savant'),
('trope', 'Idiot Turned Hero'),
('trope', 'Immigrant'),
('trope', 'Imposter / Pretender'),
('trope', 'Incompetent Officer'),
('trope', 'Ingenue'),
('trope', 'Innocent'),
('trope', 'Innovator'),
('trope', 'Invasive Neighbor'),
('trope', 'Jaded Lead'),
('trope', 'Jock'),
('trope', 'Joker / Jester'),
('trope', 'Journalist'),
('trope', 'Kamidere'),
('trope', 'Knight-Errant'),
('trope', 'Kuudere'),
('trope', 'Leader'),
('trope', 'Legacy Hero'),
('trope', 'Liar'),
('trope', 'Little Green Men'),
('trope', 'Living Legend'),
('trope', 'Loathly Lady'),
('trope', 'Logician'),
('trope', 'Loner'),
('trope', 'Loose Cannon / Crooked Cop'),
('trope', 'Lovable Loser'),
('trope', 'Lovable Pervert'),
('trope', 'Love Interest'),
('trope', 'Lovers'),
('trope', 'Macho Action Guy'),
('trope', 'Mad Scientist'),
('trope', 'Magician / Mage / Shaman'),
('trope', 'Maiden'),
('trope', 'Male Buffoon'),
('trope', 'Malewife'),
('trope', 'Man Alone'),
('trope', 'Manic Pixie Dream Girl'),
('trope', 'Martyr'),
('trope', 'Mary Sue'),
('trope', 'Masked Superhero'),
('trope', 'Masochist'),
('trope', 'Maverick'),
('trope', 'Mean Popular Girl'),
('trope', 'Mentor'),
('trope', 'Messenger'),
('trope', 'Messiah'),
('trope', 'Middle Child'),
('trope', 'Milkman'),
('trope', 'Miltonic Hero'),
('trope', 'Momma''s Boy'),
('trope', 'Monk'),
('trope', 'Monster'),
('trope', 'Mother-In-Law'),
('trope', 'Mother''s Boy'),
('trope', 'Mother / Matriarch'),
('trope', 'Mythological King'),
('trope', 'Napoleonic Villain'),
('trope', 'Narrator'),
('trope', 'Nature Lover'),
('trope', 'Nemesis'),
('trope', 'Nerd'),
('trope', 'Nice Guy'),
('trope', 'Noble Savage'),
('trope', 'Non-Conformist'),
('trope', 'Out-of-Towner'),
('trope', 'Outcast'),
('trope', 'Outlaw'),
('trope', 'Overly Patient Wife'),
('trope', 'Paranoid Conspiracy Theorist'),
('trope', 'Patriarch'),
('trope', 'Peacemaker'),
('trope', 'Perfectionist'),
('trope', 'Perpetual Traveler'),
('trope', 'Petrushka'),
('trope', 'Philosopher'),
('trope', 'Pierrot'),
('trope', 'Pinning Friend'),
('trope', 'Pirate'),
('trope', 'Predator'),
('trope', 'Preppy'),
('trope', 'Prey'),
('trope', 'Prince Charming'),
('trope', 'Prince on a White Horse'),
('trope', 'Princesse Lointaine'),
('trope', 'Psycho-Biddy'),
('trope', 'Psychopath'),
('trope', 'Puppeteer'),
('trope', 'Rags to Riches'),
('trope', 'Raw Recruit'),
('trope', 'Rebel'),
('trope', 'Redneck'),
('trope', 'Redshirt'),
('trope', 'Reluctant Hero'),
('trope', 'Reluctant / Unwilling Monster'),
('trope', 'Rich Woman'),
('trope', 'Rightful Heir'),
('trope', 'Rightful King'),
('trope', 'Robin Hood'),
('trope', 'Romantic Runner-Up'),
('trope', 'Royal Usurper'),
('trope', 'Savant'),
('trope', 'Scapegoat'),
('trope', 'Schoolma''am'),
('trope', 'Scrooge'),
('trope', 'Secretive'),
('trope', 'Senex Amans'),
('trope', 'Senex Iratus'),
('trope', 'Servant / Slave'),
('trope', 'Sexy Grandma'),
('trope', 'Shapeshifter'),
('trope', 'Shrew'),
('trope', 'Sickly'),
('trope', 'Sidekick'),
('trope', 'Sinnekins'),
('trope', 'Sissy'),
('trope', 'Skeptic'),
('trope', 'Sleazy Lawyer'),
('trope', 'Sleazy Politician'),
('trope', 'Slow Burn'),
('trope', 'Soubrette'),
('trope', 'Southern Belle'),
('trope', 'Spear Carrier'),
('trope', 'Stand-In Parent / Role Model'),
('trope', 'Star-Crossed Lovers'),
('trope', 'Starving Artist'),
('trope', 'Straight Man'),
('trope', 'Student'),
('trope', 'Stupid Muscle'),
('trope', 'Super Soldier'),
('trope', 'Superfluous Man'),
('trope', 'Superhero'),
('trope', 'Supersoldier'),
('trope', 'Supervillain'),
('trope', 'Surfer'),
('trope', 'Surprise Genius'),
('trope', 'Survivalist'),
('trope', 'Survivor'),
('trope', 'Swashbuckler'),
('trope', 'Thrill-Seeker'),
('trope', 'Thug'),
('trope', 'Tiger Mom'),
('trope', 'Tomboy'),
('trope', 'Tortured Artist'),
('trope', 'Tortured Superhero'),
('trope', 'Town Drunk'),
('trope', 'Traditionalist'),
('trope', 'Tragic Hero'),
('trope', 'Trickster'),
('trope', 'Tricky Slave'),
('trope', 'Troubled Teenager'),
('trope', 'Troubled Vet'),
('trope', 'Trusty Sidekick'),
('trope', 'Truth Seeker'),
('trope', 'Tsundere'),
('trope', 'Turncoat'),
('trope', 'Tyrant'),
('trope', 'Underling / Henchman'),
('trope', 'Unfortunate Orphan'),
('trope', 'Unknown Threat'),
('trope', 'Unlikely Hero'),
('trope', 'Unseen Character'),
('trope', 'Vice'),
('trope', 'Vigilante'),
('trope', 'Village Idiot'),
('trope', 'Villain'),
('trope', 'Visionary'),
('trope', 'Wannabe Hero'),
('trope', 'Warrior'),
('trope', 'Well-Intentioned Extremist'),
('trope', 'Whiskey Priest'),
('trope', 'Wicked Stepmother'),
('trope', 'Wicked Witch'),
('trope', 'Wimp'),
('trope', 'Wise Fool'),
('trope', 'Wise Mentor'),
('trope', 'Wise Old Man'),
('trope', 'Workaholic'),
('trope', 'Youngest Child')
ON CONFLICT (field, option) DO NOTHING;
